	PROGRAM AXIS02

	CALL POPEN

	CALL PARSE_COMMAND_LINE ('axis02')
	CALL PSETC('PAGE_ID_LINE_USER_TEXT','TESTS/AXIS02') 
C
C	SET PAGE AND SUBPAGE
C
	CALL PSETR('SUPER_PAGE_Y_LENGTH',29.7)
	CALL PSETR('SUPER_PAGE_X_LENGTH',21.0)
	CALL PSETR('PAGE_Y_LENGTH',29.7)
	CALL PSETR('PAGE_X_LENGTH',21.0)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PSETR('SUBPAGE_X_LENGTH',18.0)
	CALL PSETR('SUBPAGE_Y_POSITION',20.8)
	CALL PSETR('SUBPAGE_X_POSITION',1.0)
	CALL PSETC('SUBPAGE_MAP_PROJECTION','NONE')
	CALL PSETC('PAGE_FRAME','OFF')   
	CALL PSETC('SUBPAGE_FRAME','OFF')   
	CALL PSETR('TEXT_REFERENCE_CHARACTER_HEIGHT',0.3)
	CALL PSETC('TEXT_MODE','POSITIONAL')
	CALL PSETC('TEXT_LINE_1','Data Units = DAYS, same month ')
	CALL PSETC('TEXT_LINE_2','  ')
	CALL PSETC('TEXT_LINE_3','AXIS_DATE_TYPE    DAYS')
	CALL PSETC('TEXT_LINE_4',
     x 'AXIS_DATE_MIN_VALUE  1995-06-01 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1995-06-10 00:00:00')
	CALL PSETC('TEXT_LINE_6','AXIS_TICK_INTERVAL     1.0')
	CALL PSETI('TEXT_LINE_COUNT',6)
	CALL PSETC('TEXT_JUSTIFICATION','LEFT')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',21.8)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT
C
C	SELECT THE PROJECTION (MUST BE DONE BEFORE CALLING PGRIB)
C
	CALL PSETC('AXIS_DATE_MIN_VALUE','1995-06-01 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1995-06-10 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','DAYS')         
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC('TEXT_LINE_1','Data Units = DAYS, consecutive months ')
	CALL PSETC('TEXT_LINE_2','  ')
	CALL PSETC('TEXT_LINE_4',
     x 'AXIS_DATE_MIN_VALUE  1991-06-25 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1991-07-04 00:00:00')
	CALL PSETI('TEXT_LINE_COUNT',5)
	CALL PSETR('SUBPAGE_Y_POSITION',11.9)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',12.9)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT
	CALL PSETR('SUBPAGE_Y_LENGTH',3.0)
	CALL PSETC('AXIS_DATE_MIN_VALUE','1991-06-25 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1991-06-04 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','DAYS')         
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = YEARS')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x 'AXIS_DATE_MIN_VALUE  1991-01-01 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x 'AXIS_DATE_MAX_VALUE  1999-01-01 00:00:00')
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_DATE_TYPE    YEARS ')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',4.0)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PSETR('SUBPAGE_Y_POSITION',3.0)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PTEXT
	CALL PSETC('AXIS_DATE_MIN_VALUE','1991-01-01 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1999-01-01 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','YEARS')         
C	CALL PSETC('AXIS_YEARS_LABEL','OFF')
                 
	CALL PAXIS 
C
C	CLOSE MAGICS
C
	CALL PNEW('PAGE')
	CALL TWO
	CALL PNEW('PAGE')
	CALL THREE
	CALL PCLOSE

      STOP
	END
      SUBROUTINE TWO
	CALL PSETR('SUBPAGE_Y_POSITION',20.8)
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = MONTHS')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x  'AXIS_DATE_MIN_VALUE  1995-06-01 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1996-03-01 00:00:00')
	CALL PSETC ('TEXT_LINE_6',
     X     'AXIS_DAYS_LABEL    NAME')
	CALL PSETC ('TEXT_LINE_7',
     X     'AXIS_DAYS_NAME_COMPOSITION = FULL')
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_DATE_TYPE    MONTHS')
	CALL PSETI('TEXT_LINE_COUNT',5)
	CALL PSETC('TEXT_JUSTIFICATION','LEFT')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',21.8)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT

C
C	SELECT THE PROJECTION (MUST BE DONE BEFORE CALLING PGRIB)
C
	CALL PSETC('AXIS_DATE_MIN_VALUE','1995-06-01 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1996-03-01 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','MONTHS')         
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = HOURS, same day  ') 
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x  'AXIS_DATE_MIN_VALUE  1995-06-25 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1995-06-25 09:00:00')
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_TYPE    HOURS')
	CALL PSETI('TEXT_LINE_COUNT',6)
	CALL PSETR('SUBPAGE_Y_POSITION',11.9)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',12.9)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT
	CALL PSETR('SUBPAGE_Y_LENGTH',3.0)
	CALL PSETC('AXIS_DATE_MIN_VALUE','1995-06-25 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1995-06-25 09:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','HOURS')         
	CALL PSETC('AXIS_HOURS_LABEL','ON')                 
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = DAYS, using HOURS')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x  'AXIS_DATE_MIN_VALUE  1995-06-25 15:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1995-07-02 18:00:00')
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_TYPE    DAYS')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',4.0)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PSETR('SUBPAGE_Y_POSITION',3.0)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PTEXT
	CALL PSETC('AXIS_DATE_MIN_VALUE','1995-06-25 15:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1995-07-02 18:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','DAYS')         
	CALL PSETC('AXIS_HOURS_LABEL','OFF')                 
                 
	CALL PAXIS 
cCALL PRESET('AXIS_BASE_DATE')
C
C	CLOSE MAGICS
C
	RETURN
	END
      SUBROUTINE THREE
	CALL PSETR('SUBPAGE_Y_POSITION',20.8)
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = DAYS, full day name but not '//
     X   ' day number')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x  'AXIS_DATE_MIN_VALUE  1991-06-25 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1991-07-04 00:00:00')
	CALL PSETC ('TEXT_LINE_6',
     X     'AXIS_DAYS_LABEL    NAME')
	CALL PSETC ('TEXT_LINE_7',
     X     'AXIS_DAYS_NAME_COMPOSITION = FULL')
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_DATE_TYPE    DAYS')
	CALL PSETI('TEXT_LINE_COUNT',7)
	CALL PSETC('TEXT_JUSTIFICATION','LEFT')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',21.8)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT

C
C	SELECT THE PROJECTION (MUST BE DONE BEFORE CALLING PGRIB)
C
	CALL PSETC('AXIS_DATE_MIN_VALUE','1991-06-25 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1991-07-04 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','DAYS')         
	CALL PSETC('AXIS_DAYS_LABEL','DAY')                 
	CALL PSETC('AXIS_DAYS_LABEL_COMPOSITION','FULL')
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = DAYS, day number but '//
     X    'not day name')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC ('TEXT_LINE_6',
     X     'AXIS_DAYS_LABEL    NUMBER')
	CALL PSETI('TEXT_LINE_COUNT',6)
	CALL PSETR('SUBPAGE_Y_POSITION',11.9)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',12.9)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PTEXT
	CALL PSETR('SUBPAGE_Y_LENGTH',3.0)
	CALL PSETC('AXIS_DATE_MIN_VALUE','1991-06-25 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1991-07-04 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','DAYS')         
	CALL PSETC('AXIS_DAYS_LABEL','NUMBER')                 
	CALL PAXIS 
	CALL PNEW('SUBPAGE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Data units = MONTHS, year labels '//
     X    ' turned off')
	CALL PSETC ('TEXT_LINE_2',
     X  '  ') 
	CALL PSETC('TEXT_LINE_4',
     x  'AXIS_DATE_MIN_VALUE  1991-06-25 00:00:00')
	CALL PSETC('TEXT_LINE_5',
     x  'AXIS_DATE_MAX_VALUE  1992-06-25 00:00:00')
	CALL PSETC ('TEXT_LINE_6',
     X     'AXIS_YEARS_LABEL  OFF     ')   
	CALL PSETC ('TEXT_LINE_3',
     X     'AXIS_TYPE    MONTHS')
	CALL PSETR('TEXT_BOX_X_POSITION',2.0)  
	CALL PSETR('TEXT_BOX_Y_POSITION',4.0)  
	CALL PSETR('TEXT_BOX_X_LENGTH',15.0)  
	CALL PSETR('TEXT_BOX_Y_LENGTH',7.8)
	CALL PSETR('SUBPAGE_Y_POSITION',3.0)
	CALL PSETR('SUBPAGE_Y_LENGTH',1.0)
	CALL PTEXT
	CALL PSETC('AXIS_DATE_MIN_VALUE','1991-06-25 00:00:00')
	CALL PSETC('AXIS_DATE_MAX_VALUE','1992-06-25 00:00:00')
	CALL PSETR('AXIS_TICK_INTERVAL',1.0)        
	CALL PSETC('AXIS_TYPE','DATE')         
	CALL PSETC('AXIS_DATE_TYPE','MONTHS')         
	CALL PSETC('AXIS_YEARS_LABEL','OFF')
                 
	CALL PAXIS 
C
C	CLOSE MAGICS
C
	RETURN
	END


#include "parse_command_line.h"
