C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM GRAPH_EPS_STAT
		
	  CHARACTER AREA*20,STEPC*4,STEPT*4,CLASS*10
	  CHARACTER YD*8
      CHARACTER*72 TEXTH,TEXTHH
      DIMENSION   ID(400),CLUST(400),TUBES(400),
     &			CTHR(400),CSEAS(400),TRAD(400),RLOW(400),STDC(400),
     &			STDT(400),CCERR(400),TSEAS(400),TCERR(400)
	  CHARACTER*19 XD(400),FDATEI,FDATEF
	  
	  OPEN (UNIT=10,FILE='/scratch/mo/moz/eps.dat',
     &	  			STATUS='OLD', FORM='FORMATTED')
	  
	  READ(10,'(A10,I2)')CLASS,IEXP
	  READ(10,'(A20)')AREA
	  READ(10,*)NSTEPC,NSTEPT

	  WRITE(STEPC,'(I3)')NSTEPC
	  WRITE(STEPT,'(I3)')NSTEPT

10	  CONTINUE
	
	  ND=ND+1	     
 	 
	  READ(10,*,END=20) IYMD,CLUST(ND),TUBES(ND),STDC(ND),STDT(ND),
     &	       CSEAS(ND),TSEAS(ND),CTHR(ND),TRAD(ND),CCERR(ND),TCERR(ND)    

      write (yd,'(i8)') iymd
      XD(ND)=YD(1:4)//'-'//YD(5:6)//'-'//YD(7:8)//' 00:00:00'

      GOTO 10
    
20    CONTINUE

	  ND=ND-1
	  FDATEI=XD(1)
	  FDATEF=XD(ND)
      WRITE (*,*) FDATEI,'  ',FDATEF

C*** OPEN MAGICS AND SET PAGE PARAMETERS

C     Open MAGICS and set the output device

      CALL POPEN
      CALL PARSE_COMMAND_LINE ('metops_cluster_tube_old')

c     Note: Replaced the following line with the next one for the
C     Magics++ test suite
c	  CALL PSETC('WORKSTATION_1','PS_COL_A3')
      CALL PSETC ('PS_DEVICE',    'ps_a3')


      PX=29.7
      PY=42.0
      ppx=29.6
      ppy=20.9

      CALL PSETR('SUPER_PAGE_X_LENGTH',PX)
      CALL PSETR('SUPER_PAGE_Y_LENGTH',PY)
      CALL PSETR('PAGE_X_LENGTH',PPX)
      CALL PSETR('PAGE_Y_LENGTH',PPY)
      CALL PSETR('SUBPAGE_Y_LENGTH',12.6225)
      CALL PSETR('SUBPAGE_X_LENGTH',25.245)
      CALL PSETR('SUBPAGE_Y_POSITION',2.5)  
      CALL PSETC('PAGE_ID_LINE','ON')
      
CCCC		CLUSTERS

C---------- heading legend
C---------- plot options

       TEXTH='CLUSTERS'//'     '//'500hPa'
       TEXTHH='Area :'//area//' step:+'//stepc
       
       call psetc('TEXT_QUALITY','HIGH')
       CALL PSETC('TEXT_COLOUR','BLACK')
       CALL PSETI('TEXT_LINE_COUNT',2)
       call psetc('TEXT_LINE_1',TEXTH)
       CALL PSETC('TEXT_LINE_2',TEXTHH)

       call psetc('LEGEND','ON')
       call psetc('LEGEND_ENTRY','ON')
       call psetc('LEGEND_BORDER','ON')
       CALL PSETC('LEGEND_TEXT_QUALITY','HIGH')
       CALL PSETC('LEGEND_TEXT_COLOUR','BLACK')
       CALL PSETR('LEGEND_ENTRY_X_GAP',0.20)
       CALL PSETR('LEGEND_BOX_X_LENGTH',4.0)
       CALL PSETR('LEGEND_BOX_Y_LENGTH',3.5)
       CALL PSETR('LEGEND_ENTRY_MAXIMUM_WIDTH',4.0)
       CALL PSETR('LEGEND_ENTRY_MINIMUM_HEIGHT',0.1)

       call psetc('LEGEND_TEXT_COMPOSITION','USER_TEXT_ONLY')
       call psetc('LEGEND_USER_TEXT_1','clusters')
   	   call psetc('LEGEND_USER_TEXT_2','eps_std')
	   call psetc('LEGEND_USER_TEXT_3','control error')
       call psetc('LEGEND_USER_TEXT_4','calib. std')
	   call psetc('LEGEND_USER_TEXT_5','clust. thr.')
	  
	
      call PTEXT

C--------------- Axis ----------------------------------
C-------- PLOT HORIZONTAL AXIS ------------------------
 
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_TITLE','ON')
            CALL PSETC('AXIS_ORIENTATION','HORIZONTAL')
            CALL PSETC('AXIS_POSITION','BOTTOM')
            CALL PSETC('AXIS_TYPE','DATE')
            CALL PSETC('AXIS_DATE_TYPE','DAYS')
            CALL PSETC('AXIS_DATE_MIN_VALUE',FDATEI)
            CALL PSETC('AXIS_DATE_MAX_VALUE',FDATEF)
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETR('AXIS_TICK_INTERVAL',1.0)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_DAYS_LABEL_COLOUR','BLACK')
            CALL PSETC('AXIS_DAYS_LABEL','NUMBER')
            CALL PSETC('AXIS_LINE','ON')
            CALL PSETI('AXIS_TICK_THICKNESS',4)
		    CALL PSETI('AXIS_LINE_THICKNESS',4)
            CALL PAXIS


C-------- PLOT VERTICAL AXIS ----------------------------
            
C##### Bar vertical axis 

            CALL PSETC('AXIS_ORIENTATION','VERTICAL')
            CALL PSETC('AXIS_TYPE','REGULAR')
            CALL PSETC('AXIS_POSITION','RIGHT')
            CALL PSETR('AXIS_MIN_VALUE',0.0)
            CALL PSETR('AXIS_MAX_VALUE',12.0)
            CALL PSETC('AXIS_TICK_POSITIONING','REGULAR')
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETR('AXIS_TICK_INTERVAL',1.0)
            CALL PSETC('AXIS_TICK_LABEL_TYPE','NUMBER')
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_TICK_LABEL_FORMAT','(I2)')
            CALL PSETI('AXIS_TICK_LABEL_FREQUENCY',2)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_MINOR_TICK','OFF')
            CALL PSETI('AXIS_MINOR_TICK_COUNT',1)

            CALL PSETC('AXIS_LINE','ON')
            CALL PSETI('AXIS_LINE_THICKNESS',4)
            CALL PSETI('AXIS_TICK_THICKNESS',4)
            CALL PSETC('AXIS_TITLE','ON')
            CALL PSETC('AXIS_TITLE_ORIENTATION','PARALLEL')
            CALL PSETC('AXIS_TITLE_QUALITY','HIGH')
            CALL PSETC('AXIS_TITLE_TEXT','n. of clusters')
C---- GRIDDING LINES

            CALL PSETC('AXIS_GRID','ON')
            CALL PSETC('AXIS_GRID_COLOUR','BLACK')
            CALL PSETI('AXIS_GRID_THICKNESS',2)
            CALL PSETC('AXIS_GRID_LINE_STYLE','DOT')

 
      		CALL PAXIS

C-------- SETTING THE GRAPH ----------------------------

cc### Bar graph ---CLUSTERS--

      CALL PSETC('GRAPH_TYPE','BAR')
      CALL PSETC('GRAPH_SHADE','ON')
      CALL PSETC('GRAPH_SHADE_STYLE','AREA_FILL')
      CALL PSETC('GRAPH_SHADE_COLOUR','BLACK')
      CALL PSETR('GRAPH_BAR_WIDTH',0.2)
      CALL PSET1C('GRAPH_BAR_DATE_X_VALUES',XD,ND)
C      CALL PSET1R('GRAPH_BAR_Y_LOWER_VALUES',RLOW,ND)
      CALL PSET1R('GRAPH_BAR_Y_UPPER_VALUES', CLUST,ND)

      CALL PGRAPH

   
cc# Curve
            CALL PSETC('AXIS_ORIENTATION','VERTICAL')
            CALL PSETC('AXIS_POSITION','LEFT')
            CALL PSETR('AXIS_MIN_VALUE',0.0)
            CALL PSETR('AXIS_MAX_VALUE',180.0)
            CALL PSETC('AXIS_TICK_POSITIONING','REGULAR')
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETR('AXIS_TICK_INTERVAL',10.0)
            CALL PSETC('AXIS_TICK_LABEL_TYPE','NUMBER')
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_TICK_LABEL_FORMAT','(AUTOMATIC)')
            CALL PSETI('AXIS_TICK_LABEL_FREQUENCY',2)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_MINOR_TICK','OFF')
            CALL PSETC('AXIS_TITLE_TEXT','metres')

C---- GRIDDING LINES

            CALL PSETC('AXIS_GRID','OFF')
            CALL PSETC('AXIS_GRID_COLOUR','BLACK')
            CALL PSETI('AXIS_GRID_THICKNESS',3)
            CALL PSETC('AXIS_GRID_LINE_STYLE','DOT')

			CALL PAXIS

			CALL PSETI('GRAPH_LINE_THICKNESS',4)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','BLUE')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',STDC,ND)

			CALL PGRAPH

			CALL PSETI('GRAPH_LINE_THICKNESS',4)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','BROWN')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSETC('GRAPH_MISSING_DATA_MODE','IGNORE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',CCERR,ND)

			CALL PGRAPH

			CALL PSETI('GRAPH_LINE_THICKNESS',2)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','RED')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',CSEAS,ND)

			CALL PGRAPH

			CALL PSETI('GRAPH_LINE_THICKNESS',2)
			CALL PSETC('GRAPH_LINE_STYLE','DASH')
			CALL PSETC('GRAPH_LINE_COLOUR','BLUE')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',CTHR,ND)

			CALL PGRAPH
			CALL PNEW('PAGE')

cc###########	--TUBES--
       		TEXTH='TUBES'//'     '//'500hPa'
            	TEXTHH='Area :'//area//'  step:+'//stept
		    
		    call psetc('TEXT_QUALITY','HIGH')
       		CALL PSETC('TEXT_COLOUR','BLACK')
       		CALL PSETI('TEXT_LINE_COUNT',2)
       		call psetc('TEXT_LINE_1',TEXTH)
       		CALL PSETC('TEXT_LINE_2',TEXTHH)

       		call psetc('LEGEND','ON')
       		call psetc('LEGEND_ENTRY','ON')
       		call psetc('LEGEND_BORDER','ON')
       		CALL PSETC('LEGEND_TEXT_QUALITY','HIGH')
       		CALL PSETC('LEGEND_TEXT_COLOUR','BLACK')
       		CALL PSETR('LEGEND_ENTRY_X_GAP',0.20)
       		CALL PSETR('LEGEND_BOX_X_LENGTH',4.0)
       		CALL PSETR('LEGEND_BOX_Y_LENGTH',3.5)
       		CALL PSETR('LEGEND_ENTRY_MAXIMUM_WIDTH',4.0)
       		CALL PSETR('LEGEND_ENTRY_MINIMUM_HEIGHT',0.1)

 			call psetc('LEGEND_USER_TEXT_1','tubes')
	   		call psetc('LEGEND_USER_TEXT_2','eps_std')
	   		call psetc('LEGEND_USER_TEXT_3','control error')
       		call psetc('LEGEND_USER_TEXT_4','calib. std')
	  	    call psetc('LEGEND_USER_TEXT_5','tubing rad.')
	  	  
	  	   call PTEXT
C--------------- Axis ----------------------------------
C-------- PLOT HORIZONTAL AXIS ------------------------
 
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_ORIENTATION','HORIZONTAL')
            CALL PSETC('AXIS_POSITION','BOTTOM')
            CALL PSETC('AXIS_TYPE','DATE')
            CALL PSETC('AXIS_DATE_TYPE','DAYS')
            CALL PSETC('AXIS_DATE_MIN_VALUE',FDATEI)
            CALL PSETC('AXIS_DATE_MAX_VALUE',FDATEF)
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETC('AXIS_TITLE','OFF')
            CALL PSETR('AXIS_TICK_INTERVAL',1.0)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_DAYS_LABEL','NUMBER')
            CALL PSETC('AXIS_DAYS_LABEL_COLOUR','BLACK')
            CALL PSETC('AXIS_LINE','ON')
            CALL PSETI('AXIS_LINE_THICKNESS',4)
            CALL PAXIS


C-------- PLOT VERTICAL AXIS ----------------------------
            
C##### Bar vertical axis 

            CALL PSETC('AXIS_ORIENTATION','VERTICAL')
            CALL PSETC('AXIS_TYPE','REGULAR')
            CALL PSETC('AXIS_POSITION','RIGHT')
            CALL PSETR('AXIS_MIN_VALUE',0.0)
            CALL PSETR('AXIS_MAX_VALUE',12.0)
            CALL PSETC('AXIS_TICK_POSITIONING','REGULAR')
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETR('AXIS_TICK_INTERVAL',1.0)
            CALL PSETC('AXIS_TICK_LABEL_TYPE','NUMBER')
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_TICK_LABEL_FORMAT','(I2)')
            CALL PSETI('AXIS_TICK_LABEL_FREQUENCY',2)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_MINOR_TICK','OFF')
            CALL PSETI('AXIS_MINOR_TICK_COUNT',1)

			
            CALL PSETC('AXIS_LINE','ON')
            CALL PSETI('AXIS_LINE_THICKNESS',4)
            CALL PSETI('AXIS_TICK_THICKNESS',4)
            CALL PSETC('AXIS_TITLE','ON')
            CALL PSETC('AXIS_TITLE_ORIENTATION','PARALLEL')
            CALL PSETC('AXIS_TITLE_QUALITY','HIGH')
            CALL PSETC('AXIS_TITLE_TEXT','n. of tubes')
C---- GRIDDING LINES

            CALL PSETC('AXIS_GRID','ON')
            CALL PSETC('AXIS_GRID_COLOUR','BLACK')
            CALL PSETI('AXIS_GRID_THICKNESS',2)
            CALL PSETC('AXIS_GRID_LINE_STYLE','DOT')
 
      		CALL PAXIS
	  	     
 	       CALL PSETC('GRAPH_TYPE','BAR')         
 	       CALL PSETC('GRAPH_SHADE_COLOUR','GRAY')
   	       CALL PSET1C('GRAPH_BAR_DATE_X_VALUES',XD,ND)
C    	   CALL PSET1R('GRAPH_BAR_Y_LOWER_VALUES', RLOW,ND)
    	   CALL PSET1R('GRAPH_BAR_Y_UPPER_VALUES', TUBES,ND)

      	   CALL PGRAPH

ccc# Curve
		    CALL PSETC('AXIS_ORIENTATION','VERTICAL')
            CALL PSETC('AXIS_POSITION','LEFT')
            CALL PSETR('AXIS_MIN_VALUE',0.0)
            CALL PSETR('AXIS_MAX_VALUE',180.0)
            CALL PSETC('AXIS_TICK_POSITIONING','REGULAR')
            CALL PSETC('AXIS_TICK','ON')
            CALL PSETR('AXIS_TICK_INTERVAL',10.0)
            CALL PSETC('AXIS_TICK_LABEL_TYPE','NUMBER')
            CALL PSETC('AXIS_TICK_LABEL_POSITION','ON_TICK')
            CALL PSETC('AXIS_TICK_LABEL_FORMAT','(AUTOMATIC)')
            CALL PSETI('AXIS_TICK_LABEL_FREQUENCY',2)
            CALL PSETC('AXIS_TICK_LABEL_QUALITY','HIGH')
            CALL PSETC('AXIS_MINOR_TICK','OFF')
            CALL PSETC('AXIS_TITLE','ON')
            CALL PSETC('AXIS_TITLE_TEXT','metres')

C---- GRIDDING LINES

            CALL PSETC('AXIS_GRID','OFF')
            CALL PSETC('AXIS_GRID_COLOUR','BLACK')
            CALL PSETI('AXIS_GRID_THICKNESS',3)
            CALL PSETC('AXIS_GRID_LINE_STYLE','DOT')
			CALL PAXIS
			
			       	          	         	   
			CALL PSETI('GRAPH_LINE_THICKNESS',4)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','BLUE')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',STDT,ND)

			CALL PGRAPH

			CALL PSETI('GRAPH_LINE_THICKNESS',4)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','BROWN')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSETC('GRAPH_MISSING_DATA_MODE','IGNORE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',TCERR,ND)
			
			CALL PGRAPH
			
			CALL PSETI('GRAPH_LINE_THICKNESS',2)
			CALL PSETC('GRAPH_LINE_STYLE','SOLID')
			CALL PSETC('GRAPH_LINE_COLOUR','RED')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',TSEAS,ND)


			CALL PGRAPH

			CALL PSETI('GRAPH_LINE_THICKNESS',2)
			CALL PSETC('GRAPH_LINE_STYLE','DASH')
			CALL PSETC('GRAPH_LINE_COLOUR','MAGENTA')
			CALL PSETC('GRAPH_TYPE','CURVE')
			CALL PSET1C('GRAPH_CURVE_DATE_X_VALUES',XD,ND)
			CALL PSET1R('GRAPH_CURVE_Y_VALUES',TRAD,ND)

			CALL PGRAPH
						
C*** CLOSE MAGICS

       CALL PCLOSE

       END



#include "parse_command_line.h"

