      PROGRAM PLOT_WIND
C

      DIMENSION RCONLIS (12)
      DATA RCONLIS /0.0, 2.0,4.0,8.0,10.0,12.0,14.0,16.0,18.0,20.0,
     x             22.0,24.0/

      CHARACTER*25 CLIST
      DIMENSION CLIST (12)
      DATA CLIST /'BLUE','GREENISH_BLUE','SKY','TURQUOISE',
     x            'GREENISH_YELLOW','YELLOW',
     x            'ORANGE_YELLOW','YELLOWISH_ORANGE','ORANGE',
     x            'REDDISH_ORANGE','RED','PURPLE_RED'/

      CALL POPEN
      CALL PARSE_COMMAND_LINE ('wind_venice')

      CALL PSETC ('PAGE_ID_LINE_USER_TEXT', 'Wind speed')


C
C     SELECT THE PROJECTION AND AREA AND PASS DATA TO MAGICS
C


      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION', 'CORNERS')
      CALL PSETC ('SUBPAGE_MAP_HEMISPHERE', 'NORTH')
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',16.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE', 27.5)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE', -2.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE', 42.5)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE', 40.0)

      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME', 'data/venice_wind_speed.grib')
      CALL PGRIB

C
C     SET GENERAL MAGICS PARAMETERS
C

      CALL PSETC ('CONTOUR_HILO', 'OFF')
      CALL PSETC ('CONTOUR_SHADE', 'ON')

      CALL PSETC ('LEGEND', 'ON')
      CALL PSETC ('LEGEND_DISPLAY_TYPE','CONTINUOUS')


      CALL PSETC ('CONTOUR_HIGHLIGHT', 'OFF')
      CALL PSETC ('CONTOUR_LINE_COLOUR', 'BLACK')
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'LEVEL_LIST')
      CALL PSET1R ('CONTOUR_LEVEL_LIST', RCONLIS, 12)


      CALL PSETC ('CONTOUR_SHADE_COLOUR_METHOD', 'LIST')
      CALL PSET1C('CONTOUR_SHADE_COLOUR_LIST',CLIST,12)

      CALL PSETC ('MAP_GRID', 'ON')
      CALL PSETC ('MAP_GRID_COLOUR', 'WHITE')
      CALL PSETC ('MAP_GRID_LINE_STYLE', 'DASH')
      CALL PSETR ('MAP_GRID_LATITUDE_INCREMENT', 4.0)
      CALL PSETR ('MAP_GRID_LONGITUDE_INCREMENT', 4.0)
      CALL PSETC ('MAP_LABEL', 'ON')
      CALL PSETC ('MAP_COASTLINE_RESOLUTION', 'HIGH')
      CALL PSETC ('MAP_COASTLINE_STYLE', 'SOLID')
      CALL PSETC ('MAP_COASTLINE_COLOUR', 'WHITE')
      CALL PSETC ('MAP_COASTLINE_LAND_SHADE', 'ON')
      CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR', 'GREY')

      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 1.25)


      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'POLYGON_SHADING')  
      CALL PSETC ('CONTOUR_SHADE_METHOD', 'AREA_FILL')  

      CALL PCONT

      CALL PSETC ('GRIB_INPUT_FILE_NAME', 'data/venice_wind.grib')
      CALL PSETI ('GRIB_WIND_POSITION_1',1)                
      CALL PSETI ('GRIB_WIND_POSITION_2',2)

      CALL PGRIB

      CALL PSETC ('WIND_ARROW_LEGEND', 'OFF')

      CALL PWIND


C
C     PLOT THE COASTLINES
C

      CALL PCOAST

C
C     PLOT TITLE TEXT
C

      CALL PSETC ('TEXT_LINE_1','Vento a 10 metri (m/s)')
c     CALL PSETC ('TEXT_QUALITY','low')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
      CALL PSETC ('TEXT_COLOUR','black')

      CALL PTEXT

      CALL PCLOSE

      STOP

      END


#include "parse_command_line.h"

