
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileAutomaticContourMethodAttributes.h
    \brief Definition of AutomaticContourMethod Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef AutomaticContourMethodWrapper_H
#define AutomaticContourMethodWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "AutomaticContourMethod.h"



#include "ContourMethodWrapper.h"








namespace magics {

class MagRequest;


class AutomaticContourMethodWrapper: public ContourMethodWrapper

{
public:
//  --  constructor
    AutomaticContourMethodWrapper();
    AutomaticContourMethodWrapper(AutomaticContourMethod*);
//  --  destructor
    virtual ~AutomaticContourMethodWrapper();
    virtual void set(const MagRequest&);

    AutomaticContourMethod* me()   { return automaticcontourmethod_; }

   	virtual AutomaticContourMethod* object() { return automaticcontourmethod_; }


	virtual void object(AutomaticContourMethod* o) {
		// Remember to delete the previous object
		automaticcontourmethod_ = o;
		ContourMethodWrapper::object(o);
		

	}



protected:
    AutomaticContourMethod* automaticcontourmethod_;


//  --  method
	virtual void print(ostream&) const override;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const AutomaticContourMethodWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif