
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileDotPolyShadingMethodAttributes.h
    \brief Definition of DotPolyShadingMethod Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef DotPolyShadingMethodWrapper_H
#define DotPolyShadingMethodWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "DotPolyShadingMethod.h"



#include "PolyShadingMethodWrapper.h"








namespace magics {

class MagRequest;


class DotPolyShadingMethodWrapper: public PolyShadingMethodWrapper

{
public:
//  --  constructor
    DotPolyShadingMethodWrapper();
    DotPolyShadingMethodWrapper(DotPolyShadingMethod*);
//  --  destructor
    virtual ~DotPolyShadingMethodWrapper();
    virtual void set(const MagRequest&);

    DotPolyShadingMethod* me()   { return dotpolyshadingmethod_; }

   	virtual DotPolyShadingMethod* object() { return dotpolyshadingmethod_; }


	virtual void object(DotPolyShadingMethod* o) {
		// Remember to delete the previous object
		dotpolyshadingmethod_ = o;
		PolyShadingMethodWrapper::object(o);
		

	}



protected:
    DotPolyShadingMethod* dotpolyshadingmethod_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const DotPolyShadingMethodWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif