
/******************************  LICENSE  *******************************

 * (C) Copyright 1996-2017 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \\file DumpShadingAttributes.h
    \\brief Definition of DumpShading Attributes class.

    This file is automatically generated.
    Do Not Edit!

*/

#include "MagRequest.h"
#include "DumpShadingWrapper.h"
#include "MagicsParameter.h"
#include "Factory.h"
#include "MagTranslator.h"
#include "MagicsGlobal.h"

using namespace magics;


DumpShadingWrapper::DumpShadingWrapper(): dumpshading_(new DumpShading())

{


	
	ShadingTechniqueWrapper::object(dumpshading_);
	

}
DumpShadingWrapper::DumpShadingWrapper(DumpShading* dumpshading): dumpshading_(dumpshading)
{

	
	ShadingTechniqueWrapper::object(dumpshading_);
	
}

DumpShadingWrapper::~DumpShadingWrapper()
{

}

void DumpShadingWrapper::set(const MagRequest& request)
{

	

	ShadingTechniqueWrapper::set(request);
	

	
	
}

void DumpShadingWrapper::print(ostream& out)  const
{
	out << "DumpShadingWrapper[]";
}


