
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileEpsPlumeAttributes.h
    \brief Definition of EpsPlume Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/
   

#ifndef EpsPlumeWrapper_H
#define EpsPlumeWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "EpsPlume.h"








 

namespace magics {

class MagRequest;


 	
class EpsPlumeWrapper 

{
public:
//  --  constructor
    EpsPlumeWrapper();
    EpsPlumeWrapper(EpsPlume*);
//  --  destructor
    virtual ~EpsPlumeWrapper();
    virtual void set(const MagRequest&);
    
    EpsPlume* me()   { return epsplume_; }
   	
   	virtual EpsPlume* object() { return epsplume_; }
	

	virtual void object(EpsPlume* o) { 
		// Remember to delete the previous object
		epsplume_ = o;
		

	}
    
  

protected:
    EpsPlume* epsplume_;


//  --  method
	virtual void print(ostream&) const;
	

private:
    string tag_;
	friend ostream& operator<<(ostream& s,const EpsPlumeWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif


