
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileEpsShadeAttributes.h
    \brief Definition of EpsShade Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef EpsShadeWrapper_H
#define EpsShadeWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "EpsShade.h"










namespace magics {

class MagRequest;



class EpsShadeWrapper

{
public:
//  --  constructor
    EpsShadeWrapper();
    EpsShadeWrapper(EpsShade*);
//  --  destructor
    virtual ~EpsShadeWrapper();
    virtual void set(const MagRequest&);

    EpsShade* me()   { return epsshade_; }

   	virtual EpsShade* object() { return epsshade_; }


	virtual void object(EpsShade* o) {
		// Remember to delete the previous object
		epsshade_ = o;
		

	}



protected:
    EpsShade* epsshade_;


//  --  method
	virtual void print(ostream&) const override;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const EpsShadeWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif