
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileGeoPointsDecoderAttributes.h
    \brief Definition of GeoPointsDecoder Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/
   

#ifndef GeoPointsDecoderAttributes_H
#define GeoPointsDecoderAttributes_H

#include "magics.h"
namespace magics {

class XmlNode;
class GeoPointsDecoderAttributes 
{
public:
//  --  constructor
    GeoPointsDecoderAttributes();
    
//  --  destructor
    virtual ~GeoPointsDecoderAttributes();
    
    virtual void set(const std::map<std::string, std::string>&);
    virtual void set(const XmlNode&);
    virtual void copy(const GeoPointsDecoderAttributes&);
    virtual bool accept(const std::string&);

    void setTag(const std::string& tag) { tag_ = tag; }

public:
	//  --  method
	virtual void print(std::ostream&) const;
	virtual void toxml(std::ostream& out) const;
	//  --  members:
	string tag_;
	string path_;
	double missing_;
	 

private:
	friend ostream& operator<<(ostream& s,const GeoPointsDecoderAttributes& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif

