
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileGraphAttributes.h
    \brief Definition of Graph Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef GraphWrapper_H
#define GraphWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "Graph.h"










namespace magics {

class MagRequest;



class GraphWrapper

{
public:
//  --  constructor
    GraphWrapper();
    GraphWrapper(Graph*);
//  --  destructor
    virtual ~GraphWrapper();
    virtual void set(const MagRequest&);

    Graph* me()   { return graph_; }

   	virtual Graph* object() { return graph_; }


	virtual void object(Graph* o) {
		// Remember to delete the previous object
		graph_ = o;
		

	}



protected:
    Graph* graph_;


//  --  method
	virtual void print(ostream&) const override;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const GraphWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif