
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileHatchPolyShadingMethodAttributes.h
    \brief Definition of HatchPolyShadingMethod Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef HatchPolyShadingMethodWrapper_H
#define HatchPolyShadingMethodWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "HatchPolyShadingMethod.h"



#include "PolyShadingMethodWrapper.h"








namespace magics {

class MagRequest;


class HatchPolyShadingMethodWrapper: public PolyShadingMethodWrapper

{
public:
//  --  constructor
    HatchPolyShadingMethodWrapper();
    HatchPolyShadingMethodWrapper(HatchPolyShadingMethod*);
//  --  destructor
    virtual ~HatchPolyShadingMethodWrapper();
    virtual void set(const MagRequest&);

    HatchPolyShadingMethod* me()   { return hatchpolyshadingmethod_; }

   	virtual HatchPolyShadingMethod* object() { return hatchpolyshadingmethod_; }


	virtual void object(HatchPolyShadingMethod* o) {
		// Remember to delete the previous object
		hatchpolyshadingmethod_ = o;
		PolyShadingMethodWrapper::object(o);
		

	}



protected:
    HatchPolyShadingMethod* hatchpolyshadingmethod_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const HatchPolyShadingMethodWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif