
/******************************  LICENSE  *******************************

 * (C) Copyright 1996-2017 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \\file HiLoBothAttributes.h
    \\brief Definition of HiLoBoth Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 2020-09-24
*/

#include "MagRequest.h" 
#include "HiLoBothWrapper.h"
#include "MagicsParameter.h"
#include "Factory.h"
#include "MagTranslator.h"

using namespace magics;


HiLoBothWrapper::HiLoBothWrapper(): hiloboth_(new HiLoBoth())

{

	
	
	HiLoTechniqueWrapper::object(hiloboth_);
	
	
} 
HiLoBothWrapper::HiLoBothWrapper(HiLoBoth* hiloboth): hiloboth_(hiloboth)
{
	
	
	HiLoTechniqueWrapper::object(hiloboth_);
	
} 

HiLoBothWrapper::~HiLoBothWrapper()
{
	
}

void HiLoBothWrapper::set(const MagRequest& request)
{
	
	
	
	HiLoTechniqueWrapper::set(request);
	

	
	
}

void HiLoBothWrapper::print(ostream& out)  const
{
	out << "HiLoBothWrapper[]";
}


    



