
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileHiLoTextAttributes.h
    \brief Definition of HiLoText Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef HiLoTextWrapper_H
#define HiLoTextWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "HiLoText.h"



#include "HiLoTechniqueWrapper.h"








namespace magics {

class MagRequest;


class HiLoTextWrapper: public HiLoTechniqueWrapper

{
public:
//  --  constructor
    HiLoTextWrapper();
    HiLoTextWrapper(HiLoText*);
//  --  destructor
    virtual ~HiLoTextWrapper();
    virtual void set(const MagRequest&);

    HiLoText* me()   { return hilotext_; }

   	virtual HiLoText* object() { return hilotext_; }


	virtual void object(HiLoText* o) {
		// Remember to delete the previous object
		hilotext_ = o;
		HiLoTechniqueWrapper::object(o);
		

	}



protected:
    HiLoText* hilotext_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const HiLoTextWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif