
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileInputDataAttributes.h
    \brief Definition of InputData Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef InputDataWrapper_H
#define InputDataWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "InputData.h"








#include "BinningObjectWrapper.h"


namespace magics {

class MagRequest;



class InputDataWrapper

{
public:
//  --  constructor
    InputDataWrapper();
    InputDataWrapper(InputData*);
//  --  destructor
    virtual ~InputDataWrapper();
    virtual void set(const MagRequest&);

    InputData* me()   { return inputdata_; }

   	virtual InputData* object() { return inputdata_; }


	virtual void object(InputData* o) {
		// Remember to delete the previous object
		inputdata_ = o;
		

	}



protected:
    InputData* inputdata_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const InputDataWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif