
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileMetgramBarAttributes.h
    \brief Definition of MetgramBar Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef MetgramBarWrapper_H
#define MetgramBarWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "MetgramBar.h"










namespace magics {

class MagRequest;



class MetgramBarWrapper

{
public:
//  --  constructor
    MetgramBarWrapper();
    MetgramBarWrapper(MetgramBar*);
//  --  destructor
    virtual ~MetgramBarWrapper();
    virtual void set(const MagRequest&);

    MetgramBar* me()   { return metgrambar_; }

   	virtual MetgramBar* object() { return metgrambar_; }


	virtual void object(MetgramBar* o) {
		// Remember to delete the previous object
		metgrambar_ = o;
		

	}



protected:
    MetgramBar* metgrambar_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const MetgramBarWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif