
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileNoBoxPlotWhiskerAttributes.h
    \brief Definition of NoBoxPlotWhisker Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef NoBoxPlotWhiskerWrapper_H
#define NoBoxPlotWhiskerWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "BoxPlotItem.h"










namespace magics {

class MagRequest;



class NoBoxPlotWhiskerWrapper

{
public:
//  --  constructor
    NoBoxPlotWhiskerWrapper();
    NoBoxPlotWhiskerWrapper(NoBoxPlotWhisker*);
//  --  destructor
    virtual ~NoBoxPlotWhiskerWrapper();
    virtual void set(const MagRequest&);

    NoBoxPlotWhisker* me()   { return noboxplotwhisker_; }

   	virtual NoBoxPlotWhisker* object() { return noboxplotwhisker_; }


	virtual void object(NoBoxPlotWhisker* o) {
		// Remember to delete the previous object
		noboxplotwhisker_ = o;
		

	}



protected:
    NoBoxPlotWhisker* noboxplotwhisker_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const NoBoxPlotWhiskerWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif