
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileNoBoxPlotBoxAttributes.h
    \brief Definition of NoBoxPlotBox Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef NoBoxPlotBoxWrapper_H
#define NoBoxPlotBoxWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "BoxPlotItem.h"










namespace magics {

class MagRequest;



class NoBoxPlotBoxWrapper

{
public:
//  --  constructor
    NoBoxPlotBoxWrapper();
    NoBoxPlotBoxWrapper(NoBoxPlotBox*);
//  --  destructor
    virtual ~NoBoxPlotBoxWrapper();
    virtual void set(const MagRequest&);

    NoBoxPlotBox* me()   { return noboxplotbox_; }

   	virtual NoBoxPlotBox* object() { return noboxplotbox_; }


	virtual void object(NoBoxPlotBox* o) {
		// Remember to delete the previous object
		noboxplotbox_ = o;
		

	}



protected:
    NoBoxPlotBox* noboxplotbox_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const NoBoxPlotBoxWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif