
/******************************  LICENSE  *******************************

 * (C) Copyright 1996-2017 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \\file NoGraphShadeAttributes.h
    \\brief Definition of NoGraphShade Attributes class.

    This file is automatically generated.
    Do Not Edit!
*/

#include "MagRequest.h" 
#include "NoGraphShadeWrapper.h"
#include "MagicsParameter.h"
#include "Factory.h"
#include "MagTranslator.h"

using namespace magics;


NoGraphShadeWrapper::NoGraphShadeWrapper(): nographshade_(new NoGraphShade())

{

	
	
	GraphShadeWrapper::object(nographshade_);
	
	
} 
NoGraphShadeWrapper::NoGraphShadeWrapper(NoGraphShade* nographshade): nographshade_(nographshade)
{
	
	
	GraphShadeWrapper::object(nographshade_);
	
} 

NoGraphShadeWrapper::~NoGraphShadeWrapper()
{
	
}

void NoGraphShadeWrapper::set(const MagRequest& request)
{
	
	
	
	GraphShadeWrapper::set(request);
	

	
	
}

void NoGraphShadeWrapper::print(ostream& out)  const
{
	out << "NoGraphShadeWrapper[]";
}


    



