
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileNoGraphShadeAttributes.h
    \brief Definition of NoGraphShade Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/
   

#ifndef NoGraphShadeWrapper_H
#define NoGraphShadeWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "GraphShade.h"


 
#include "GraphShadeWrapper.h"






 

namespace magics {

class MagRequest;


class NoGraphShadeWrapper: public GraphShadeWrapper

{
public:
//  --  constructor
    NoGraphShadeWrapper();
    NoGraphShadeWrapper(NoGraphShade*);
//  --  destructor
    virtual ~NoGraphShadeWrapper();
    virtual void set(const MagRequest&);
    
    NoGraphShade* me()   { return nographshade_; }
   	
   	virtual NoGraphShade* object() { return nographshade_; }
	

	virtual void object(NoGraphShade* o) { 
		// Remember to delete the previous object
		nographshade_ = o;
		GraphShadeWrapper::object(o);
		

	}
    
  

protected:
    NoGraphShade* nographshade_;


//  --  method
	virtual void print(ostream&) const;
	

private:
    string tag_;
	friend ostream& operator<<(ostream& s,const NoGraphShadeWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif


