
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileNoLabelPlottingAttributes.h
    \brief Definition of NoLabelPlotting Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef NoLabelPlottingWrapper_H
#define NoLabelPlottingWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "LabelPlotting.h"










namespace magics {

class MagRequest;



class NoLabelPlottingWrapper

{
public:
//  --  constructor
    NoLabelPlottingWrapper();
    NoLabelPlottingWrapper(NoLabelPlotting*);
//  --  destructor
    virtual ~NoLabelPlottingWrapper();
    virtual void set(const MagRequest&);

    NoLabelPlotting* me()   { return nolabelplotting_; }

   	virtual NoLabelPlotting* object() { return nolabelplotting_; }


	virtual void object(NoLabelPlotting* o) {
		// Remember to delete the previous object
		nolabelplotting_ = o;
		

	}



protected:
    NoLabelPlotting* nolabelplotting_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const NoLabelPlottingWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif