
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileNoLogoPlottingAttributes.h
    \brief Definition of NoLogoPlotting Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef NoLogoPlottingWrapper_H
#define NoLogoPlottingWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "LogoPlotting.h"










namespace magics {

class MagRequest;



class NoLogoPlottingWrapper

{
public:
//  --  constructor
    NoLogoPlottingWrapper();
    NoLogoPlottingWrapper(NoLogoPlotting*);
//  --  destructor
    virtual ~NoLogoPlottingWrapper();
    virtual void set(const MagRequest&);

    NoLogoPlotting* me()   { return nologoplotting_; }

   	virtual NoLogoPlotting* object() { return nologoplotting_; }


	virtual void object(NoLogoPlotting* o) {
		// Remember to delete the previous object
		nologoplotting_ = o;
		

	}



protected:
    NoLogoPlotting* nologoplotting_;


//  --  method
	virtual void print(ostream&) const override;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const NoLogoPlottingWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif