
/******************************  LICENSE  *******************************

 * (C) Copyright 1996-2017 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \\file NoOriginMarkerAttributes.h
    \\brief Definition of NoOriginMarker Attributes class.

    This file is automatically generated.
    Do Not Edit!
*/

#include "MagRequest.h" 
#include "NoOriginMarkerWrapper.h"
#include "MagicsParameter.h"
#include "Factory.h"
#include "MagTranslator.h"

using namespace magics;


NoOriginMarkerWrapper::NoOriginMarkerWrapper(): nooriginmarker_(new NoOriginMarker())

{

	
	
	OriginMarkerWrapper::object(nooriginmarker_);
	
	
} 
NoOriginMarkerWrapper::NoOriginMarkerWrapper(NoOriginMarker* nooriginmarker): nooriginmarker_(nooriginmarker)
{
	
	
	OriginMarkerWrapper::object(nooriginmarker_);
	
} 

NoOriginMarkerWrapper::~NoOriginMarkerWrapper()
{
	
}

void NoOriginMarkerWrapper::set(const MagRequest& request)
{
	
	
	
	OriginMarkerWrapper::set(request);
	

	
	
}

void NoOriginMarkerWrapper::print(ostream& out)  const
{
	out << "NoOriginMarkerWrapper[]";
}


    



