
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileObsPlottingAttributes.h
    \brief Definition of ObsPlotting Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef ObsPlottingWrapper_H
#define ObsPlottingWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "ObsPlotting.h"










namespace magics {

class MagRequest;



class ObsPlottingWrapper

{
public:
//  --  constructor
    ObsPlottingWrapper();
    ObsPlottingWrapper(ObsPlotting*);
//  --  destructor
    virtual ~ObsPlottingWrapper();
    virtual void set(const MagRequest&);

    ObsPlotting* me()   { return obsplotting_; }

   	virtual ObsPlotting* object() { return obsplotting_; }


	virtual void object(ObsPlotting* o) {
		// Remember to delete the previous object
		obsplotting_ = o;
		

	}



protected:
    ObsPlotting* obsplotting_;


//  --  method
	virtual void print(ostream&) const override;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const ObsPlottingWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif