
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \filePaletteColourTechniqueAttributes.h
    \brief Definition of PaletteColourTechnique Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef PaletteColourTechniqueWrapper_H
#define PaletteColourTechniqueWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "ColourTechnique.h"



#include "ColourTechniqueWrapper.h"








namespace magics {

class MagRequest;


class PaletteColourTechniqueWrapper: public ColourTechniqueWrapper

{
public:
//  --  constructor
    PaletteColourTechniqueWrapper();
    PaletteColourTechniqueWrapper(PaletteColourTechnique*);
//  --  destructor
    virtual ~PaletteColourTechniqueWrapper();
    virtual void set(const MagRequest&);

    PaletteColourTechnique* me()   { return palettecolourtechnique_; }

   	virtual PaletteColourTechnique* object() { return palettecolourtechnique_; }


	virtual void object(PaletteColourTechnique* o) {
		// Remember to delete the previous object
		palettecolourtechnique_ = o;
		ColourTechniqueWrapper::object(o);
		

	}



protected:
    PaletteColourTechnique* palettecolourtechnique_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const PaletteColourTechniqueWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif