
/******************************  LICENSE  *******************************

 * (C) Copyright 1996-2017 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \\file Proj4EPSG8857Attributes.h
    \\brief Definition of Proj4EPSG8857 Attributes class.

    This file is automatically generated.
    Do Not Edit!

*/

#include "MagRequest.h"
#include "Proj4EPSG8857Wrapper.h"
#include "MagicsParameter.h"
#include "Factory.h"
#include "MagTranslator.h"
#include "MagicsGlobal.h"

using namespace magics;



Proj4EPSG8857Wrapper::Proj4EPSG8857Wrapper(): proj4epsg8857_(new Proj4EPSG8857())


{


	
	Proj4ProjectionWrapper::object(proj4epsg8857_);
	

}
Proj4EPSG8857Wrapper::Proj4EPSG8857Wrapper(Proj4EPSG8857* proj4epsg8857): proj4epsg8857_(proj4epsg8857)
{

	
	Proj4ProjectionWrapper::object(proj4epsg8857_);
	
}

Proj4EPSG8857Wrapper::~Proj4EPSG8857Wrapper()
{

}

void Proj4EPSG8857Wrapper::set(const MagRequest& request)
{

	

	Proj4ProjectionWrapper::set(request);
	

	
	
}

void Proj4EPSG8857Wrapper::print(ostream& out)  const
{
	out << "Proj4EPSG8857Wrapper[]";
}


