
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileTextVisitorAttributes.h
    \brief Definition of TextVisitor Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/
   

#ifndef TextVisitorWrapper_H
#define TextVisitorWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "TextVisitor.h"








 

namespace magics {

class MagRequest;


 	
class TextVisitorWrapper 

{
public:
//  --  constructor
    TextVisitorWrapper();
    TextVisitorWrapper(TextVisitor*);
//  --  destructor
    virtual ~TextVisitorWrapper();
    virtual void set(const MagRequest&);
    
    TextVisitor* me()   { return textvisitor_; }
   	
   	virtual TextVisitor* object() { return textvisitor_; }
	

	virtual void object(TextVisitor* o) { 
		// Remember to delete the previous object
		textvisitor_ = o;
		

	}
    
  

protected:
    TextVisitor* textvisitor_;


//  --  method
	virtual void print(ostream&) const;
	

private:
    string tag_;
	friend ostream& operator<<(ostream& s,const TextVisitorWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif


