
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 * 
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
 * In applying this licence, ECMWF does not waive the privileges and immunities 
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileWrepRootNodeAttributes.h
    \brief Definition of WrepRootNode Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/
   

#ifndef WrepRootNodeWrapper_H
#define WrepRootNodeWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "WrepRootNode.h"








 

namespace magics {

class MagRequest;


 	
class WrepRootNodeWrapper 

{
public:
//  --  constructor
    WrepRootNodeWrapper();
    WrepRootNodeWrapper(WrepRootNode*);
//  --  destructor
    virtual ~WrepRootNodeWrapper();
    virtual void set(const MagRequest&);
    
    WrepRootNode* me()   { return wreprootnode_; }
   	
   	virtual WrepRootNode* object() { return wreprootnode_; }
	

	virtual void object(WrepRootNode* o) { 
		// Remember to delete the previous object
		wreprootnode_ = o;
		

	}
    
  

protected:
    WrepRootNode* wreprootnode_;


//  --  method
	virtual void print(ostream&) const;
	

private:
    string tag_;
	friend ostream& operator<<(ostream& s,const WrepRootNodeWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif


