
/*******************************  LICENSE  *******************************

 * (C) Copyright 1996-2016 ECMWF.
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 * In applying this licence, ECMWF does not waive the privileges and immunities
 * granted to it by virtue of its status as an intergovernmental organisation nor
 * does it submit to any jurisdiction.

 *******************************  LICENSE  *******************************/

/*! \fileXHyperCoordinateAttributes.h
    \brief Definition of XHyperCoordinate Attributes class.

    This file is automatically generated.
    Do Not Edit!

    Generated: 
*/


#ifndef XHyperCoordinateWrapper_H
#define XHyperCoordinateWrapper_H

#include "magics.h"
#include "ParameterManager.h"
#include "Factory.h"



#include "Coordinate.h"



#include "XCoordinateWrapper.h"








namespace magics {

class MagRequest;


class XHyperCoordinateWrapper: public XCoordinateWrapper

{
public:
//  --  constructor
    XHyperCoordinateWrapper();
    XHyperCoordinateWrapper(XHyperCoordinate*);
//  --  destructor
    virtual ~XHyperCoordinateWrapper();
    virtual void set(const MagRequest&);

    XHyperCoordinate* me()   { return xhypercoordinate_; }

   	virtual XHyperCoordinate* object() { return xhypercoordinate_; }


	virtual void object(XHyperCoordinate* o) {
		// Remember to delete the previous object
		xhypercoordinate_ = o;
		XCoordinateWrapper::object(o);
		

	}



protected:
    XHyperCoordinate* xhypercoordinate_;


//  --  method
	virtual void print(ostream&) const;


private:
    string tag_;
	friend ostream& operator<<(ostream& s,const XHyperCoordinateWrapper& p)
	{ p.print(s); return s; }
};

} // namespace magics

#endif