#!/bin/ksh

# set -x


ref_root="/tmp/$USER/magcompare"
new_root="/tmp/$USER/magcompare"


# -------------------------------------------------------------------------------

# test the command-line arguments

print_help=0

if [[ $# -ne 2 ]];then
   print_help=1
fi

for arg;do
    if [[ $arg = "-h" || $arg = "-help" || $arg = "--help" ]]
    then
        print_help=1
    fi
done


if [[ $print_help -eq 1 ]]
then
        echo ""
        echo "version_diff usage:"
        echo ""
        echo "version_diff  <ref_version>  <new_version>"
        echo "  e.g."
        echo "version_diff  suse9_++1.3.6_double_cylindrical  suse9_++2.1.0_double_cylindrical"
        echo ""
        echo "Note: it is assumed that the reference version is in directory"
        echo "   $ref_root"
        echo "and that the new version is in directory"
        echo "   $new_root"
        echo ""
        exit
fi


# -------------------------------------------------------------------------------


# version_dirs - space-separated list of versions to compare with the reference version

# new_root="../../links"
reference_version_dir=$1
new_version_dirs=$2
# ref_root="../../links"
# mdiff="/ccview/magics_cgs_linux/magics/demos/mdiff"
#mdiff="/var/tmp/cgi/PERFORCE/magics/docs/www/4_examples/progs/diff/src/mdiff"
mdiff="/home/graphics/cgi/bin/mdiff"
ps_source_dir="ps_source"
ps_diff_dir="../ps_diff"



for vdir in $new_version_dirs
do

    # create any directories that we need

    exp_dir="${reference_version_dir}_${vdir}"
    mkdir -p exps/$exp_dir
    cd       exps/$exp_dir
    mkdir -p ps_source
    mkdir -p ps_diff


    # remove the current report file so we don't just keep adding to it

    rm -f report


    # for each postscript file in the reference directory, create a difference file

    for psfile in $ref_root/$reference_version_dir/*.ps
    do
        psbase=`basename $psfile`
        echo [$psbase]
	    ps1="exp1_$psbase"
	    ps2="exp2_$psbase"
	    cp -u $ref_root/$reference_version_dir/$psbase  "$ps_source_dir/$ps1"
	    cp -u $new_root/$vdir/$psbase                   "$ps_source_dir/$ps2"
#       ps1="$ref_root/$reference_version_dir/$psbase"
#       ps2="$new_root/$vdir/$psbase"
        cd $ps_source_dir
        $mdiff -ps $ps1 $ps2 -o "$ps_diff_dir/$psbase.diff.ps" >> ../report
        cd ..
    done

done


# generate the HTML

cd ../..
mkdir -p html
diffpage.pl exps

