C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM WIND02
*
*     THIS PROGRAM DEMONSTRATES MAGICS WIND FIELD PLOTTING FACILITIES.
*
*     THE METEOROLOGICAL DATA FIELDS IN FILE 2 ARE 10 METRE U/V FIELDS
*     ON A GAUSSIAN (T511)GRID. WIND ARROWS AND COASTLINES ARE 
*     PROJECTED ONTO A POLAR STEREOGRAPHIC MAP.
*     DATA FOR WIND PLOTTING IS IN GRIB CODE IN THE FILE 10uv.grb.
*
*
*     OPEN MAGICS
*
      CALL POPEN
      CALL PSETC ('PS_DEVICE',    'ps_a4')
      CALL PSETC ('PS_FILE_NAME', 'wind02.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Wind02')
      CALL PSETR ('SUBPAGE_X_LENGTH',17.0)	 
      CALL PSETR ('SUBPAGE_Y_LENGTH',17.0)
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_SCALE',75.E6)
*
*     PASS THE DATA TO MAGICS
*
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x 'data/10uv.grb')
      CALL PSETI ('GRIB_WIND_POSITION_1',1)
      CALL PSETI ('GRIB_WIND_POSITION_2',2) 
      CALL PGRIB
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')
      CALL PSETC ('MAP_GRID_COLOUR','GREEN')
*
*     PLOT WIND_ARROWS ON NORTHERN HEMISPHERE POLAR STEREOGRAPHIC MAP
*
      CALL WIND02_ONE
      CALL PNEW ('PAGE')
*
*     WIND_ARROWS ON POLAR STEREO MAP + THINNING FACTOR = 3.0 AND
*     UNIT VELOCITY= 50.0 m/s AND CALM INDICATOR = ON
*
      CALL WIND02_TWO
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON POLAR STEREO MAP + CALM INDICATOR SIZE = 0.15
*     AND WIND_ARROW_CALM_BELOW = 2.0
*
      CALL WIND02_THREE
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA
*
      CALL WIND02_FOUR
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA
*     + THINNING FACTOR = 2, ARROW THICKNESS = 3, WIND LEGEND MOVED
*
      CALL WIND02_FIVE
*
*     CLOSE MAGICS
*
      CALL PCLOSE
*
      END
      SUBROUTINE WIND02_ONE
*
*     THIS SUBROUTINE PLOTS THE WIND_ARROWS AND COASTLINES ON A
*     NORTHEN HEMISPHERE POLAR STEREOGRAPHIC MAP.
*     DEFAULT VALUES FOR ALL WIND ARROW PARAMETERS
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Northern Hemisphere Polar Stereographic -'//
     1           '10 metre U/V on a Gaussian (T511) grid')
      CALL PSETC ('TEXT_LINE_2',
     1           'Default Values for Wind Arrow Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',2)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND02_TWO
*
*     THIS SUBROUTINE PLOTS THE WIND ARROWS FROM THE GAUSSIAN (T511)
*     FIELD ON A POLAR STEREOGRAPHIC PROJECTION. WIND ARROW UNIT
*     VELOCITY IS SET TO 50.0 AND THE THINNING FACTOR TO 3.0 TO
*     IMPROVE THE APPEARANCE OF THE WIND ARROWS. CALM WIND < 0.5 m/s
*     ARE PLOTTED WITH A MARKER CIRCLE.
*
*     ALL WIND PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE THEIR
*     DEFAULT VALUES.
*
      CALL PSETR ('WIND_ARROW_UNIT_VELOCITY',50.0)
      CALL PSETR ('WIND_THINNING_FACTOR',3.0)
      CALL PSETC ('WIND_ARROW_CALM_INDICATOR','ON')
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Northern Hemisphere Polar Stereographic -'//
     1           '10 metre U/V on a Gaussian (T511) grid')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Unit Velocity = 50 m/s, Thinning factor = 3.0, ' //
     2           'Calm Indicator = ON')
*
*     PLOT TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND02_THREE
*
*     THIS SUBROUTINE PLOTS THE WIND ARROWS FROM THE GAUSSIAN (T511)
*     FIELD ON A POLAR STEREOGRAPHIC PROJECTION. THE WIND ARROW UNIT
*     VELOCITY IS SET TO 50.0 AND THE THINNING FACTOR TO 3.0 TO IMPROVE
*     THE APPEARANCE OF THE WIND ARROWS. WINDS BELOW 2.0 m/s ARE
*     PLOTTED AS CALM AND WITH A MARKER CIRCLE TWICE AS BIG AS
*     THE DEFAULT (0.2).
*
      CALL PSETR ('WIND_ARROW_CALM_INDICATOR_SIZE',0.15)
      CALL PSETR ('WIND_ARROW_CALM_BELOW',2.0)
      CALL PSETC ('TEXT_LINE_1',
     1           'Northern Hemisphere Polar Stereographic -'//
     1           '10 metre U/V on a Gaussian (T511) grid')
*
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Unit Velocity = 50 m/s, Thinning factor = 3.0, ' //
     2           'Calm Indicator = ON')
      CALL PSETC ('TEXT_LINE_3',
     1  ' + Calm Indicator Size = 0.4, Wind Arrow Calm Below = 2.0')
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND02_FOUR
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     AREA + EVERY GRID POINT IS PLOTTED (THINNING FACTOR =1.)
*     UNIT VELOCITY IS SET TO 15 m/s AND CALM INDICATOR is OFF
*
      CALL PSETR ('SUBPAGE_X_LENGTH',26.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',10.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',10.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',10.E6)
*
      CALL PSETR ('WIND_ARROW_UNIT_VELOCITY',15.0)
      CALL PSETR ('WIND_THINNING_FACTOR',1.0)
      CALL PSETC ('WIND_ARROW_CALM_INDICATOR','OFF')
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Northern Hemisphere Polar Stereographic -'//
     1           '10 metre U/V on a Gaussian (T511) grid')
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Unit Velocity = 15 m/s, Thinning factor = 1.0, '//
     2           'Calm Indicator = OFF')

      CALL PSETI ('TEXT_LINE_COUNT',2)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND02_FIVE
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     THE WIND_ARROW_ORIGIN_POSITION IS SET TO CENTRE
*
      CALL PSETC ('WIND_ARROW_ORIGIN_POSITION','CENTRE')
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Northern Hemisphere Polar Stereographic -'//
     1           '10 metre U/V on a Gaussian (T511) grid')
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Unit Velocity = 15 m/s, Thinning factor = 1.0, '//
     2           'Calm Indicator = OFF')
      CALL PSETC ('TEXT_LINE_3',
     2           '+ Wind Arrow Origin Position = CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
      RETURN
      END
