C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM WIND01
*
*     THIS PROGRAM DEMONSTRATES MAGICS WIND FIELD PLOTTING FACILITIES.
*
*     THE METEOROLOGICAL DATA FIELDS IN FILE 2 ARE STANDARD GLOBAL
*     500 HPA MODEL OUTPUT FIELDS ON A REGULAR 1.5 DEGREE GRID.
*     WIND ARROWS AND COASTLINES ARE PROJECTED ONTO A CYLINDRICAL MAP.
*     THE WIND ARROWS ARE PLOTTED USING THE DEFAULT VALUES OF MAGICS
*     PARAMETERS FOR WIND PLOTTING. DATA FOR WIND PLOTTING IS IN GRIB
*     CODE IN THE FILE 500uv.grb.
*
*     OPEN MAGICS
*     -----------
      CALL POPEN
      CALL PSETC ('PS_DEVICE',    'ps_a4')
      CALL PSETC ('PS_FILE_NAME', 'wind01.ps')
c      CALL PSETC ('PS_SPLIT',     'ON')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Wind01')
*
*     PASS THE DATA TO MAGICS
*     -----------------------
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x  'data/500uv.grb')
      CALL PSETI ('GRIB_WIND_POSITION_1',1)                 
      CALL PSETI ('GRIB_WIND_POSITION_2',2) 
      CALL PGRIB
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')
      CALL PSETC ('MAP_GRID_COLOUR','GREEN')
*
*     PLOT WIND_ARROWS ON GLOBAL CYLINDRICAL MAP
*
      CALL WIND01_ONE
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON GLOBAL CYLINDRICAL MAP + SELECTED SPEED
*     RANGE, CROSS BOUNDARY = OFF
*
      CALL WIND01_TWO
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON GLOBAL CYLINDRICAL MAP + SELECTED SPEED
*     RANGE, CROSS BOUNDARY = OFF + ARROWHEAD INDEX = 12 
*     AND THINNING FACTOR=3
*
      CALL WIND01_THREE
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA
*     + THINNING FACTOR = 1
*
      CALL WIND01_FOUR
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA
*     + THINNING FACTOR = 2, ARROW THICKNESS = 3, WIND LEGEND MOVED
*
      CALL WIND01_FIVE
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA,
*     THINNING FACTOR = 2, ARROW THICKNESS = 3, WIND LEGEND MOVED
*     + UNIT VELOCITY = 40.0
*
      CALL WIND01_SIX
      CALL PNEW ('PAGE')
*
*     PLOT WIND_ARROWS ON SELECTED EUROPEAN AREA, ARROWHEAD INDEX = 1
*     THINNING FACTOR = 2, ARROW THICKNESS = 3, WIND LEGEND MOVED
*     + UNIT VELOCITY = 0.0
*
      CALL WIND01_SEVEN
*
*     CLOSE MAGICS
*
      CALL PCLOSE
*
      END
      SUBROUTINE WIND01_ONE
*
*     THIS SUBROUTINE PLOTS THE WIND_ARROWS AND COASTLINES ON A
*     CYLINDRICAL MAP.
*     DEFAULT VALUES FOR ALL WIND ARROW PARAMETERS
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1           'Default Values for Wind Arrow Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',2)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND01_TWO
*
*     THIS SUBROUTINE PLOTS THE WIND ARROWS FROM THE REGULAR INPUT
*     FIELD ON A CYLINDRICAL PROJECTION. THE WIND SPEEDS ARE CONFINED
*     TO A SELECTED RANGE BY USING THE PARAMETERS WIND_ARROW_MAX_SPEED
*     AND WIND_ARROW_MIN_SPEED.  WIND ARROWS ARE ALLOWED TO CROSS
*     BOUNDARIES
*
*     ALL WIND PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE THEIR
*     DEFAULT VALUES.
*
      CALL PSETR ('WIND_ARROW_MAX_SPEED',30.0)
      CALL PSETR ('WIND_ARROW_MIN_SPEED',10.0)
      CALL PSETC ('WIND_ARROW_CROSS_BOUNDARY','OFF')
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Wind Speed range is 10.0 to 30.0 m/s, ' //
     2           'Cross Boundary = OFF')
      CALL PSETI ('TEXT_LINE_COUNT',2)
*
*     PLOT TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND01_THREE
*
*     THIS SUBROUTINE PLOTS THE WIND ARROWS FROM THE REGULAR INPUT
*     FIELD ON A CYLINDRICAL PROJECTION. THE WIND SPEEDS ARE CONFINED
*     TO A SELECTED RANGE BY USING THE PARAMETERS WIND_ARROW_MAX_SPEED
*     AND WIND_ARROW_MIN_SPEED.  WIND ARROWS ARE ALLOWED TO CROSS   
*     BOUNDARIES
*
*     WIND THINNING FACTOR AND ARROWHEAD INDEX ARE CHANGED.
*
*
      CALL PSETR ('WIND_THINNING_FACTOR',3.0)
      CALL PSETI ('WIND_ARROW_HEAD_INDEX',12)      
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1 '+ Wind Speed range is 10.0 to 30.0 m/s, ' //
     2           'Cross Boundary = OFF')
      CALL PSETC ('TEXT_LINE_3',
     1  ' + Arrowhead Index = 12, Thinning Factor = 3.0')
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      CALL PRESET('WIND_ARROW_MAX_SPEED')
      CALL PRESET('WIND_ARROW_MIN_SPEED')
      CALL PRESET('WIND_ARROW_CROSS_BOUNDARY')
      RETURN
      END
      SUBROUTINE WIND01_FOUR
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     AREA + EVERY GRID POINT IS PLOTTED (THINNING FACTOR =1.)
*
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',30.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-20.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',72.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',42.0)
*
      CALL PSETR ('WIND_THINNING_FACTOR',1.0)
      CALL PSETI ('WIND_ARROW_HEAD_INDEX',22)
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1 'European Area: Thinning Factor = 1.0')
      CALL PSETI ('TEXT_LINE_COUNT',2)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND01_FIVE
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     AREA + WIND THICKNESS IS 3, WIND ARROW THINNING FACTOR IS 2.0,
*     THE WIND_ARROW LEGEND IS MOVED.
*
      CALL PSETI ('WIND_ARROW_THICKNESS',3)
      CALL PSETR ('WIND_THINNING_FACTOR',2.0)
      CALL PSETR ('WIND_ARROW_LEGEND_X_POSITION',1.0)
      CALL PSETR ('WIND_ARROW_LEGEND_Y_POSITION',19.0)
*
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1           'European Area: '//
     2           'Thinning Factor = 2.0')
      CALL PSETC ('TEXT_LINE_3',
     2           '+ Arrow Thickness = 3, Arrow Legend is moved')  
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
      RETURN
      END
      SUBROUTINE WIND01_SIX
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     AREA. WIND THICKNESS IS 3.  WIND ARROW THINNING FACTOR IS 2.0.
*     THE WIND_ARROW LEGEND IS MOVED.
*     + WIND ARROW UNIT VELOCITY = 40.0                          
*
*
      CALL PSETR ('WIND_ARROW_UNIT_VELOCITY',40.0)
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1           'European Area: '//
     2           'Thinning Factor = 2.0')
      CALL PSETC ('TEXT_LINE_3',
     2 'Arrow Thickness = 3, Arrow Legend is moved '//
     3  ' + Unit Velocity = 40.0')
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END
      SUBROUTINE WIND01_SEVEN
*
*     THIS SUBROUTINE PLOTS WIND_ARROWS IN A SELECTED AREA EUROPEAN
*     AREA. WIND THICKNESS = 3.  WIND ARROW THINNING FACTOR = 2.0.
*     THE WIND_ARROW LEGEND IS MOVED.
*     + WIND ARROW UNIT VELOCITY = 0.0                          
*
      CALL PSETR ('WIND_ARROW_UNIT_VELOCITY',0.0)
      CALL PSETC ('TEXT_LINE_1',
     1           'Global Cylindrical 500 U/V Wind Components '//
     1           'on a regular 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1           'European Area: '//
     2           'Thinning Factor = 2.0')
      CALL PSETC ('TEXT_LINE_3',
     2 'Arrow Thickness = 3, Arrow Legend is moved '//
     3  ' + Unit Velocity = 0.0')  
      CALL PSETI ('TEXT_LINE_COUNT',3)
*
*     PLOT THE TITLE, COASTLINES AND WIND_ARROWS
*
      CALL PTEXT
      CALL PCOAST
      CALL PWIND
*
      RETURN
      END

