#!/bin/bash
# $1 = top directory $2 = git directory $3 = build directory $4 = install directory $5 = ecbuild $6 = cpus
set -eaux

/usr/local/apps/cmake/current/bin/cmake $2 \
    -DCMAKE_MODULE_PATH=$5 \
    -DCMAKE_INSTALL_PREFIX=$4  \
    -DCMAKE_C_FLAGS=-DMAGICS_EXCEPTION \
    -DCMAKE_BUILD_TYPE=Debug
    
/usr/local/apps/cmake/current/bin/cmake $2 -LAH > build-info.txt

make -j $6 install
