#!/bin/bash
# $1 = top directory $2 = git directory $3 = build directory $4 = install directory $5 = ecbuild

/usr/local/apps/cmake/current/bin/cmake $2 \
    -DCMAKE_MODULE_PATH=$5 \
    -DCMAKE_PREFIX_PATH=$4 \
    -DCMAKE_INSTALL_PREFIX=$4
    
make install
