#!/bin/bash
# $1 = top directory $2 = git directory $3 = build directory $4 = install directory $5 = ecbuild $6 = cpus
set -eaux

/usr/local/apps/cmake/current/bin/cmake $2 \
    -DCMAKE_MODULE_PATH=$5 \
    -DCMAKE_INSTALL_PREFIX=$4 
    #-DCMAKE_PREFIX_PATH="$4;/usr/local/apps/python/2.7.1-02" 

    #-DBOOST_ROOT=/usr/local/apps/boost/1.50.0 \
    #-DPROJ4_PATH=/usr/local/apps/proj4/4.8.0/LP64 
    #-DNETCDF_PATH=/usr/local/apps/netcdf4/4.1.3/LP64 
    
/usr/local/apps/cmake/current/bin/cmake $2 -LAH > build-info.txt

make -j $6 install
