SET(ENABLE_CAIRO   ON  CACHE BOOL "Enable PNG")
SET(ENABLE_PYTHON  OFF CACHE BOOL "Disable Python")
SET(ENABLE_BUFR    ON  CACHE BOOL "Enable BUFR")
SET(ENABLE_METVIEW ON  CACHE BOOL "Enable Metview")
# SET(WITH_PGI_FORTRAN ON  CACHE BOOL "Enable pgi Fortran")
# SET(PGI_PATH /usr/local/apps/pgi/pgi-10.8/linux86-64/10.8/libso  CACHE STRING "PGI library path")
