SET(ENABLE_CAIRO   ON  CACHE BOOL "Enable PNG")
SET(ENABLE_PYTHON  OFF CACHE BOOL "Disable Python")
SET(ENABLE_BUFR    ON  CACHE BOOL "Enable BUFR")
SET(ENABLE_METVIEW ON  CACHE BOOL "Enable Metview")
