       PROGRAM PLOT_FREQUENCY

       REAL PROBA2(144,73)


       LLON=0
       LLAT=-90.
       RLON=360.
       RLAT=90.

       
       OPEN(UNIT=13,file='MASKENP',FORM='UNFORMATTED')
       READ(13) PROBA2


       CALL POPEN

       CALL PSETR('PAGE_ID_LINE_HEIGHT',0.3)
       CALL PSETR('SUPER_PAGE_Y_LENGTH',21.00)
       CALL PSETR('SUPER_PAGE_X_LENGTH',29.70)
       CALL PSETR('PAGE_Y_LENGTH',21.00)
       CALL PSETR('PAGE_X_LENGTH',29.70)
       CALL PSETC ('INPUT_FIELD_ORGANIZATION',     'REGULAR')
       CALL PSETR('SUBPAGE_X_POSITION', 2.0)
       CALL PSETR('SUBPAGE_Y_POSITION', 2.0)
       CALL PSETR('SUBPAGE_Y_LENGTH',17.00)
       CALL PSETR('SUBPAGE_X_LENGTH',25.70)
       CALL PSETC ('SUBPAGE_MAP_PROJECTION',      'CYLINDRICAL')
       CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',    LLON)
       CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',   RLON)


       CALL PSETR ('INPUT_FIELD_INITIAL_LONGITUDE',      0.0)
       CALL PSETR ('INPUT_FIELD_INITIAL_LATITUDE',  90.0000)
       CALL PSETR ('INPUT_FIELD_LONGITUDE_STEP',       2.500)
       CALL PSETR ('INPUT_FIELD_LATITUDE_STEP',        -2.500)

       CALL PSETC('PAGE_FRAME','OFF')
       CALL PSETC('PAGE_ID_LINE','OFF')


!
! Plot Regional Contours
!
       CALL PSET2R('INPUT_FIELD',PROBA2,144,73)

!      CALL PSETR('INPUT_FIELD_INITIAL_X',0.0)
!      CALL PSETR('INPUT_FIELD_FINAL_X',360.)
!      CALL PSETR('INPUT_FIELD_INITIAL_Y',90.)
!      CALL PSETR('INPUT_FIELD_FINAL_Y',-90.)


       CALL PSETC('CONTOUR','ON')
       CALL PSETC('CONTOUR_GRID_VALUE_PLOT','OFF')
       CALL PSETI('CONTOUR_HIGHLIGHT_THICKNESS', 55 )
       CALL PSETC('CONTOUR_HIGHLIGHT_COLOUR',  'BLUE' )
       CALL PSETC('MAP_GRID',                       'OFF')
       CALL PCONT
       CALL PCOAST


       CALL PCLOSE
       STOP

       END

