#!/bin/csh

# ---------------------------------------------------------------
# Cron job that will be run daily
# Cleans and rebuilds the Magics++ test suite and the HTML output
# As of 18/01/2005, it also rebuilds and uses our own version of
# the Magics++ library.
# ---------------------------------------------------------------



setenv LD_LIBRARY_PATH .

source ~/.login
source ~/.cshrc
setenv EMOSLIB -lemos
setenv ODB_VERSION latest
# setenv ODB_VERSION latest
#setenv MAGPLUS_VERSION x
#use newmagics++
use magicsX++
# source usedev
#use odb

#cd /var/tmp/cgi/PERFORCE/magics/docs/www/4_examples/progs
cd /tmp/cgi/PERFORCE/metview_4/magics/docs/www/4_examples/progs
echo "User: $USER"

# cd /ccview/metview_docs/src/libMagPlus
# make clean install

# source usetmp
# source setbin7
# cleanmpponly

setbin -shared
cleanps -mpp
make_testsuite -ps_gif_png_svg -nocompilempp -noodb
date > logs/zcron.log

source copytesttoscratch
