#!/bin/ksh

# get the command-line arguments

username=$1
password=$2



# go into the html directory and upload all the files

cd html


for file in *.html *.png *.gif intro/*  interfaces/* interfaces/*/* parameters/* formats/* install/* history/* environment/* versions/*
do
  # fname=`basename $file`
  fname=$file
  ../tools/dav.pl $fname $username $password w3ec2
done
