#!/bin/ksh

# get the command-line arguments

username=$1
password=$2



# go into the html directory and upload all the files

cd html


for file in *.html *.png *.gif intro/* examples/* examples/c/* examples/fortran/* examples/magml/* interfaces/* interfaces/c/* interfaces/fortran/* interfaces/magml/* formats/*  parameters/* 
# for file in interfaces/magml/* 
# for file in *.html *.png *.gif intro/* examples/*.html interfaces/* formats/* 
do
  fname=$file
  ../tools/dav.pl $fname $username $password wedit
done
