#!/bin/ksh

# get the command-line arguments

username=$1
password=$2



# go into the html directory and upload all the files

cd html


for file in  interfaces/fortran/fortran_compile.html 
do
  fname=$file
  ../tools/dav.pl $fname $username $password w3ec2
done
