      PROGRAM APP01
C
C	THIS PROGRAM DEMONSTRATES MAGICS TEXT WRITING CAPABILITIES.
C
C	OPEN MAGICS
C
	CALL POPEN
        CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','app01.ps')
	CALL PSETC ('PAGE_ID_LINE','OFF')
C
C	DEFINE PLOT LAYOUT.  NOTE THE SETTING UP OF SUPER_PAGE AND PAGE
C	SIZES TO ENABLE TWO PAGES TO FIT INTO THE SUPER_PAGE.  THE FRAME
C	AROUND THE SUBPAGE IS TURNED OFF.
C
	CALL PSETR ('SUPER_PAGE_Y_LENGTH',29.7)
	CALL PSETR ('SUPER_PAGE_X_LENGTH',21.0)
	CALL PSETR ('PAGE_X_LENGTH',21.0)
	CALL PSETR ('PAGE_Y_LENGTH',14.35)
	CALL PSETR ('PAGE_Y_GAP',1.0)
	CALL PSETC ('PLOT_START','TOP')
	CALL PSETC ('SUBPAGE_FRAME','OFF')
C
C	POSITION THE TEXT BOX
C
	CALL PSETC ('TEXT_MODE','POSITIONAL')
	CALL PSETR ('TEXT_BOX_X_POSITION',3.5)
	CALL PSETR ('TEXT_BOX_Y_POSITION',6.0)
	CALL PSETR ('TEXT_BOX_X_LENGTH', 14.0)
	CALL PSETR ('TEXT_BOX_Y_LENGTH',4.0)
C
C	WRITE TEXT ON PAGES ONE AND TWO OF FIFTH SUPER_PAGE
C
	CALL NINE

	CALL PNEW ('PAGE')
	CALL TEN

	CALL PNEW ('PAGE')
C
C	TERMINATE PLOTTING
C
	CALL PCLOSE

	END
	SUBROUTINE NINE
C
C	WRITE A BLOCK OF TEXT WITH DIFFERENT TEXT QUALITY
C
	CALL PSETI ('TEXT_LINE_COUNT',3)
	CALL PSETR ('TEXT_LINE_SPACE_RATIO',2.0)
	CALL PSETC ('TEXT_JUSTIFICATION','LEFT')
	CALL PSETC ('TEXT_QUALITY','HIGH')
	CALL PSETC ('TEXT_LINE_1','TEXT QUALITY IS HIGH')
	CALL PSETC ('TEXT_LINE_2','\QLM\TEXT QUALITY IS  MEDIUM')
	CALL PSETC ('TEXT_LINE_3','\QLL\TEXT QUALITY IS LOW')
	CALL PTEXT
C
	RETURN
	END
	SUBROUTINE TEN
C
C	WRITE A BLOCK OF TEXT DEMONSTRATIN UNDERLINING
C
      DIMENSION XPOS(4),YPOS(4),Y(4),XX(2),YY(2),ISTYL(4)
      CHARACTER*10 TXTX(4)
      DATA TXTX /'SOLID','DASH','DOT','CHAIN_DASH'/
      DATA XPOS /12.,11.9,11.7,13./
      DATA YPOS /10.,7.5,5.,2.5/
      DATA ISTYL /0,2,1,4/         
      DATA Y /10.,7.5,5.,2.5/
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC ('MAP_COASTLINE','OFF')                          
	CALL PSETC ('MAP_GRID','OFF')                          
	CALL PSETC ('MAP_LABEL','OFF')                          
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)     
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)     
      CALL PCOAST
	  CALL PSET1R ('SYMBOL_INPUT_X_POSITION',XPOS,4)        
	  CALL PSET1R ('SYMBOL_INPUT_Y_POSITION',YPOS,4)        
	  CALL PSET1C ('SYMBOL_INPUT_TEXT_LIST',TXTX,4)        
	  CALL PSETC ('SYMBOL_TYPE','TEXT')  
	  CALL PSETR ('SYMBOL_HEIGHT',0.5)  
	  CALL PSETC ('SYMBOL_POSITION_MODE','PAPER')
       CALL PSYMB
       DO 100 I=1,4
          XX(1)=3.0
          XX(2)=10.0
          YY(1)=Y(I)
          YY(2)=Y(I)
          CALL PLATTR(6,ISTYL(I))
          CALL MPOLYLINE(2,XX,YY)
100    CONTINUE
C
	RETURN
	END
