      PROGRAM CONT04
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOURING FACILITIES. THE
C     METEOROLOGICAL DATA FIELDS ARE A STANDARD GLOBAL 500 hPa HEIGHTS
C     MODEL OUTPUT FIELD ON A REGULAR 1.5 DEGREE GRID AND A MSL PRESSURE
C     FIELD ON A REDUCED T319 GAUSSIAN GRID.
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont04.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT04')             
C
C     DEFINE CYLINDRICAL MAP AREA AND PROJECTION
C
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE', 45.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE', -15.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE', 65.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE', 15.0)
C
C     PASS THE 500 hPa DATA TO MAGICS
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_SUBAREA_EXTRACTION', 'OFF')
      CALL PSETC ('GRIB_INPUT_FILE_NAME', 
     x   'data/oldts/500Z.grb')
      CALL PGRIB
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Input Field: 500 hPa Geopotential Height')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')           
C
C     DRAW CONTOURS GRID POINT VALUES FOR 500 hPa HEIGHTS ON 
C     CYLINDRICAL AREA
C
      CALL CONT04_ONE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH GRID VALUES FOR 500 hPa HEIGHTS ON POLAR
C     STEREOGRAPHIC MAP
C
      CALL CONT04_TWO
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH GRID VALUES FOR MSL ON CYLINDRICAL AREA
C     ALL GRID POINTS PLOTTED
C
      CALL CONT04_THREE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH GRID VALUES FOR MSL ON CYLINDRICAL AREA
C     ONLY REDUCED GAUSSIAN GRID POINTS PLOTTED
C
      CALL CONT04_FOUR
      CALL PNEW ('PAGE')
C
C     GRID VALUES FOR EVERY SECOND GRID POINT
C
      CALL CONT04_FIVE
      CALL PNEW ('PAGE')
C
C     GIRD VALUES LIMITED TO MIN/MAX VALUES
C
      CALL CONT04_SIX
      CALL PCLOSE
C
      END
      SUBROUTINE CONT04_ONE
C
C     DRAW CONTOUR LINES AND GRID POINT VALUES ON CYLINDRICAL AREA
C
C     ALL CONTOURING PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE
C     THEIR DEFAULT VALUES.
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL', 3.0)
      CALL PSETC ('CONTOUR_GRID_VALUE_PLOT', 'ON')
      CALL PSETR ('CONTOUR_GRID_VALUE_HEIGHT', 0.18)
      CALL PSETC ('CONTOUR_GRID_VALUE_FORMAT', '(F10.1)')
C
       CALL PSETC ('TEXT_LINE_2',
     1 'Grid Point Values on Cylindrical Area, Contour Interval '//
     2  ' is @(F5.1)CONTOUR_INTERVAL@' )
C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT04_TWO
C
C     DRAW CONTOUR LINES AND GRID POINT VALUES ON A POLAR STEREOGRAPHICS AREA.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LABEL_HEIGHT'                        0.25
C      'CONTOUR_LEVEL_SELECTION_TYPE'          'INTERVAL'
C      'CONTOUR_GRID_VALUE_PLOT'                     'ON'
C      'CONTOUR_GRID_VALUE_HEIGHT'                   0.18
C      'CONTOUR_GRID_VALUE_FORMAT'              '(F10.1)'
C
C     DEFINE POLAR STEREOGRAPHICS PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION', 'CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE', 54.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE', -5.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE', 10.E6)
      CALL PSETR ('CONTOUR_INTERVAL', 4.0)
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Input Field: 500 hPa Geopotential Height')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
       CALL PSETC ('TEXT_LINE_2',
     1 'Grid Point Values on Polar Stereographic Area. ' //
     2  ' Contour Interval is @(F5.1)CONTOUR_INTERVAL@' )

C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT04_THREE
C
C     DRAW GRID POINT VALUES FOR MSL ON CYLINDRICAL PROJECTION.
C     ALL GRID POINT VALUES PLOTTED FOR GAUSSIAN GRID.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LEVEL_SELECTION_TYPE'          'INTERVAL'
C      'CONTOUR_HILO_QUALITY'                      'HIGH'
C      'CONTOUR_HIGHLIGHT_FREQUENCY'                   3
C      'CONTOUR_LABEL_HEIGHT'                       0.25
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'CYLINDRICAL')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE', 75.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE', -5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE', 82.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE', 5.0)
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x 'data/oldts/msl.grb')
      CALL PGRIB
      CALL PSETC ('CONTOUR_GRID_VALUE_PLOT', 'ON')
      CALL PSETR ('CONTOUR_INTERVAL', 1.0)
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Input Field: MSL Pressure on T319 Reduced Gaussian grid')
      CALL PSETC ('TEXT_LINE_2',
     1 'All Grid Point Values are Plotted ')
C
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PCONT
      CALL PCOAST
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE CONT04_FOUR
C
C     DRAW GRID POINT VALUES FOR MSL ON CYLINDRICAL PROJECTION.
C     ONLY THE GRID POINT VALUES FOR THE REDUCED GRID ARE PLOTTED.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LEVEL_SELECTION_TYPE'          'INTERVAL'
C      'CONTOUR_HILO_QUALITY'                      'HIGH'
C      'CONTOUR_HIGHLIGHT_FREQUENCY'                   3
C      'CONTOUR_LABEL_HEIGHT'                       0.25
C      'CONTOUR_GRID_VALUE_PLOT'                     'ON'
C      'SUBPAGE_MAP_PROJECTION'             'CYLINDRICAL'
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                72.0
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'               -5.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'               79.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'               5.0
C
      CALL PSETI ('CONTOUR_GRID_VALUE_LAT_FREQUENCY',2)
      CALL PSETI ('CONTOUR_GRID_VALUE_LON_FREQUENCY',2)
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input FIeld: MSL Pressure on T319 Reduced Gaussian grid')
      CALL PSETC ('TEXT_LINE_2',
     1 'Every Second Grid Point Value is Plotted ')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PCONT
      CALL PCOAST
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE CONT04_FIVE
C
C     DRAW GRID POINT VALUES FOR MSL ON CYLINDRICAL PROJECTION.
C     ONLY THE GRID POINT VALUES FOR THE REDUCED GRID ARE PLOTTED.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LEVEL_SELECTION_TYPE'          'INTERVAL'
C      'CONTOUR_HILO_QUALITY'                      'HIGH'
C      'CONTOUR_HIGHLIGHT_FREQUENCY'                   3
C      'CONTOUR_LABEL_HEIGHT'                       0.25
C      'CONTOUR_GRID_VALUE_PLOT'                     'ON'
C      'SUBPAGE_MAP_PROJECTION'             'CYLINDRICAL'
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                72.0
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'               -5.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'               79.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'               5.0
C
      CALL PSETC ('CONTOUR_GRID_VALUE_TYPE', 'REDUCED')
      CALL PSETI ('CONTOUR_GRID_VALUE_LAT_FREQUENCY',1)
      CALL PSETI ('CONTOUR_GRID_VALUE_LON_FREQUENCY',1)
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input FIeld: MSL Pressure on T319 Reduced Gaussian grid')
      CALL PSETC ('TEXT_LINE_2',
     1 'Reduced Grid Point Values are Plotted ')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PCONT
      CALL PCOAST
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE CONT04_SIX
C
C     DRAW GRID POINT VALUES FOR MSL ON CYLINDRICAL PROJECTION.
C     ONLY THE GRID POINT VALUES FOR THE REDUCED GRID ARE PLOTTED.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LEVEL_SELECTION_TYPE'          'INTERVAL'
C      'CONTOUR_HILO_QUALITY'                      'HIGH'
C      'CONTOUR_HIGHLIGHT_FREQUENCY'                   3
C      'CONTOUR_LABEL_HEIGHT'                       0.25
C      'CONTOUR_GRID_VALUE_PLOT'                     'ON'
C      'SUBPAGE_MAP_PROJECTION'             'CYLINDRICAL'
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                72.0
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'               -5.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'               79.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'               5.0
C
      CALL PSETR ('CONTOUR_GRID_VALUE_MIN',990.0)
      CALL PSETR ('CONTOUR_GRID_VALUE_MAX',995.0)
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input FIeld: MSL Pressure on T319 Reduced Gaussian grid')
      CALL PSETC ('TEXT_LINE_2',
     1 'Reduced Grid Point Values are Plotted ')
      CALL PSETC ('TEXT_LINE_3',
     1 'Max Value = 990.0, Min Value = 995.0')
      CALL PSETI ('TEXT_LINE_COUNT', 3)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 0.5)
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
C
C     PLOT THE CONTOURS, COASTLINES AND TITLE
C
      CALL PCONT
      CALL PCOAST
      CALL PTEXT
C
      RETURN
      END
