C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT08
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOUR SHADING TECHNIQUES AND METHODS.
C     THERE ARE THREE TECHNIQUES - POLYGON_SHADING, MARKER and CELL_SHADING.
C     POLYGON SHADING HAS THREE METHODS - DOT, HATCH and AREA_FILL (SOLID).
C     THE AREA SELECTED IS A POLAR STEREOGRAPHIC ATLANTIC/EUROPEAN AREA AND THE
C     DATA TO BE CONTOURED/SHADED IS A MSL FIELD IN GRIB CODE.
C
C     OPEN MAGICS
C
      DIMENSION CONLIS (7)
      DATA CONLIS /450.0, 490.0, 520., 550., 565., 580., 620.0/
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont08.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT', 'TESTS/CONT08')
C
C     SELECT THE PROJECTION AND AREA AND PASS DATA TO MAGICS
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION', 'CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE', 40.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE', -20.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE', 35.E6)
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x 'data/oldts/500Z.grb')
      CALL PGRIB
C
C     SET GENERAL MAGICS PARAMETERS
C
      CALL PSETC ('CONTOUR_HILO', 'OFF')
      CALL PSETC ('CONTOUR_SHADE', 'ON')
      CALL PSETC ('LEGEND', 'ON')
      CALL PSETC ('CONTOUR_HIGHLIGHT', 'OFF')
      CALL PSETC ('CONTOUR_LINE_COLOUR', 'BLACK')
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'LEVEL_LIST')
      CALL PSET1R ('CONTOUR_LEVEL_LIST', CONLIS, 7)
      CALL PSETC ('MAP_GRID', 'OFF')
      CALL PSETC ('MAP_LABEL', 'OFF')
      CALL PSETC ('MAP_COASTLINE_COLOUR', 'BLACK')
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT', 1.25)
C
C     FIRST MAP - TECHNIQUE: POLYGON, METHOD: AREA_FILL
C
      CALL CONT08_ONE
      CALL PNEW ('PAGE')
C
C     SECOND MAP - TECHNIQUE: POLYGON, METHOD: DOT
C
      CALL CONT08_TWO
      CALL PNEW ('PAGE')
C
C     THIRD MAP - TECHNIQUE: POLYGON, METHOD: HATCH
C
      CALL CONT08_THREE
      CALL PNEW ('PAGE')
C
C     FOURTH MAP - TECHNIQUE: CELL_SHADING (DEFAULT)
C
      CALL CONT08_FOUR
      CALL PNEW ('PAGE')
C
C     FIVTH MAP - TECHNIQUE: CELL_SHADING (DIFFERENT METHOD AND RESOLUTION)
C
      CALL CONT08_FIVE
      CALL PNEW ('PAGE')    
C
C     SIXTH MAP - TECHNIQUE: MARKER
C
      CALL CONT08_SIX

      CALL PCLOSE
      STOP
      END    
    






      SUBROUTINE CONT08_ONE
C
C     THIS ROUTINE USES POLYGON SHADING TECHNIQUE WITH 'DOT' METHOD
C
C     PLOT THE SHADED CONTOURS
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'POLYGON_SHADING')   
      CALL PSETC ('CONTOUR_SHADE_METHOD', 'DOT')
      CALL PSETR ('CONTOUR_SHADE_DOT_SIZE', 0.045)     
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETI ('TEXT_LINE_COUNT', 1)
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE= POLYGON '//
     x    '    SHADE_METHOD= DOT')
      CALL PTEXT
      RETURN
      END
      SUBROUTINE CONT08_TWO
C
C     THIS ROUTINE USES POLYGON SHADING TECHNIQUE WITH 'HATCH' METHOD
C
C     PLOT THE SHADED CONTOURS
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'POLYGON_SHADING')   
      CALL PSETC ('CONTOUR_SHADE_METHOD', 'HATCH') 
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE= POLYGON '//
     x    '    SHADE_METHOD= HATCH')
      CALL PTEXT
      RETURN
      END
      SUBROUTINE CONT08_THREE

C
C     THIS ROUTINE USES POLYGON SHADING TECHNIQUE WITH 'REA_FILL' METHOD
C
C     PLOT THE SHADED CONTOURS
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'POLYGON_SHADING')   
      CALL PSETC ('CONTOUR_SHADE_METHOD', 'AREA_FILL')   
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE= POLYGON '//   
     x   '    SHADE_METHOD = AREA_FILL')
      CALL PTEXT
      RETURN
      END

      SUBROUTINE CONT08_FOUR
C
C     THIS ROUTINE USES CELL SHADING TECHNIQUE,  DEFAULT CELL_METHOD = 'INTERPOLATE'
C     DEFAULT CELL_RESOLUTION = 10.0 
C
C     PLOT THE SHADED CONTOURS - DEFAULT CELL_METHOD = 'INTERPOLATE'
C     DEFAULT CELL_RESOLUTION = 10.0
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'CELL_SHADING')   
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE = CELL_SHADING                ')
      CALL PSETC ('TEXT_LINE_2',
     X'CELL_METHOD = INTERPOLATE , CELL RESOLOUTION = 10.0  ')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END
      SUBROUTINE  CONT08_FIVE
C
C     THIS ROUTINE USES CELL SHADING TECHNIQUE,  CELL_METHOD = 'NEAREST'
C     DEFAULT CELL_RESOLUTION = 20.0
C
C     PLOT THE SHADED CONTOURS  
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'CELL_SHADING')  
      CALL PSETC ('CONTOUR_SHADE_CELL_METHOD', 'NEAREST')
      CALL PSETR ('CONTOUR_SHADE_CELL_RESOLUTION', 20.0) 
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE = CELL_SHADING                ')
      CALL PSETC ('TEXT_LINE_2',
     X'CELL_METHOD = NEAREST, CELL RESOLOUTION = 20.0  ')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END
      SUBROUTINE CONT08_SIX
      CHARACTER*32 COLTAB
      DIMENSION  HGTAB(6), MARTAB(6)
      DATA MARTAB /3, 5, 7, 9, 15, 18/
      DATA HGTAB /0.22, 0.23, 0.21, 0.18, 0.17, 0.15/
C
C     CYLINDICAL AREA FOR MARKER SHADING TO AVOID CONGESTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'CYLINDRICAL')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE', 20.0)    
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE', -30.0)    
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE', 70.0)    
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE', 40.0)    
C
C     THIS ROUTINE USES MARKER SHADING TECHNIQUE 
C
C     EACH SHADING LEVEL WILL HAVE A DIFFERENT MARKER SYMBOL, HEIGHT AND COLOUR
C     - DEFINED BY THE TABLES MARTAB, HGTAB AND COLTAB
C     6 SHADING LEVELS REQUIRED DEFINED PREVIOUSLY
C
      CALL PSET1I ('CONTOUR_SHADE_MARKER_TABLE', MARTAB, 6)
      CALL PSET1R ('CONTOUR_SHADE_HEIGHT_TABLE', HGTAB, 6)
C
C     PLOT THE SHADED CONTOURS
C
      CALL PSETC ('CONTOUR_SHADE_TECHNIQUE', 'MARKER')   
      CALL PCONT
C
C     PLOT THE COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'CONTOUR_SHADE_TECHNIQUE = MARKER -  VARIOUS MARKERS AND HEIGHTS')
      CALL PSETI ('TEXT_LINE_COUNT', 1)
      CALL PTEXT
      RETURN
      END

