C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT07                    
C
C     THIS PROGRAM DEMONSTRATES MAGICS SHADING FOR RAINFALL. THE
C     RAINFALL FIELD IS ON A GAUSSIAN GRID AND CONTAINS THE
C     TOTAL RAINFALL (CONVECTIVE + NON-CONVECTIVE) ACCUMULATED OVER THE
C     PERIOD 00z TO 12z FOR 28/9/85. THE RAINFALL IS PLOTTED WITH A
C     CONTOUR INTERVAL OF 10mm AND THE MINIMUM LEVEL PLOTTED IS 1.0 mm.
C     THE MAXIMA OF THE FIELD ARE PLOTTED AS NUMBERS AND THE MINIMA ARE
C     NOT PLOTTED. THE SHADING DOT DENSITY IS 10.0 FOR THE LOWEST
C     SHADING BAND AND INCREASES LINEARLY TO 60.0 FOR THE HIGHEST BAND.
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont07.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT07')
C
C     TURN LEGEND ON
C
      CALL PSETC ('LEGEND','ON')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_SCALE',25.E6)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',-90.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',44.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-88.0)
      CALL PSETR ('SUBPAGE_Y_LENGTH ',17.0)             
      CALL PSETR ('MAP_GRID_LATITUDE_INCREMENT',20.0)
      CALL PSETR ('MAP_GRID_LATITUDE_REFERENCE',10.0)
      CALL PSETC ('MAP_COASTLINE_COLOUR','BLACK')
      CALL PSETC ('MAP_GRID_COLOUR','BLACK')
C
C     PASS THE DATA TO MAGICS
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME', 
     x  'data/oldts/lsp.grb')
      CALL PGRIB
C
C     SET UP CONTOURING PARAMETERS
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL',10.0)
      CALL PSETR ('CONTOUR_MIN_LEVEL',1.0)
      CALL PSETR ('CONTOUR_REFERENCE_LEVEL',1.0)
      CALL PSETC ('CONTOUR_HIGHLIGHT','OFF')
      CALL PSETC ('CONTOUR_LABEL','OFF')
C
C     SET UP HILO PARAMETERS
C
      CALL PSETC ('CONTOUR_HILO','HI')
      CALL PSETC ('CONTOUR_HI_COLOUR','RED')
      CALL PSETR ('CONTOUR_HILO_MIN_VALUE', 8.0)
      CALL PSETC ('CONTOUR_HILO_QUALITY','HIGH')
      CALL PSETR ('CONTOUR_HILO_HEIGHT',0.3)
      CALL PSETC ('CONTOUR_HILO_FORMAT','(I4)')
      CALL PSETC ('CONTOUR_HILO_TYPE','NUMBER')




C
C     SHADING PARAMETERS
C
      CALL PSETC ('CONTOUR_SHADE','ON')
      CALL PSETR ('CONTOUR_SHADE_MIN_LEVEL',1.0)
      CALL PSETR ('CONTOUR_SHADE_MIN_LEVEL_DENSITY',10.0)
      CALL PSETR ('CONTOUR_SHADE_MAX_LEVEL_DENSITY',100.0)
      CALL PSETR ('CONTOUR_SHADE_DOT_SIZE',0.04)

C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1','Contour Shading Example')
      CALL PSETC ('TEXT_LINE_2',
     1            ' Shading using Varying Dot Densities ')
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
C     PLOT THE TITLE, COASTLINES, CONTOURS AND SHADING
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      STOP
      END




