C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT12
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont12.ps')
      CALL PSETC('SUBPAGE_MAP_PROJECTION','LAMBERT')
      CALL PSETC('GRIB_INPUT_TYPE','FILE')
      CALL PSETC('GRIB_INPUT_FILE_NAME',
     x   'data/oldts/500Z.grb')
      CALL PGRIB
      CALL PSETC('CONTOUR_HILO','OFF')
      CALL PSETC('CONTOUR_SHADE','ON')
      CALL PSETC('CONTOUR_SHADE_METHOD','AREA_FILL')
      CALL PSETC('MAP_COASTLINE_COLOUR','BLACK')
      CALL PSETC('MAP_GRID_COLOUR','BLACK')
      CALL CONT12_ONE
      CALL PNEW('PAGE')
      CALL CONT12_TWO
      CALL PNEW('PAGE')
      CALL CONT12_THREE
      CALL PCLOSE
      STOP
      END
      SUBROUTINE CONT12_ONE
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-54.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',-35.)
      CALL PCONT
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-154.5)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCONT
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-94.5)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCONT
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',165.0)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCONT
      CALL PCOAST
      RETURN
      END
      SUBROUTINE CONT12_TWO
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-64.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',-25.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-65.)
      CALL PCONT
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-64.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',180.0)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',-35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-45.)
      CALL PCONT
      CALL PCOAST
      CALL PNEW('PAGE')
      RETURN
      END
      SUBROUTINE CONT12_THREE
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-54.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',90.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',-55.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-65.)
      CALL PCONT
      CALL PCOAST
      RETURN
      END
