      PROGRAM CONT09
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOURING FACILITIES FOR VARIOUS
C     TYPES OF INPUT FIELD FORMATS - REGULAR GRIDS, GAUSSIAN GRIDS, SPECTRAL FIELDS,
C     POLAR STEREOGRAPHIC AND STRETCHED/ROTATED FIELDS (REGULAR AND SPECTRAL).
C
C     CONTOURS  ARE PROJECTED ONTO A POLAR STEREOGRAPHIC MAP.
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont09.ps')

      CALL PSETC ('PAGE_ID_LINE_USER_TEXT', 'TESTS/CONT09')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')

      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE', 5.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE', 55.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE', 5.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE', 30.E6)
      CALL PSETC ('MAP_COASTLINE_COLOUR','CREAM')
      CALL PSETC ('MAP_GRID_COLOUR','BLACK')
      CALL PSETC ('MAP_COASTLINE_LAND_SHADE','ON')
      CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','CREAM')
C
C     INPUT FIELD IS ON A REGULAR 1.5 DEGREE GRID
C
      CALL CONT09_ONE
      CALL PNEW ('PAGE')
C
C     INPUT FIELD IS ON T319 GAUSSIAN GRID
C
      CALL CONT09_TWO
      CALL PNEW ('PAGE')
C
C     INPUT FIELD IS IN SPHERICAL HARMONICS
C
      CALL CONT09_THREE
      CALL PNEW ('PAGE')
C
C     INPUT FIELD IS A POLAR STEREOGRAPHIC FIELD
C
      CALL CONT09_FOUR
      CALL PNEW ('PAGE')
C
C     INPUT FIELD IS ROTATED IN A LAT/LONG PROJECTION
C
      CALL CONT09_FIVE
      CALL PNEW ('PAGE')
C
C     INPUT FIELD IS ROTATED IN SPHERICAL HARMONICS
C
      CALL CONT09_SIX

      CALL PCLOSE
      STOP
      END
      SUBROUTINE CONT09_ONE
C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. DEFAULT VALUES FOR ALL
C     CONTOUR PARAMETERS.
C     THE INPUT FIELD IS A GLOBAL 500 hpa GEOPOTENTIAL HEIGHT FIELD ON A REGULAR
C     1.5 DEGREE GRID.
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x  'data/oldts/500Z.grb')
      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS
C
      CALL PCOAST
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic 500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Regular Global 1.5 Degree LAT/LONG Field')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END

      SUBROUTINE CONT09_TWO
C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. DEFAULT VALUES FOR ALL
C     CONTOUR PARAMETERS.
C     THE INPUT FIELD IS A GLOBAL MEAN SEA LEVEL PRESSURE FIELD ON A T319 GAUSSINA GRID
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x  'data/oldts/msl.grb')
      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS
C
      CALL PCOAST
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic Mean Sea Level Pressure')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Global T319 Gaussian Grid')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END


      SUBROUTINE CONT09_THREE
C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. DEFAULT VALUES FOR ALL
C     CONTOUR PARAMETERS.
C     THE INPUT FIELD IS A GLOBAL 500 hpa GEOPOTENTIAL HEIGHT FIELD IN SPHERICAL HARMONICS.
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x  'data/oldts/500Z_AN.grb')
      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS
C
      CALL PCOAST
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic 500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Global Spectral  Field')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END

      SUBROUTINE CONT09_FOUR

C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. CONTOUR INTERVAL IS 5.0 AND
C     CONTOUR MAXIMUM LEVEL IS 1150.0.
C     THE VALUES ABOVE 999998.0 AND BELOW -999998.0 ARE SUPPRESSED DURING THE CONTOURING
C     BECAUSE THE FIELD CONTAINS AREAS WHERE DATA IS MISSING, .
C
C     THE INPUT FIELD IS IN A POLAR STEREOGRAPHIC PROJECTION WHICH IS DIFFERENT TO THE
C     PROJECTION TO BE PLOTTED. SUBROUTINE PGRIB HANDLES THE TRANSFORMATION AND THE
C     RE-PROJECTION OF THE DATA.
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x 'data/oldts/fmi.grib')
      CALL PSETC ('GRIB_SPECIFICATION', 'OFF')
      CALL PGRIB

      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS - SUPPRESS MISSING VALUES
C
      CALL PCOAST
      CALL PSETR ('CONTOUR_MAX_LEVEL', 1150.0)
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL', 5.0)
      CALL PSETR ('INPUT_FIELD_SUPPRESS_ABOVE', 999998.)
      CALL PSETR ('INPUT_FIELD_SUPPRESS_BELOW', -999998.)
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic 500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Different Polar Stereographic GRIB coded '//
     2 ' field')
      CALL PSETI ('TEXT_LINE_COUNT', 2)

      CALL PTEXT

      RETURN
      END
      SUBROUTINE CONT09_FIVE
C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. CONTOUR INTERVAL IS 8.0.
C
C     THE INPUT FIELD IS A 500 hPa ROTATED FIELD IN A LAT/LONG PROJECTION.
C     SUBROUTINE PGRIB HANDLES THE PROJECTION OF THE DATA.
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x 'data/oldts/z500.rot_latlon')
      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS
C
      CALL PCOAST
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL', 8.00000)
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic 500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Stretched/Rotated field on a '//
     2 'Regular LAT/LONG Grid ')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
      CALL PTEXT
      RETURN
      END
      SUBROUTINE CONT09_SIX
C
C     PLOT CONTOURS ON A POLAR STEREOGRAPHIC PROJECTION. CONTOUR INTERVAL IS 8.0.
C
C     THE INPUT FIELD IS A 500 hPa ROTATED FIELD IN SPHERICAL HARMONICS.
C
C     SUBROUTINE PGRIB HANDLES THE PROJECTION OF THE DATA.
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x   'data/oldts/z500.rot_spectral')
      CALL PGRIB
C
C     PLOT THE COASTLINES AND CONTOURS
C
      CALL PCOAST
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE', 'INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL', 8.00000)
      CALL PCONT
C
C     GENERATE AND PLOT TITLE TEXT
C
      CALL PSETC ('TEXT_JUSTIFICATION', 'CENTRE')
      CALL PSETC ('TEXT_LINE_1',
     1 'Polar Stereographic 500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1 'Projected from a Stretched/Rotated field in'//
     2 ' Spherical Harmonics')
      CALL PSETI ('TEXT_LINE_COUNT', 2)
C
C     PLOT THE TITLE, COASTLINES AND CONTOURS
C
      CALL PTEXT
      RETURN
      END
