C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT03
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOURING FACILITIES. 
C     THE METEOROLOGICAL DATA FIELD IN FILE 500Z.grb  IS A STANDARD 
C     GLOBAL 500 hPa MODEL OUTPUT FIELD ON A REGULAR 1.5 DEGREE GRID.
C     CONTOURS ARE PROJECTED ONTO A POLAR STEREOGRAPHIC MAP.
C     COASTLINES AND GRID LINES ARE NOT PLOTTED.
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont03.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT03')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',95.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',35.0)
C
C     PASS THE DATA TO MAGICS
C
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     x  'data/oldts/500Z.grb')
      CALL PGRIB
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
C
C     DRAW ONE CONTOUR LINE
C
      CALL CONT03_ONE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOUR WITH USER TEXT
C
      CALL CONT03_TWO
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS ABOVE AND BELOW A CERTAIN LEVEL
C
      CALL CONT03_THREE
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END
      SUBROUTINE CONT03_ONE
C
C     DRAW ONLY ONE SELECTED CONTOUR LINE WITH HIGHS AND LOWS INDICATED
C
C     ALL CONTOURING PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE
C     THEIR DEFAULT VALUES.
C
      CALL PSETR ('CONTOUR_MAX_LEVEL',560.0)
      CALL PSETR ('CONTOUR_MIN_LEVEL',560.0)
      CALL PSETR ('CONTOUR_LABEL_HEIGHT',0.3)
      CALL PSETI ('CONTOUR_HIGHLIGHT_THICKNESS',5)
      CALL PSETC ('CONTOUR_HILO_QUALITY','HIGH')
C
      CALL PSETC ('TEXT_LINE_2',
     1'Only One Contour Line 560 hPa is selected, '//
     2 'HILO Text Quality is HIGH')
C
C     PLOT THE TITLE AND CONTOURS 
C
      CALL PTEXT
      CALL PCONT
C
      RETURN
      END





      SUBROUTINE CONT03_TWO
C
C     DRAW ONE SPECIFIC CONTOUR LINE, LABELED WITH USER'S TEXT.
C     HIGH/LOW MARKERS ARE PLOTTED.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_MAX_LEVEL'                      560.0
C      'CONTOUR_MIN_LEVEL'                      560.0
C      'CONTOUR_LABEL_HEIGHT'                     0.3
C      'CONTOUR_HIGHLIGHT_THICKNESS'                5
C
      CALL PSETR ('CONTOUR_HILO_SUPPRESS_RADIUS',5.0)
      CALL PSETC ('CONTOUR_HILO_TYPE','BOTH')
      CALL PSETC ('CONTOUR_HILO_FORMAT','(F10.1)')
      CALL PSETC ('CONTOUR_HILO_MARKER','ON')
      CALL PSETC ('CONTOUR_HILO_QUALITY','MEDIUM')
      CALL PSETR ('CONTOUR_HILO_MARKER_HEIGHT',0.25)
      CALL PSETC ('CONTOUR_LABEL_TYPE','TEXT')
      CALL PSETC ('CONTOUR_LABEL_TEXT','Mean Level')
C
      CALL PSETC ('TEXT_LINE_2',
     1'Contour is Labelled with User''s Text')
      CALL PSETC ('TEXT_LINE_3',
     2'HILO Markers are Plotted, Suppress Radius is 5.0')  
      CALL PSETI ('TEXT_LINE_COUNT',3)          
C
C     PLOT THE TITLE AND CONTOURS
C
      CALL PTEXT
      CALL PCONT      
      CALL PRESET ('CONTOUR_MAX_LEVEL')
      CALL PRESET ('CONTOUR_MIN_LEVEL')
      CALL PRESET ('CONTOUR_LABEL_TYPE')
      CALL PRESET ('CONTOUR_HILO_TYPE')
      CALL PRESET ('CONTOUR_HILO_MARKER')
      CALL PRESET ('CONTOUR_HILO_FORMAT')
C
      RETURN
      END





      SUBROUTINE CONT03_THREE                  
C
C     DRAW CONTOUR LINES SPLIT INTO TWO GROUPS: LINES HIGHER THEN AND
C     LOWER THAN 560HPA. 
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_LABEL_HEIGHT'                     0.3
C      'CONTOUR_HILO_SUPPRESS_RADIUS'             5.0
C      'CONTOUR_HILO_QUALITY'                'MEDIUM
C
C     CONTOUR INTERVAL IS 5.0
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL',5.0)
C
C     THE SPLIT LEVEL IS 560 hPa WHICH IS A SOLID LINE, THICKNESS 1
C
      CALL PSETC ('CONTOUR_LINE_PLOTTING','SPLIT')
      CALL PSETC ('CONTOUR_SPLIT_LINE_PLOT','ON')
      CALL PSETR ('CONTOUR_SPLIT_LEVEL',560.)
C
C     CONTOURS ABOVE 560 hPa WILL BE DASHED WITH THICKNESS 3
C
      CALL PSETC ('CONTOUR_ABOVE_LINE_STYLE','DASH')
      CALL PSETC ('CONTOUR_ABOVE_HIGHLIGHT_STYLE','DASH')
      CALL PSETI ('CONTOUR_ABOVE_LINE_THICKNESS',3)
      CALL PSETI ('CONTOUR_ABOVE_HIGHLIGHT_THICKNES',3)
C
C     CONTOURS BELOW 560 hPa WILL BE DOTTED WITH THICKNESS 3
C
      CALL PSETC ('CONTOUR_BELOW_LINE_STYLE','DOT')
      CALL PSETC ('CONTOUR_BELOW_HIGHLIGHT_STYLE','DOT')
      CALL PSETI ('CONTOUR_BELOW_LINE_THICKNESS',3)
      CALL PSETI ('CONTOUR_BELOW_HIGHLIGHT_THICKNES',3)
      CALL PSETC ('CONTOUR_LABEL_FORMAT','(I4)')
      CALL PCONT
C
      CALL PSETC ('TEXT_LINE_2',
     1'Split level is 560 hPa. Dashed Lines >> 560 hPa')
      CALL PSETC ('TEXT_LINE_3',
     1'Dotted Lines << 560 hPa')
      CALL PTEXT
C
      RETURN
      END




