C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

     
      PROGRAM CONT06                    
C
C     THIS PROGRAM DEMONSTRATES MAGICS SHADING FACILITIES FOR SHADING
C     SELECTED LEVELS. 
C     THE METEOROLOGICAL FIELD IS A STANDARD GLOBAL 500 MB MODEL OUTPUT FIELD.
C     THE AREAS TO BE SHADED ARE SELECTED BY SETTING THE MAGICS
C     PARAMETERS CONTOUR_SHADE_MIN_LEVEL AND CONTOUR_SHADE_MAX_LEVEL.
C     THE SHADING DOTS ARE OF EQUAL SIZE AND EQUIDISTANT FROM EACH OTHER
C     IN EACH BAND. ACTION ROUTINE PCONT IS CALLED FOR EACH SHADING
C     BAND.
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont06.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT06')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',95.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',35.0)
      CALL PSETC ('MAP_COASTLINE_STYLE', 'DOT')
      CALL PSETC ('MAP_GRID_LINE_STYLE', 'DOT')
C
C     PASS THE DATA TO MAGICS
C
      CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME', 
     x  'data/oldts/500Z.grb')
      CALL PGRIB
C
C     SET UP CONTOURING PARAMETERS
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL',8.0)
C
C     SET SHADING PARAMETERS
C     FIRST BAND 544 - 552
C     DOT SIZE 0.04 AND MIN LEVEL DENSITY 50.0
C
      CALL PSETC ('CONTOUR_SHADE','ON')
      CALL PSETR ('CONTOUR_SHADE_DOT_SIZE',0.04)
      CALL PSETR ('CONTOUR_SHADE_MIN_LEVEL_DENSITY',50.0)
      CALL PSETR ('CONTOUR_SHADE_MIN_LEVEL',544.0)
      CALL PSETR ('CONTOUR_SHADE_MAX_LEVEL',552.0)
C
C     PLOT THE COASTLINES AND CONTOURS AND SHADING
C     FOR BAND BETWEEN 544.0 and 552.0
C
      CALL PCOAST
C
      CALL PCONT
C
C     PLOT SECOND BAND BETWEEN 576.0 AND 584.0
C
      CALL PSETR ('CONTOUR_SHADE_MIN_LEVEL',576.0)
      CALL PSETR ('CONTOUR_SHADE_MAX_LEVEL',584.0)
      CALL PCONT


C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1','Contour Shading Example')
      CALL PSETC ('TEXT_LINE_2','Shading Between Selected Bands')
C
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PTEXT
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END




