C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT05
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOUR MAXIMA/MINIMA PLOTTING
C     FACILITIES. THE METEOROLOGICAL DATA FIELD WHICH IS IN GRIB CODE
C     IS A GLOBAL SURFACE TEMPERATURE MODEL OUTPUT FIELD ON A
C     GAUSSIAN GRID.
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont05.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT05')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_MAP_SCALE',30.0E6)
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-5.)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETC ('MAP_COASTLINE_STYLE', 'DOT')
C
C     PASS THE DATA TO MAGICS
C
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     c   'data/oldts/2t.grb')
      CALL PGRIB
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Polar Stereographic Map of Surface Temperature')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
C
C     PLOT ALL MAXIMA/MINIMA WITH MARKERS AND WITH VALUES AND TEXT SYMBOLS
C
      CALL CONT05_ONE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH SUPPRESSED HIGHS AND LOWS
C
      CALL CONT05_TWO
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH SUPPRESSED HIGHS AND LOWS
C
      CALL CONT05_THREE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH HIGHS AND LOWS INDICATED
C
      CALL CONT05_FOUR
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END
      SUBROUTINE CONT05_ONE
C
C     DRAW CONTOURS, WITH ALL MINIMA AND MAXIMA. EACH MINIMA/MAXIMA IS REPRESENTED BY
C     A MARKER SYMBOL. THE ACTUAL VALUES OF THE MINIMA/MAXIMA ARE PLOTTED ABOVE THE
C     MARKER AND TEXT SYMBOLS ('L'/'H') BELOW THE MARKER. THE MARKER SYMBOL IS CHANGED
C     FROM THE DEFAULT (1) TO 8. THE HEIGHT OF THE MARKER SYMBOL IS MODIFIED,AS IS THE
C     HEIGHT OF THE ACTUAL VALUES AND TEXT.
C
C     ALL CONTOUR PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE
C     THEIR DEFAULT VALUES.
C
      CALL PSETR ('CONTOUR_HILO_SUPPRESS_RADIUS',0.0)
      CALL PSETR ('CONTOUR_HILO_HEIGHT',0.25)
      CALL PSETC ('CONTOUR_HILO_TYPE','BOTH')
      CALL PSETC ('CONTOUR_HILO_FORMAT','(I4)')
      CALL PSETC ('CONTOUR_HILO_MARKER','ON')
      CALL PSETI ('CONTOUR_HILO_MARKER_INDEX',8)
      CALL PSETR ('CONTOUR_HILO_MARKER_HEIGHT',0.2)
C
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Polar Stereographic Map of Surface Temperature')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_LINE_2',
     1            'All Highs and Lows Plotted with Actual Values '//
     2            'and Marked With Marker Symbols')
C
C     PLOT COASTLINES, TITLE TEXT AND CONTOURS
C
      CALL PCOAST
      CALL PTEXT
      CALL PCONT
C
      RETURN
      END





      SUBROUTINE CONT05_TWO
C
C     DRAW CONTOUR LINES IN THE SAME AREA WITH HIGHS AND LOWS WHICH
C     ARE LIMITED BY USING CONTOUR_HILO_SUPPRESS_RADIUS PARAMETER.
C     RADIUS IS 5.0.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_HILO_HEIGHT'                          0.25
C      'CONTOUR_HILO_TYPE'                           'BOTH'
C      'CONTOUR_HILO_FORMAT'                         '(I4)'
C      'CONTOUR_HILO_MARKER'                           'ON'
C      'CONTOUR_HILO_MARKER_INDEX'                       8
C      'CONTOUR_HILO_MARKER_HEIGHT'                    0.2
C
      CALL PSETR ('CONTOUR_HILO_SUPPRESS_RADIUS', 5.0)
      CALL PSETC ('CONTOUR_HILO_QUALITY','LOW')
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Polar Stereographic Map of Surface Temperature')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_LINE_2',
     1            'Highs and Lows are Limited Setting Parameter '//
     2            'CONTOUR_HILO_SUPPRESS_RADIUS '//
     3            'to @(F6.1)CONTOUR_HILO_SUPPRESS_RADIUS@')
C
C     PLOT CONTOURS, COASTLINES, TEXT AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END





      SUBROUTINE CONT05_THREE
C
C     DRAW CONTOURS WITH HIGHS ONLY AND WITH SUPPRESS RADIUS 15.0.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_HILO_HEIGHT'                          0.25
C      'CONTOUR_HILO_TYPE'                           'BOTH'
C      'CONTOUR_HILO_FORMAT'                         '(I4)'
C      'CONTOUR_HILO_QUALITY'                         'LOW'
C      'CONTOUR_HILO_MARKER'                           'ON'
C      'CONTOUR_HILO_MARKER_INDEX'                       8
C      'CONTOUR_HILO_MARKER_HEIGHT'                    0.2
C
      CALL PRESET ('CONTOUR_HILO_SUPPRESS_RADIUS')
      CALL PSETC ('CONTOUR_HILO', 'HI')
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Polar Stereographic Map of Surface Temperature')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_LINE_2',
     1            'Highs Only and Suppress Radius is @(F6.1)' //
     2            'CONTOUR_HILO_SUPPRESS_RADIUS@ (Default)')
C
C     PLOT CONTOURS, COASTLINES, TEXT AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
      CALL PRESET('CONTOUR_HILO_TYPE')
      CALL PRESET('CONTOUR_HILO_MARKER_HEIGHT')
      CALL PRESET('CONTOUR_HILO_HEIGHT')
C
      RETURN
      END





      SUBROUTINE CONT05_FOUR
C
C     DRAW CONTOURS WITH HIGHS AND LOWS, IN THE SPECIFIED RANGE OF
C     VALUES, LABELLED BY THE TEXT 'HIGH' AND 'LOW'.
C
C     THE FOLLOWING CONTOUR PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOUR PARAMETERS THAT ARE NOT SET IN THIS
C     SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_HILO_FORMAT'                         '(I4)'
C      'CONTOUR_HILO_MARKER'                           'ON'
C
C
      CALL PSETC ('CONTOUR','OFF')
      CALL PSETR ('CONTOUR_HILO_SUPPRESS_RADIUS', 25.0)
C
C     PLOT LOWS ONLY FROM -10.0 TO 0.0. LOWS LABELLED 'Low'
C
      CALL PSETC ('CONTOUR_HILO','LO')
      CALL PSETR ('CONTOUR_HILO_MIN_VALUE',-10.0)
      CALL PSETR ('CONTOUR_HILO_MAX_VALUE',0.0)
      CALL PSETC ('CONTOUR_HILO_QUALITY','HIGH')
      CALL PSETC ('CONTOUR_LO_TEXT','Low')
      CALL PSETI ('CONTOUR_HILO_MARKER_INDEX',15)
      CALL PCONT
C
C     PLOT HIGHS ONLY FROM 10.0 TO 30.0. HIGHS LABELLED 'High'
C
      CALL PSETR ('CONTOUR_HILO_MIN_VALUE',10.0)
      CALL PSETR ('CONTOUR_HILO_MAX_VALUE',30.0)
      CALL PSETC ('CONTOUR_HILO','HI')
      CALL PSETC ('CONTOUR_HI_TEXT','High')
      CALL PCONT
C
C     PLOT CONTOURS WITH NO HIGHS/LOWS
C
      CALL PSETC ('CONTOUR','ON')
      CALL PSETC ('CONTOUR_HILO','OFF')
      CALL PCONT
C
      CALL PSETC ('TEXT_LINE_1',
     1            'Polar Stereographic Map of Surface Temperature')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETC ('TEXT_LINE_2',
     1            'Highs and Lows in Specified Ranges Labelled '//
     2            'with Texts High and Low')
C
C     PLOT COASTLINES AND TITLE
C
      CALL PCOAST
      CALL PTEXT
C
      RETURN
      END

