C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM CONT02
C
C     THIS PROGRAM DEMONSTRATES MAGICS CONTOURING FACILITIES. THE
C     METEOROLOGICAL DATA FIELD IS A STANDARD GLOBAL 500 hPa
C     MODEL OUTPUT FIELD ON A REGULAR 1.5 DEGREE GRID. 
C     CONTOURS ARE PROJECTED ONTO A POLAR STEREOGRAPHIC MAP.
C     GRIDLINES ARE NOT PLOTTED.
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','cont02.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/CONT02')
C
C     PASS THE DATA TO MAGICS
C
      CALL PSETC('GRIB_INPUT_TYPE','FILE')
      CALL PSETC('GRIB_INPUT_FILE_NAME',
     x  'data/oldts/500Z.grb')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',95.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',35.0)
      CALL PGRIB
C
C     DRAW CONTOURS WITH NO HIGHLIGHTING
C
      CALL PSETC ('MAP_GRID','OFF')
      CALL CONT02_ONE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH SELECTED INTERVAL
C
      CALL CONT02_TWO
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH HIGHLIGHTED LINES
C
      CALL CONT02_THREE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS WITH SELECTED LEVELS
C
      CALL CONT02_FOUR
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS HIGHLIGHTED WITH DASHED LINES
C
      CALL CONT02_FIVE
      CALL PNEW ('PAGE')
C
C     DRAW CONTOURS HIGHLIGHTED WITH RED LINES
C
      CALL CONT02_SIX
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END
      SUBROUTINE CONT02_ONE
C
C     DRAW CONTOURS WITH REFERENCE LEVEL 550 HPA. NO CONTOUR LINES
C     HIGHLIGHTED.
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
C
      CALL PSETC ('TEXT_LINE_2',
     1'Contour Reference Level 550.0 hPa, no contours Highlighted')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     ALL CONTOURING PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE TAKE
C     THEIR DEFAULT VALUES.
C
      CALL PSETC ('CONTOUR_HIGHLIGHT','OFF')
      CALL PSETR ('CONTOUR_REFERENCE_LEVEL', 550.0)
      CALL PSETR ('CONTOUR_LABEL_HEIGHT', 0.25)
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT02_TWO
C
C     DRAW CONTOURS WITH SELECTED INTERVAL (DEFAULT IS 8), CHANGE LABEL
C     FORMAT.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     ROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_HIGHLIGHT'                    'OFF'
C      'CONTOUR_REFERENCE_LEVEL'              550.0
C      'CONTOUR_LABEL_HEIGHT'                  0.25
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETC ('CONTOUR_LABEL_FORMAT', '(E12.3)')
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETC ('TEXT_LINE_2',
     1'Contour Interval 8 (Default) and Label Format E12.3')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
C     RESET LABEL FORMAT
C
      CALL PRESET ('CONTOUR_LABEL_FORMAT')
C
      RETURN
      END
      SUBROUTINE CONT02_THREE
C
C     HIGHLIGHT EVERY THIRD CONTOUR LINE (RELATIVE TO 550 HPA
C     REFERENCE) BY THICKENING.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     ROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_REFERENCE_LEVEL'              550.0
C      'CONTOUR_LABEL_HEIGHT'                  0.25
C      'CONTOUR_LEVEL_SELECTION_TYPE'    'INTERVAL'
C
      CALL PRESET('CONTOUR_HIGHLIGHT')
      CALL PSETI ('CONTOUR_HIGHLIGHT_FREQUENCY',3)
      CALL PSETI ('CONTOUR_HIGHLIGHT_THICKNESS',4)
C
      CALL PSETC ('TEXT_LINE_2',
     1            'Every Third Contour Line is Highlighted')
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT02_FOUR
C
C     DRAW SELECTED CONTOUR LINES, SPECIFIED IN ARRAY 'RLEV', USING LEVEL
C     LIST PARAMETER.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     ROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_REFERENCE_LEVEL'              550.0
C      'CONTOUR_LABEL_HEIGHT'                  0.25
C      'CONTOUR_HIGHLIGHT_FREQUENCY'              3
C      'CONTOUR_HIGHLIGHT_THICKNESS'              4
C
      PARAMETER (NLEV=15)
      DIMENSION RLEV (NLEV)
      DATA RLEV /600.,595.,590.,580.,570.,565.,550.,545.,540.,535.,
     1 530.,525.,520.,515.,510./
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','LEVEL_LIST')
      CALL PSET1R ('CONTOUR_LEVEL_LIST',RLEV,NLEV)
C
      CALL PSETC ('TEXT_LINE_2',
     1'Contour Levels are selected using CONTOUR_LEVEL_LIST parameter')
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETI ('TEXT_LINE_COUNT',2)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT02_FIVE
C
C     DRAW SELECTED CONTOUR LINES HIGHLIGHTING EVERY SECOND LINE WITH
C     DASHED AND THICKENED LINES. THE SELECTED CONTOUR LEVELS ARE IN
C     THE PREVIOUSLY DEFINED ARRAY 'RLEV'. PLOT ALL POSSIBLE HIGHS
C     AND LOWS.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     ROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_REFERENCE_LEVEL'              550.0
C      'CONTOUR_LABEL_HEIGHT'                  0.25
C      'CONTOUR_LEVEL_SELECTION_TYPE'  'LEVEL_LIST'
C      'CONTOUR_HIGHLIGHT_THICKNESS'              4
C
      CALL PSETC ('CONTOUR_HIGHLIGHT_STYLE','DASH')
      CALL PSETI ('CONTOUR_HIGHLIGHT_FREQUENCY',2)
      CALL PSETR ('CONTOUR_HILO_SUPPRESS_RADIUS',0.0)
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETC ('TEXT_LINE_2',
     1'Every Second Contour is Highlighted with Dashed Line Style ')
      CALL PSETC ('TEXT_LINE_3',
     1'Suppress Radius for HILO is set to 0.0 (Default 15.0)')
      CALL PSETI('TEXT_LINE_COUNT',3)
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE CONT02_SIX
C
C     DRAW HIGHLIGHTED CONTOURS AS SOLID RED LINES AND LABEL THEM WITH
C     NUMBERS AND USER TEXT.
C
C     THE FOLLOWING CONTOURING PARAMETERS ARE STILL ACTIVE FROM PREVIOUS
C     CALLS. ALL OTHER CONTOURING PARAMETERS THAT ARE NOT SET IN THIS
C     ROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'CONTOUR_REFERENCE_LEVEL'              550.0
C      'CONTOUR_LABEL_HEIGHT'                  0.25
C      'CONTOUR_LEVEL_SELECTION_TYPE'  'LEVEL_LIST'
C      'CONTOUR_HIGHLIGHT_THICKNESS'              4
C      'CONTOUR_HIGHLIGHT-FREQUENCY'              2
C      'CONTOUR_HILO_SUPPRESS_RADIUS'           0.0
C
      CALL PRESET('CONTOUR_HIGHLIGHT_STYLE')
      CALL PSETC ('CONTOUR_HIGHLIGHT_COLOUR','RED')
      CALL PSETC ('CONTOUR_LABEL_TYPE','BOTH')
      CALL PSETC ('CONTOUR_LABEL_TEXT','>DM')
C
      CALL PSETC ('TEXT_LINE_1',
     1'Input Field: 500 hPa Geopotential Height on a 1.5 degree grid')
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETC ('TEXT_LINE_2',
     1'Contour Labels Include Text')
      CALL PSETC ('TEXT_LINE_3',
     2'Contours Highlighted with RED Colour')
      CALL PSETI('TEXT_LINE_COUNT',3)
C
C     PLOT THE CONTOURS AND TITLE
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
