      PROGRAM DATA04
C
C     THIS PROGRAM DEMONSTRATES MAGICS INPUT_FIELD FACILITIES.  THE
C     METEOROLOGICAL DATA FIELD WHICH IS IN FILE 2 IS A STANDARD GLOBAL
C     500 HPA MODEL OUTPUT FIELD ON A REGULAR GRID.  THE FIRST ELEMENT
C     OF THE ARRAY 'FIELD'(1,1) IS 0.0 LONGITUDE AND 90.0 LATITUDE WITH
C     A STEP OF 1.5 DEGREES IN LONGITUDE DIRECTION AND -1.5 DEGREES IN
C     LATITUDE DIRECTION.
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
c     CALL PSETR ('PS_SCALE',0.76)
      CALL PSETC ('PS_FILE_NAME','data04.ps')
C
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/500Z.grb')
      CALL PGRIB
C
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/DATA04')
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')           
      CALL PSETC ('MAP_GRID_COLOUR','GREEN')           
C
C     PLOT A GLOBAL FIELD IN CYLINDRICAL PROJECTION
C
      CALL DATA04_ONE
      CALL PNEW ('PAGE')
C
C     PLOT UNPROJECTED INPUT_FIELD
C
      CALL DATA04_TWO
      CALL PNEW ('PAGE')
C
C     PLOT UNPROJECTED INPUT_FIELD WHERE THE FIRST ELEMENT OF THE
C     MATRIX(1,1) IS MAPPED ONTO THE LOWER LEFT CORNER OF THE SUBPAGE
C     (DEFAULT MAPPING IS ONTO THE UPPER LEFT CORNER).
C
      CALL DATA04_THREE
      CALL PNEW ('PAGE')
C
C     PLOT UNPROJECTED, TRANSPOSED INPUT FIELD.  THE FIRST ELEMENT OF
C     THE MATRIX IS MAPPED ONTO THE UPPER LEFT CORNER OF THE SUBPAGE
C     (DEFAULT).  TRANSPOSED MEANS THAT THE FIRST ARRAY INDEX REFERS TO
C     LATITUDE POSITIONS AND THE SECOND INDEX REFERS TO LONGITUDE
C     POSITIONS (DEFAULT IS THE OPPOSITE).
C
      CALL DATA04_FOUR
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END
      SUBROUTINE DATA04_ONE
C
C     THIS SUBROUTINE PLOTS CONTOURS AND COASTLINES IN CYLINDRICAL
C     PROJECTION.  THE DATA IS STORED IN THE ARRAY 'FIELD'. THE
C     PARAMETER INPUT_FIELD_ORGANIZATION IS SET TO 'FITTED' WHICH MEANS
C     THAT THE CONTOUR DATA IS NOT PROJECTED.  COASTLINES (BY DEFAULT)
C     ARE PROJECTED.
C
C     ALL DATA INPUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('INPUT_FIELD_ORGANIZATION','FITTED')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',0.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',-90.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',358.5)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',90.0)
      CALL PSETC ('TEXT_LINE_1',
     1            'Cylindrical '//
     2            '500 hPa Geopotential Height')
      CALL PSETC ('TEXT_LINE_2',
     1            'Contours are Fitted from a Regular Global 1.5'//
     2            ' Degree lat/lon Field')
      CALL PSETC ('TEXT_LINE_3',
     1            'Coastlines are Projected')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE, COASTLINES AND CONTOURS
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE DATA04_TWO
C
C     THIS SUBROUTINE PLOTS CONTOURS FOR THE REGULAR INPUT FIELD.  NO
C     COASTLINES ARE PLOTTED AS SUBPAGE_MAP_PROJECTION IS SET TO 'NONE'.
C
C     THE FOLLOWING DATA INPUT PARAMETER IS STILL ACTIVE FROM A PREVIOUS
C     CALL.  ALL OTHER DATA INPUT PARAMETERS TAKE THEIR DEFAULT VALUES.
C
C     'INPUT_FIELD_ORGANIZATION'                     'FITTED'
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','NONE')
      CALL PSETC ('TEXT_LINE_1','Non-Projected Map ')
      CALL PSETC ('TEXT_LINE_2',
     1            'Contours are Fitted from a Regular Global 1.5'//
     2            ' Degree lat/lon Field')
      CALL PSETC ('TEXT_LINE_3',
     1            'The Parameter INPUT_FIELD_SUBPAGE_MAPPING is'//
     2            ' UPPER_LEFT (Default)')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE AND CONTOURS
C
      CALL PTEXT
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE DATA04_THREE
C
C     THIS SUBROUTINE PLOTS CONTOURS FOR THE REGULAR FIELD WITH NO
C     COASTLINES AND NO CONTOUR PROJECTION.  THE DATA FIELD IS THE SAME
C     AS THAT USED IN THE PREVIOUS TWO EXAMPLES BUT, IN THIS EXAMPLE,
C     THE FIRST ELEMENT OF THE ARRAY 'FIELD'(1,1) IS MAPPED ONTO THE
C     LOWER LEFT HAND CORNER OF THE SUBPAGE. THEREFORE THE CONTOUR FIELD
C     IN THIS EXAMPLE WILL BE UPSIDE DOWN WHEN COMPARED TO THE TWO
C     PREVIOUS EXAMPLES.
C
C     THE FOLLOWING DATA INPUT PARAMETER IS STILL ACTIVE FROM A PREVIOUS
C     CALL.  ALL OTHER DATA INPUT PARAMETERS TAKE THEIR DEFAULT VALUES.
C
C     'INPUT_FIELD_ORGANIZATION'                     'FITTED'
C
      CALL PSETC ('INPUT_FIELD_SUBPAGE_MAPPING','LOWER_LEFT')
      CALL PSETC ('TEXT_LINE_3',
     1            'First Element of the Field is Mapped'//
     2            ' onto the LOWER_LEFT Corner')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE AND CONTOURS
C
      CALL PTEXT
      CALL PCONT
C
      RETURN
      END
      SUBROUTINE DATA04_FOUR
C
C     THIS SUBROUTINE PLOTS CONTOURS FOR THE REGULAR INPUT FIELD.  NO
C     COASTLINES ARE PLOTTED.  THE FIRST ELEMENT OF THE ARRAY
C     'FIELD'(1,1) IS MAPPED ONTO THE UPPER LEFT CORNER AND TRANSPOSED.
C     TRANSPOSED MEANS THAT THE FIRST INDEX OF THE ARRAY REFERS TO
C     LATITUDE AND THE SECOND INDEX TO LONGITUDE, THE DEFAULT BEING THE
C     OPPOSITE.
C
C     THE FOLLOWING DATA INPUT PARAMETER IS STILL ACTIVE FROM A PREVIOUS
C     CALL.  ALL OTHER DATA INPUT PARAMETERS TAKE THEIR DEFAULT VALUES.
C
C     'INPUT_FIELD_ORGANIZATION'                     'FITTED'
C
      CALL PSETC ('INPUT_FIELD_SUBPAGE_MAPPING',
     1            'UPPER_LEFT_TRANSPOSED')
      CALL PSETC ('TEXT_LINE_3',
     1            'Field is Set to be TRANSPOSED and have'//
     2            ' the First Element in the UPPER_LEFT Corner')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE AND CONTOURS
C
      CALL PTEXT
      CALL PCONT
C
      RETURN
      END
