C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM DATA01
C
C     THIS PROGRAM DEMONSTRATES MAGICS DATA INPUT FACILITIES FOR ARRAY
C     INPUT. THE METEOROLOGICAL DATA FIELDS ARE STANDARD GLOBAL
C     500 hPa MODEL OUTPUT FIELD ON A REGULAR 1.5 DEGREE GRID. 
C     CONTOURS AND COASTLINES ARE PROJECTED ONTO A POLAR STEREOGRAPHIC.  
C     MAP. THE INPUT FIELD PARAMETERS ARE SET - EVEN THOUGH THEY ARE 
C     THE DEFAULT VALUES.
C
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
c     CALL PSETR ('PS_SCALE',0.76)    
      CALL PSETC ('PS_FILE_NAME','data01.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/DATA01')
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')           
      CALL PSETC ('MAP_GRID_COLOUR','GREEN')           
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',95.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',35.0)
C
C     SET INPUT FIELD PARAMETERS
C
      CALL PSETR ('INPUT_FIELD_INITIAL_LATITUDE',90.0)             
      CALL PSETR ('INPUT_FIELD_INITIAL_LONGITUDE',0.0)             
      CALL PSETR ('INPUT_FIELD_LATITUDE_STEP',-1.5)                
      CALL PSETR ('INPUT_FIELD_LONGITUDE_STEP',1.5)                
C
C     PLOT CONTOURS
C
      CALL DATA01_ONE
C
C     PLOT WINDS
C
      CALL PNEW ('PAGE')
      CALL DATA01_TWO

      CALL PCLOSE
      END




      SUBROUTINE DATA01_ONE
C
C     INPUT FIELD ON FILE UNIT LUNU IS 500hPa HEIGHT field
C
      PARAMETER (NLON=240, NLAT=121)
      DIMENSION FIELD (NLON,NLAT)
C
C     PLOT CONTOURS USING ARRAY INPUT
C
C     READ THE DATA AND PASS FIELD TO MAGICS
C
      OPEN(UNIT=20,FILE='data/oldts/reg500.bin',
     x FORM='UNFORMATTED',IOSTAT=IOSTAT, STATUS= 'OLD')
      IF(IOSTAT.NE.0)THEN
        WRITE(*,*)'DATA FILE NOT ACCESSIBLE'
        STOP
      ENDIF
      READ (20) FIELD
      
      CALL PSET2R ('INPUT_FIELD',FIELD,NLON,NLAT)
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_2',
     1  'Input Field is a Global 500 hPa Model Output Field ')
      CALL PSETC ('TEXT_LINE_1',
     1  'Data Input Example using ARRAY Input')              
      CALL PSETC ('TEXT_LINE_3',
     1  'Default Values for all Contour Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE, COASTLINES AND CONTOURS
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT

      RETURN
      END




      SUBROUTINE DATA01_TWO
C
C     FIELDS ON FILE UNITS 22 AND 23 ARE 500hPa U AND V COMPONENT FIELDS 
C
      PARAMETER (NLON=240, NLAT=121)
      DIMENSION UFIELD(NLON,NLAT), VFIELD(NLON,NLAT)
C
C     PLOT WIND FIELD USING ARRAY INPUT
C
C     READ THE DATA AND PASS FIELD TO MAGICS
C
      OPEN(UNIT=22,FILE='data/oldts/ucomp.bin',
     x FORM='UNFORMATTED',IOSTAT=IOSTAT, STATUS= 'OLD')
      IF(IOSTAT.NE.0)THEN
        WRITE(*,*)'DATA FILE NOT ACCESSIBLE'
        STOP
      ENDIF
      OPEN(UNIT=23,FILE='data/oldts/vcomp.bin',
     x FORM='UNFORMATTED',IOSTAT=IOSTAT, STATUS= 'OLD')
      IF(IOSTAT.NE.0)THEN
        WRITE(*,*)'DATA FILE NOT ACCESSIBLE'
        STOP
      ENDIF
      READ (22) UFIELD
      READ (23) VFIELD
      CALL PSET2R ('INPUT_WIND_U_COMPONENT',UFIELD,NLON,NLAT)
      CALL PSET2R ('INPUT_WIND_V_COMPONENT',VFIELD,NLON,NLAT)
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_2',
     1  'Input Fields are Global 500 hPa Model Output Fields ')
      CALL PSETC ('TEXT_LINE_1',
     1  'Data Input Example using ARRAY Input')              
      CALL PSETC ('TEXT_LINE_3',
     1  'Default Values for all Wind Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
C     PLOT THE TITLE, COASTLINES AND WIND ARROWSS
C
      CALL PTEXT
      CALL PCOAST
      CALL PWIND

      RETURN
      END
