C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM DATA02
C
C     THIS PROGRAM DEMONSTRATES MAGICS DATA INPUT FACILITIES FOR GRIB
C     INPUT. THE METEOROLOGICAL DATA FIELDS ARE STANDARD GLOBAL
C     500 hPa MODEL OUTPUT FIELD ON A REGULAR 1.5 DEGREE GRID.
C     CONTOURS AND COASTLINES ARE PROJECTED ONTO A POLAR STEREOGRAPHIC.  
C     MAP. 
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
c     CALL PSETR ('PS_SCALE',0.76)
      CALL PSETC ('PS_FILE_NAME','data02.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','TESTS/DATA02')
C
C     DEFINE MAP AREA AND PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',5.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',95.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',35.0)
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')
      CALL PSETC ('MAP_GRID_COLOUR','GREEN')
C
C     SET GRIB FILE ACCESS    
C
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
C
C     PLOT CONTOURS
C
      CALL DATA02_ONE
C
C     PLOT WINDS
C
      CALL PNEW ('PAGE')
      CALL DATA02_TWO
C
C     PLOT TEMPERATURES
C
      CALL PNEW ('PAGE')
      CALL DATA02_THREE

      CALL PCLOSE
      END



      SUBROUTINE DATA02_ONE
C
C     PLOT CONTOURS USING GRIB INPUT
C
C     READ THE GRIB DATA AND SET LOCATION ON FILE
C
      CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/500Z.grb')
      CALL PSETI ('GRIB_FIELD_POSITION',1)
      CALL PGRIB
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1  'Data Input Example using GRIB Input')              
      CALL PSETC ('TEXT_LINE_2',
     1  'Input Field is a Global 500 hPa Model Output Field ')
      CALL PSETC ('TEXT_LINE_3',
     1  'Default Values for all Contour Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',3)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT THE TITLE, COASTLINES AND CONTOURS
C
      CALL PTEXT
      CALL PCOAST
      CALL PCONT

      RETURN
      END




      SUBROUTINE DATA02_TWO
C
C     PLOT WIND FIELD USING GRIB INPUT
C
C     READ THE GRIB DATA AND SET POSITION OF WIND FIELDS
C
      CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/500uv.grb')
      CALL PSETI ('GRIB_WIND_POSITION_1',1)
      CALL PSETI ('GRIB_WIND_POSITION_2',2)
      CALL PGRIB
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1',
     1  'Data Input Example using GRIB Input')              
      CALL PSETC ('TEXT_LINE_2',
     1  'Input Fields are Global 500 hPa Model Output Fields ')
      CALL PSETC ('TEXT_LINE_3',
     1  'Default Values for all Wind Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',3)
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT THE TITLE, COASTLINES AND WIND ARROWSS
C
      CALL PTEXT
      CALL PCOAST
      CALL PWIND

      RETURN
      END




      SUBROUTINE DATA02_THREE
      DIMENSION IB1PAR(550),IB2PAR(550),FIELD(29040)
C
C     DATA ON FILE IS A MARS TARGET FILE CONTAINING 2 FIELDS
C     850 HPA TEMPERATURES FOR 2 ANALYSES
C     THE RESOLUTION OF THE DATA IS 1.5/1.5.
C
C     PLOT THE FIELDS USING PGRIB IN DECODE MODE
C     ONE FIELD PER PAGE
C
      CALL PSETC ('GRIB_MODE','DECODE')
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/850t.grb')
C
C     SET FIELD POSITION ON FILE FOR PGRIB
C     ARRAY 'FIELD' WILL RECEIVE THE DECODED FIELD FROM PGRIB
C     ARRAYS 'IB1PAR' AND 'IB2PAR' RECEIVE PRODUCT AND GRID
C     INFORMATION
C
      CALL PSETI ('GRIB_FIELD_POSITION',1)
      CALL PSET1R ('GRIB_OUTPUT_FIELD',FIELD,29040)
      CALL PSET1I ('GRIB_PRODUCT_BLOCK',IB1PAR,550)
      CALL PSET1I ('GRIB_GRID_BLOCK',IB2PAR,550)
      CALL PGRIB
      CALL PENQI ('GRIB_ERROR_CODE',IERR)
      IF (IERR.NE.0) THEN
         WRITE (*,*) ' ERROR IN PGRIB = ',IERR
      ELSE

C        USER PASSES FIELD RECEIVED FROM PGRIB TO MAGICS FOR
C        CONTOURING. MAGICS INPUT FIELD, CONTOURING AND TEXT
C        PARAMETERS MUST BE SET HERE, IF REQUIRED
C
         NLAT = IB2PAR (3)
         NLON = IB2PAR (2)
         CALL PSET2R ('INPUT_FIELD',FIELD,NLON,NLAT)
         CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
         CALL PSETR ('CONTOUR_INTERVAL',4.0)
C
C        SET TEXT PARAMETERS FOR THE DIFFERENT FIELDS
C
         CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
         CALL PSETI ('TEXT_LINE_COUNT',2)            
         CALL PSETC ('TEXT_LINE_2',
     1      'Example Using PGRIB in DECODE mode')
         CALL PSETC ('TEXT_LINE_1','850 hPa Temperatures'//
     1         ' Forecast T+12  vt: 0000z 19/02/99')
         CALL PCOAST
         CALL PCONT
         CALL PTEXT
      ENDIF

      RETURN
      END
