	PROGRAM DATA06 
C
C	PROGRAM TO DEMONSTRATE INPUT DATA FOR GRAPH PLOTTING
C	THREE SIMPLE EXAMPLES ARE SHOWN:
C	(1) CURVE PLOTTING
C	(2) BAR CHART PLOTTING
C	(2) AREA CURVE PLOTTING
C
 
C
C     OPEN MAGICS
C     -----------
      CALL POPEN 
      
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','data06.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','DATA06') 

C
C     DEFINE PLOT AREA 
C     ----------------
      CALL PSETR ('SUBPAGE_X_LENGTH',22.0) 
      CALL PSETR ('SUBPAGE_Y_LENGTH',17.0)
      CALL PSETC ('SUBPAGE_FRAME','OFF')
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','NONE')
      CALL PSETC ('MAP_COASTLINE_COLOUR','BLACK')      
C	
C     PLOT CURVE
C     ----------
      CALL ONE 
C
C     PLOT BARS
C     ---------
      CALL PNEW('PAGE') 
      CALL TWO 
C
C     PLOT AREA CURVE
C     ---------------
      CALL PNEW('PAGE') 
      CALL THREE 
C
C     CLOSE MAGICS
C     ------------
      CALL PCLOSE 
      STOP 
      END 






      SUBROUTINE ONE
C
C     PLOT SIMPLE CURVE
C
      DIMENSION X(11),Y(11)
C
C     DEFINE CURVE
C
      DATA X /1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0/ 
      DATA Y /1.0,3.0,6.0,8.0,10.0,15.0,20.0,30.0,20.0,10.0,5.0/
C
C     SET UP AXIS SYSTEM - FIRST X AXIS
C
      CALL PSETC ('AXIS_POSITION','BOTTOM')
      CALL PSETC ('AXIS_ORIENTATION','HORIZONTAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',13.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',1.0)
      CALL PAXIS
C
C     Y AXIS
C
      CALL PSETC ('AXIS_POSITION','LEFT')
      CALL PSETC ('AXIS_ORIENTATION','VERTICAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',40.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',5.0)
      CALL PAXIS
C
C     CURVE
C
      CALL PSETC ('GRAPH_TYPE','CURVE')
      CALL PSET1R ('GRAPH_CURVE_X_VALUES',X,11)
      CALL PSET1R ('GRAPH_CURVE_Y_VALUES',Y,11)
      CALL PSETC ('GRAPH_LINE_COLOUR','RED')

      CALL PGRAPH
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','GRAPH plotting in '//
     X' CURVE mode') 
C
C     PLOT TEXT
C
      CALL PTEXT 
      RETURN
      END

      SUBROUTINE TWO 
C
C     PLOT SIMPLE BAR CHART
C
      DIMENSION X(11),YL(11),YU(11)
C
C     DEFINE BARS
C
      DATA X /1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0/ 
      DATA YL /11*0.0/
      DATA YU /3.0,5.0,9.0,1.0,2.0,10.0,9.0,8.0,0.0,3.0,10.0/
C
C     SET UP AXIS SYSTEM - FIRST X AXIS
C
      CALL PSETC ('AXIS_POSITION','BOTTOM')
      CALL PSETC ('AXIS_ORIENTATION','HORIZONTAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',13.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',1.0)
      CALL PAXIS
C
C     Y AXIS
C
      CALL PSETC ('AXIS_POSITION','LEFT')
      CALL PSETC ('AXIS_ORIENTATION','VERTICAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',10.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',1.0)
      CALL PAXIS
C
C     BARS
C
      CALL PSETC ('GRAPH_TYPE','BAR')
      CALL PSET1R ('GRAPH_BAR_X_VALUES',X,11)
      CALL PSET1R ('GRAPH_BAR_Y_LOWER_VALUES',YL,11)
      CALL PSET1R ('GRAPH_BAR_Y_UPPER_VALUES',YU,11)
      CALL PSETC ('GRAPH_SHADE','ON')
      CALL PSETC ('GRAPH_SHADE_STYLE','AREA_FILL')
      CALL PSETC ('GRAPH_SHADE_COLOUR','RED')

      CALL PGRAPH
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','GRAPH plotting in'//
     X' BAR mode') 
C
C     PLOT TEXT
C
      CALL PTEXT 
      RETURN
      END
      SUBROUTINE THREE 
C
C     PLOT SIMPLE AREA CHART
C
      DIMENSION X1(11),Y1(11),X2(11),Y2(11)
C
C     DEFINE TWO CHARTS
C
      DATA X1 /1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0/ 
      DATA Y1 /4.5,5.0,6.0,7.0,9.0,9.5,9.8,8.0,7.0,6.5,5.0/
      DATA X2 /1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0/ 
      DATA Y2 /1.5,2.0,3.0,2.0,1.0,2.5,3.8,6.0,2.0,3.5,4.5/
C
C     SET UP AXIS SYSTEM - FIRST X AXIS
C
      CALL PSETC ('AXIS_POSITION','BOTTOM')
      CALL PSETC ('AXIS_ORIENTATION','HORIZONTAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',13.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',1.0)
      CALL PAXIS
C
C     Y AXIS
C
      CALL PSETC ('AXIS_POSITION','LEFT')
      CALL PSETC ('AXIS_ORIENTATION','VERTICAL')
      CALL PSETR ('AXIS_MIN_VALUE',0.0) 
      CALL PSETR ('AXIS_MAX_VALUE',10.0)
      CALL PSETR ('AXIS_TICK_INTERVAL',1.0)
      CALL PAXIS
C
C     BARS
C
      CALL PSETC ('GRAPH_TYPE','AREA')
      CALL PSET1R ('GRAPH_CURVE_X_VALUES',X1,11)
      CALL PSET1R ('GRAPH_CURVE_Y_VALUES',Y1,11)
      CALL PSET1R ('GRAPH_CURVE2_X_VALUES',X2,11)
      CALL PSET1R ('GRAPH_CURVE2_Y_VALUES',Y2,11)
      CALL PSETC ('GRAPH_SHADE','ON')
      CALL PSETC ('GRAPH_SHADE_STYLE','DOT')
      CALL PSETC ('GRAPH_SHADE_COLOUR','GREEN')

      CALL PGRAPH
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','GRAPH plotting in '//
     X' AREA mode') 
C
C     PLOT TEXT
C
      CALL PTEXT 

      RETURN
      END
