	PROGRAM IMAG07
C

C	PLOT AN IMAGE WITH LAND/SEA SHADING
C
	CALL POPEN
C
C	PASS GRIB FILE WITH IMAGE
C
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','image07.ps')
	CALL PSETR ('SUPER_PAGE_X_LENGTH',29.7)
	CALL PSETR ('SUPER_PAGE_Y_LENGTH',29.7)
	CALL PSETR ('PAGE_X_LENGTH',29.7)
	CALL PSETR ('PAGE_Y_LENGTH',29.7)
	CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/imag07')
	CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
	CALL PSETC ('GRIB_INPUT_FILE_NAME', 
     x  'data/oldts/im96011000.img')
	CALL PSETC('IMAGE_SUBAREA_SELECTION','ON')
	CALL PSETR('SUBPAGE_MAP_CORNER_LATITUDE',80.)
	CALL PSETR('SUBPAGE_MAP_CORNER_LONGITUDE',80.)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',40.)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.)
C
C	SELECT THE PROJECTION (MUST BE DONE BEFORE CALLING PGRIB)
C
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','SATELLITE')
	CALL PGRIB
C
C	SET UP IMAGE COLOUR TABLE - BLACK AND WHITE ONLY
C
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE','ON') 
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE','ON') 
C
C	PLOT THE IMAGE
C
	CALL PSETC ('MAP_COASTLINE_COLOUR','BLACK')
	CALL PSETC ('MAP_GRID_COLOUR','BLACK')
	CALL PCOAST
	CALL PSETC ('TEXT_LINE_1','Example of land/Sea Shading on a'//
     X 'Satellite Projection ')
	CALL PTEXT
C
C	CLOSE MAGICS
C
	CALL PCLOSE
	STOP
	END
