C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

	PROGRAM IMAG03
C
C	PLOT AN IMAGE WITH OVERLAID CONTOURS
C
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','image03.ps')
	CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/imag03')                   
C
C	DEFINE POLAR STEREOGRAPHIC PROJECTION
C
	CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION', 'CENTRE')
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE', -20.0) 
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE', 40.0) 
	CALL PSETR ('SUBPAGE_MAP_SCALE', 35.E6) 
C
C	PASS GRIB FILE WITH IMAGE
C
	CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
	CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/im96011000.img')
	CALL PGRIB
C
C	SET UP IMAGE COLOUR TABLE - BLACK AND WHITE ONLY
C
	CALL PSETC ('IMAGE_MIN_LEVEL_COLOUR','WHITE')
	CALL PSETC ('IMAGE_MAX_LEVEL_COLOUR','BLACK')
	CALL PSETC ('IMAGE_COLOUR_TABLE_CREATION_MODE','EQUIDISTANT')
	CALL PSETC ('IMAGE_LEGEND','ON')
C
C	PLOT THE IMAGE
C
	CALL PIMAGE
	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Satellite Image Overlaid with Contours')
	CALL PTEXT
C
C	PASS GRIB FILE WITH CONTOUR FIELD AND PLOT CONTOURS
C
	CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/msl.grb')
	CALL PGRIB
	CALL PSETC ('CONTOUR_HILO','OFF')
	CALL PCONT
C
C	PLOT COASTLINES AND TITLE
C	
	CALL PSETC ('MAP_COASTLINE_COLOUR','BLACK')
	CALL PSETC ('MAP_GRID_COLOUR','BLACK')
	CALL PCOAST
C
C	CLOSE MAGICS
C
	CALL PCLOSE
	STOP
	END
