	PROGRAM LGND04
C
C	EXAMPLE OF SATELLITE IMAGE LEGEND    
C
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','legend04.ps')
	CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Lgnd04')         
C
C	DEFINE POLAR STEREOGRAPHIC PROJECTION
C
	CALL PSETC ('SUBPAGE_MAP_PROJECTION', 'POLAR_STEREOGRAPHIC')
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION', 'CENTRE')
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE', -20.0) 
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE', 40.0) 
	CALL PSETR ('SUBPAGE_MAP_SCALE', 35.E6) 
C
C	PASS GRIB FILE WITH IMAGE
C
	CALL PSETC ('GRIB_INPUT_TYPE', 'FILE')
	CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/im96011000.img')
	CALL PGRIB
C
C	SET UP IMAGE COLOUR TABLE - BLACK AND WHITE ONLY
C
	CALL PSETC ('IMAGE_MIN_LEVEL_COLOUR','WHITE')
	CALL PSETC ('IMAGE_MAX_LEVEL_COLOUR','BLACK')
	CALL PSETC ('IMAGE_COLOUR_TABLE_CREATION_MODE','EQUIDISTANT')
	CALL PSETC ('IMAGE_LEGEND','ON')
C
C	PLOT THE IMAGE
C
	CALL PIMAGE
	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETC ('TEXT_LINE_1',
     X  'Example of Satellite Image Legend')
	CALL PTEXT
C
C	PLOT COASTLINES AND TITLE
C	
	CALL PSETC ('MAP_COASTLINE_COLOUR','BLACK')
	CALL PSETC ('MAP_GRID_COLOUR','BLACK')
	CALL PCOAST
C
C	CLOSE MAGICS
C
	CALL PCLOSE
	STOP
	END
