C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

	PROGRAM LGND01
C
C	THIS PROGRAM DEMONSTRATES MAGICS LEGEND PLOTTING FEATURES.
C
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','legend01.ps')
C
C	SET COMMON MAGICS PARAMETERS FOR THIS PLOT
C
	CALL PSETC('GRIB_INPUT_TYPE','FILE')
	CALL PSETC('PAGE_ID_LINE_USER_TEXT','Tests/Lgnd01')
	CALL PSETC ('LEGEND','ON')
	CALL PSETC('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
	CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',52.0)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
	CALL PSETR('SUBPAGE_MAP_SCALE',25.0E6)
C
C	DISPLAY ISOTACHS AND WIND_ARROWS IN NORTHERN HEMISPHERE.  PLOT
C	LEGENDS INTO DEFAULT AREA
C
	CALL LGND01_ONE
	CALL PNEW('PAGE')
C
C	DISPLAY ISOTACHS AND 500 hPa FIELD WITH WIND FLAGS ON THE
C	SELECTED POLAR STEREOGRAPHIC AREA.  PLOT LEGENDS INTO USER DEFINED
C	AREA WITH USER'S TEXT FOR EACH ENTRY.
C
	CALL LGND01_TWO
	CALL PNEW('PAGE')
C
C	DISPLAY ISOTACHS WITH THE WIND_ARROWS AND ISOTACHS ON
C	THE EUROPEAN AREA.  PLOT LEGENDS IN THREE COLUMNS.
C
	CALL LGND01_THREE
C
C	CLOSE MAGICS
C
	CALL PCLOSE
C
	END
	SUBROUTINE LGND01_ONE
C
C	THIS SUBROUTINE PLOTS WIND ARROWS AND ISOTACHS ON THE
C	NORTHERN HEMISPHERE. LEGEND ENTRIES ARE GENERATED IN EACH
C	ACTION ROUTINES THAT IS CALLED.
C
C	ISOTACH LEVELS HIGHER THAN 25 M/S ARE CONTOURED AND SHADED.
C
C	ALL LEGEND PARAMETERS NOT SET IN THIS SUBROUTINE TAKE
C	THEIR DEFAULT VALUES.
C
	CALL PSETR('WIND_THINNING_FACTOR',8.0)
	CALL PSETC('WIND_ARROW_LEGEND','OFF')
C	CALL PSETI('WIND_ARROW_HEAD_INDEX',23)
C	CALL PSETI('WIND_ARROW_THICKNESS',3)
C
C	PLOT COASTLINES, ISOTACHS AND WIND_ARROWS
C
	CALL PCOAST
	CALL PSETC('GRIB_INPUT_FILE_NAME','data/oldts/500uv.grb')
	CALL PSETI('GRIB_WIND_POSITION_1',1)
	CALL PSETI('GRIB_WIND_POSITION_2',2)
	CALL PGRIB
	CALL PSETC('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
	CALL PSETR('CONTOUR_INTERVAL',5.0)
	CALL PSETR('CONTOUR_MIN_LEVEL',25.0)
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL',25.0)
	CALL PSETR('CONTOUR_SHADE_MAX_LEVEL_DENSITY',200.0)
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL_DENSITY',20.0)
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PSETC('CONTOUR_HILO','OFF')
	CALL PSETC('CONTOUR_HIGHLIGHT','OFF')
	CALL PCONT
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','NORMAL')
	CALL PWIND
C
C	PLOT TEXT
C
	CALL PSETC('TEXT_LINE_1',
     1       'Polar Stereographic 500 hPa Wind Arrows and Isotachs')
	CALL PSETC('TEXT_LINE_2',
     2       'Legend Plotted in Default Position - No Legend Title')
	CALL PSETI('TEXT_LINE_COUNT',2)
	CALL PSETC('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETR('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
	CALL PTEXT
	RETURN
	END
	SUBROUTINE LGND01_TWO
C
C	PLOT LEGEND WITH USER-POSITIONED BOX
C
	CALL PSETC('WIND_FIELD_TYPE','FLAGS')
	CALL PSETI('WIND_FLAG_THICKNESS',2)
	CALL PSETR('WIND_THINNING_FACTOR',15.0)
	CALL PSETR('WIND_FLAG_LENGTH',0.7)
C
	CALL PSETR('LEGEND_BOX_X_POSITION',0.5)
	CALL PSETR('LEGEND_BOX_Y_POSITION',5.9)
	CALL PSETR('LEGEND_BOX_X_LENGTH',4.5)
	CALL PSETR('LEGEND_BOX_Y_LENGTH',8.0)
	CALL PSETC('LEGEND_BOX_BLANKING','ON')
	CALL PSETC('LEGEND_BOX_MODE','POSITIONAL')
	CALL PSETC('LEGEND_BORDER','ON')
	CALL PSETC('LEGEND_TITLE','ON')
C
	CALL PCOAST

	CALL PSETC('TEXT_LINE_1','Polar Stereographic 500 hPa Wind '//
     2  '(Isotachs / Wind Flags) and 500 hPa Z Field ')
	CALL PSETC('TEXT_LINE_2','Legend Plotted in User Positioned Box'//
     2  ' - Default Legend Title - Contour Legend Suppressed')
	CALL PSETI('TEXT_LINE_COUNT',2)
	CALL PTEXT
C
  	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PCONT

	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','NORMAL')
C
C	SET LEGEND USER TEXT
C
	CALL PSETC('LEGEND_USER_TEXT','8 - 12 knots')
	CALL PSETC('LEGEND_TEXT_COMPOSITION','USER_TEXT_ONLY')
	CALL PWIND

	CALL PSETC('GRIB_INPUT_FILE_NAME','data/oldts/500Z.grb')
	CALL PGRIB

	CALL PSETC('CONTOUR','ON')
	CALL PSETC('LEGEND','OFF')
	CALL PSETC('CONTOUR_HILO','OFF')
	CALL PCONT

	RETURN
	END
	SUBROUTINE LGND01_THREE
C
C	LEGEND IS PLOTTED IN USER POSITIONED BOX, IN THREE COLUMNS.
C
	CALL PSETC('GRIB_INPUT_FILE_NAME','data/oldts/500uv.grb')
	CALL PSETI('GRIB_WIND_POSITION_1',1)
	CALL PSETI('GRIB_WIND_POSITION_2',2)
	CALL PGRIB
	CALL PSETC('LEGEND','ON')
	CALL PSETR('CONTOUR_INTERVAL',5.0)
	CALL PSETR('CONTOUR_MIN_LEVEL',20.0)
	CALL PSETR('CONTOUR_SHADE_MAX_LEVEL_DENSITY',600.0)
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL_DENSITY',40.0)
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL',20.0)
C
	CALL PSETC('WIND_FIELD_TYPE','ARROWS')
	CALL PSETI('WIND_ARROW_THICKNESS',2)
	CALL PSETR('WIND_THINNING_FACTOR',6.0)
	CALL PSETC('LEGEND_BOX_MODE','POSITIONAL')
	CALL PSETR('LEGEND_BOX_X_POSITION',10.1)
	CALL PSETR('LEGEND_BOX_Y_POSITION',1.0)
	CALL PSETR('LEGEND_BOX_X_LENGTH',9.5)
	CALL PSETR('LEGEND_BOX_Y_LENGTH',2.5)
	CALL PSETC('LEGEND_TITLE','ON')
	CALL PSETI('LEGEND_COLUMN_COUNT',3)
	CALL PSETC('LEGEND_TEXT_FORMAT','(I3)')
	CALL PSETC('TEXT_CHARACTER_2','\QLH\500 hPa Wind'//
     1   ' and Heights')
	CALL PSETC('LEGEND_TITLE_TEXT','@TEXT_CHARACTER_2@')
C
	CALL PSETC('TEXT_LINE_1',
     1  'Polar Stereographic 500 hPa Wind: Arrows, Isotachs')
	CALL PSETC('TEXT_LINE_2',' Legend Plotted in Three Columns - '//
     4      'User Legend Title - Wind Arrow Legend Suppressed')
C
C	SUPPRESS LEGEND ENTRY FOR WIND
C
	CALL PSETC('LEGEND_ENTRY','OFF')
	CALL PWIND
	CALL PCOAST
C
C	ACTIVATE LEGEND ENTRY
C
	CALL PSETC('LEGEND_ENTRY','ON')
	CALL PSETC('LEGEND_TEXT_COMPOSITION','BOTH')
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PCONT
	CALL PSETC('TEXT_JUSTIFICATION','CENTRE')
	CALL PTEXT
	RETURN
	END
