C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

	PROGRAM LGND03
C
C	THIS PROGRAM SHOWS AN EXAMPLES OF ANALYSIS FEEDBACK LEGEND   
C
	CHARACTER*5 CLIST(1)
	DATA CLIST /'TEMP'/
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','legend03.ps')
	CALL PSETC('PAGE_ID_LINE_USER_TEXT','Tests/lgnd03')
C
C	SET UP MAPPING PARAMETERS
C
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
	CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
	CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)
C
C	SET OBSERVATION INPUT FILE
C
	CALL PSETC ('OBS_INPUT_FILE_NAME',
     x 'data/oldts/obs991108_vsns_fb.bfr')
	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETC ('OBS_FB_LEGEND','ON')
C	CALL PSETC ('OBS_FB_ERROR_FLAG0_COLOUR','BLACK')
C	CALL PSETC ('OBS_FB_ERROR_FLAG1_COLOUR','BLACK')
C	CALL PSETC ('OBS_FB_ERROR_FLAG2_COLOUR','BLACK')
C	CALL PSETC ('OBS_FB_ERROR_FLAG3_COLOUR','BLACK')
	CALL PSETC ('MAP_COASTLINE_STYLE','DOT')
C
C	SELECT THE REQUIRED OBSERVATION OPTIONS
C
	CALL PSETC ('OBS_FB','4DVAR')
	CALL PSETC ('OBS_FB_TYPE','ALL')
C
C	PLOT ONLY TEMP REPORTS AT 700 hPa
C
	CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
	CALL PSETI ('OBS_FB_LEVEL',700)
	CALL POBS
C
C	PLOT COASTLINES AND TEXT
C
	CALL PCOAST
	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETC ('TEXT_LINE_1',
     X'Example of Analysis Feedback Legend')
	CALL PTEXT
C
C	CLOSE MAGICS
C
	CALL PCLOSE
C
	STOP
	END
