C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM OBS03   
C
C     THIS PROGRAM GIVES EXAMPLES OF ANALYSIS FEEDBACK PLOTTING
C     OF OBSERVATIONS. THE DATA FILE 'obs20030912_fb.bfr' CONTAINS VARIOUS
C     OBSERVATION TYPES.
C
C     INITIALIZE MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','obs03.ps')
      CALL PSETC('PAGE_ID_LINE_USER_TEXT','Tests/obs03')
C
C     SET UP MAPPING PARAMETERS
C     SELECTED AREA IS POLAR STEREOGRAPHIC PROJECTION
C
c     CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)
      CALL PSETC ('MAP_COASTLINE_COLOUR', 'RED')
      CALL PSETC ('MAP_COASTLINE_STYLE', 'DOT')
      CALL PSETC ('MAP_GRID_COLOUR', 'RED')
C
C     SET OBSERVATION INPUT FILE
C
      CALL PSETC ('OBS_INPUT_FILE_NAME',
     x            'data/oldts/obs20030912_fb.bfr')

      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT REJECTED TEMP REPORTS                  
C
      CALL FDB01
      CALL PNEW('PAGE')
C
C     PLOT REJECTED SYNOP REPORTS WITH STATION IDENTIFICATION
C
      CALL FDB02
      CALL PNEW('PAGE')
C
C     PLOT REJECTED VARIABLES FOR SYNOP ONLY            
C
      CALL FDB03
      CALL PNEW('PAGE')
C
C     PLOT REJECTED VARIABLES FOR TEMPS ONLY            
C     SOURCE OF REJECTION = FG  (FIRST GUESS)           
C
      CALL FDB04
      CALL PNEW('PAGE')
C
C     PLOT REJECTED VARIABLES FOR TEMPS ONLY            
C     PRESSURE PLOTTED (OTHER VARIABLES TURNED OFF)     
C
      CALL FDB05
      CALL PNEW('PAGE')
C
C     PLOT REJECTED VARIABLES FOR TOVS
C
      CALL FDB06
C
C     CLOSE MAGICS
C
998   CALL PCLOSE
C
      END





      SUBROUTINE FDB01
      CHARACTER*5 CLIST(1)
      DATA CLIST /'TEMP'/
C
C     TEMP REPORTS ONLY
C     DEFAULT VALUES ARE USED FOR ALL FEEDBACK PARAMETERS EXCEPT
C     OBS_FB = 4DVAR  AND OBS_FB_PRESSURE = 'ON'.
C     REJECT_REPORT IS THE DEFAULT VALUE OF OBS_FB_TYPE
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_PRESSURE','ON')
      CALL PSETC ('OBS_FB_ERROR_FLAG0_COLOUR','BLACK')
      CALL PSETC ('OBS_FB_ERROR_FLAG1_COLOUR','BLACK')
      CALL PSETC ('OBS_FB_ERROR_FLAG2_COLOUR','BLACK')
      CALL PSETC ('OBS_FB_ERROR_FLAG3_COLOUR','BLACK')
C
C     SET TOLERANCE LEVELS TO ENSURE ALL LEVELS ARE SEARCHED
C
      CALL PSETI ('OBS_FB_LEVEL',500)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_BELOW',600)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',499)
C
C     PLOT ONLY TEMP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X 'Rejected REPORTS for TEMP Observations')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET('OBS_FB_LEVEL')
      CALL PRESET('OBS_FB_LEVEL_TOLERANCE_BELOW')
      CALL PRESET('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      RETURN
      END




      SUBROUTINE FDB02
      CHARACTER*5 CLIST(1)
      DATA CLIST /'SYNOP'/
C
C     SYNOP REPORTS ONLY
C     OBS_FB_TYPE = REJECT_REPORT
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','REJECT_REPORT')
      CALL PSETC ('OBS_IDENTIFICATION','ON')
C
C     TURN THE LEGEND ON
C
      CALL PSETC('OBS_FB_LEGEND','ON')
C
C     PLOT ONLY SURFACE REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X'Rejected REPORTS for SYNOP Observations with '//
     X'Station Identification')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB')
      CALL PRESET ('OBS_FB_TYPE')
      CALL PRESET ('OBS_FB_PRESSURE')
      CALL PRESET ('OBS_IDENTIFICATION')
      CALL PRESET ('OBS_FB_LEGEND')
      RETURN
      END




      SUBROUTINE FDB03

      CHARACTER*5 CLIST(1)
      DATA CLIST /'SYNOP'/
C
C     SYNOP REPORTS ONLY         
C     FB_TYPE = REJECT_VARIABLES
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','REJECT_VARIABLES')
      CALL PSETC ('OBS_IDENTIFICATION','ON')
C
C     TURN THE LEGEND ON
C
      CALL PSETC ('OBS_FB_LEGEND','ON')
C
C     PLOT ONLY SYNOP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X'Rejected VARIABLES for SYNOP Observations with '//
     X'Station Identification')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_IDENTIFICATION')
      RETURN
      END




      SUBROUTINE FDB04

      CHARACTER*5 CLIST(1)
      DATA CLIST /'TEMP'/
C
C     PLOT TEMPS ONLY            
C     FB_TYPE = REJECTED_VARIABLES
C     SOURCE OF REJECTION = FG
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','REJECT_VARIABLES')
      CALL PSETC ('OBS_FB_SOURCE_TYPE','FG')
      CALL PSETI ('OBS_FB_LEVEL',100)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',99)
      CALL PSETC ('OBS_FB_LEGEND','ON')
C
C     PLOT ONLY TEMP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X'Rejected VARIABLES for TEMP Observations - '//
     X'Source of Rejection = FG')
      CALL PSETC('TEXT_LINE_2',' Temps Above 100 hPa only')
      CALL PSETI('TEXT_LINE_COUNT',2)
      CALL PTEXT
      CALL PSETI('TEXT_LINE_COUNT',1)
      CALL PCOAST
      CALL PRESET ('OBS_FB_SOURCE_TYPE')
      CALL PRESET ('OBS_FB_LEVEL')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      RETURN
      END




      SUBROUTINE FDB05

      CHARACTER*5 CLIST(1)
      DATA CLIST /'TEMP'/
C
C     PLOT TEMPS ONLY
C     PRESSURE TURNED ON
C     TEMPERATURE, HEIGHT, HUMIDITY TURNED OFF
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','REJECT_VARIABLES')
      CALL PSETC ('OBS_FB_TEMPERATURE','OFF')
      CALL PSETC ('OBS_FB_HEIGHT','OFF')
      CALL PSETC ('OBS_FB_RELATIVE_HUMIDITY','OFF')
      CALL PSETC ('OBS_FB_SPECIFIC_HUMIDITY','OFF')
      CALL PSETC ('OBS_FB_PRESSURE','ON')
      CALL PSETC ('OBS_FB_LEGEND','ON')
      CALL PSETI ('OBS_FB_LEVEL',500)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_BELOW',600)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',499)
C
C     PLOT ONLY TEMP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X'Rejected VARIABLES for TEMP Observations - Wind Only - '//
     X'Pressure turned ON')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB_TEMPERATURE')
      CALL PRESET ('OBS_FB_HEIGHT')
      CALL PRESET ('OBS_FB_RELATIVE_HUMIDITY')
      CALL PRESET ('OBS_FB_SPECIFIC_HUMIDITY')
      CALL PRESET ('OBS_FB_PRESSURE')
      CALL PRESET ('OBS_FB_LEVEL')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_BELOW')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      CALL PRESET ('OBS_TYPE_LIST')
      RETURN
      END




      SUBROUTINE FDB06

      DIMENSION ILIST(1)
      DATA ILIST /55/
C
C     SET THE INPUT FILE THAT CONTAINS ATOVS DATA
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/atovs_fb.bfr')
C
C     PLOT TOVS ONLY (CODE TYPE 55)
C     FB TYPE = REJECTED_VARIABLES
C
C     NOTE THAT WE MUST SET 'OBS_FB_RADIANCES' 'ON' IN ORDER TO VIEW THE DATA
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','REJECT_VARIABLES')
      CALL PSETC ('OBS_FB_RADIANCES', 'ON')
      CALL PSETC ('OBS_FB_RADIANCES_TYPE', '4DVAR')
      CALL PSETI ('OBS_FB_LEVEL',  700)
      CALL PSETI ('OBS_FB_LEVEL_2',500)
      CALL PSETC ('OBS_FB_LEGEND','ON')
      
C
C     PLOT ONLY HIGH RESOLUTION TOVS REPORTS
C
      CALL PSET1I ('OBS_CODE_TYPE_LIST',ILIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X'Rejected VARIABLES for TOVS Observations - '//
     X'700/500 level')
      CALL PTEXT
      CALL PCOAST
      RETURN
      END
