      PROGRAM OBS02 
C
C     THIS PROGRAM GIVES EXAMPLES OF OBSERVATION PLOTTING USING
C     THE OPTIONS AVAILABLE.
C
C
C     INITIALIZE MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','obs02.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Obs02')
C
C     SET UP MAPPING PARAMETERS
C     SELECTED AREA IS POLAR STEREOGRAPHIC PROJECTION
C
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)
      CALL PSETC ('MAP_COASTLINE_COLOUR','RED')
      CALL PSETC ('MAP_GRID_COLOUR','RED')
      CALL PSETC ('MAP_COASTLINE_STYLE','DOT')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
C
C     PLOT TEMPS - POSITIONS OF OBSERVATIONS ONLY
C
      CALL TEMPOS
      CALL PNEW('PAGE')
C
C     PLOT TEMPS - SELECTED BY STATION IDENTIFIER
C
      CALL TEMSEL
      CALL PNEW('PAGE')
C
C     PLOT SYNOPS - SHIPS ONLY - SELECTED BY CODE TYPE
C
      CALL SHIP
      CALL PNEW('PAGE')
C
C     PLOT SATEMS - SELECTED SATELLITE BY NUMBER
C
      CALL SATSEL
      CALL PNEW('PAGE')
C
C     PLOT TEMPS WITH THERMAL WINDS
C
      CALL THERML
      CALL PNEW('PAGE')
C
C     PLOT SOIL TEMPERATURES
C
      CALL SOILT
      CALL PNEW('PAGE')
C
C     PLOT SHIP WAVES 
C
      CALL WAVES
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END




      SUBROUTINE TEMPOS
C
C     PLOT TEMP OBSERVATIONS - POSITIONS ONLY WITH
C     STATION IDENTIFICATION.
C
C     SET DISTANCE BETWEEN OBSERVATIONS TO 0.5CM
C
C     ARRAY 'ICOD' HOLDS THE LIST OF OBSERVATION CODE TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE ONLY TEMPS TO BE
C     PLOTTED (CODE TYPES 101 AND 102)
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      DIMENSION ICOD(2)
      DATA ICOD /101,102/
C
C     SET OBSERVATION OPTIONS
C
      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/vsns.bfr')
      CALL PSETR  ('OBS_DISTANCE_APART',0.5)
      CALL PSETC  ('OBS_POSITION_ONLY','ON')
      CALL PSETC  ('OBS_IDENTIFICATION','ON')
      CALL PSET1I ('OBS_CODE_TYPE_LIST',ICOD,2)
C
C     SET UP TEXT
C
      CALL PSETC('TEXT_LINE_1','TEMP Observations - Positions Only')
      CALL PSETC('TEXT_LINE_2',
     1  'Station Identifiers Plotted and Distance Apart is 0.5cm')
      CALL PSETI('TEXT_LINE_COUNT',2)
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION OPTIONS USED IN THIS ROUTINE
C
      CALL PRESET('OBS_DISTANCE_APART')
      CALL PRESET('OBS_POSITION_ONLY')
      CALL PRESET('OBS_IDENTIFICATION')
      CALL PRESET('OBS_CODE_TYPE_LIST')
      CALL PRESET('OBS_IDENTIFICATION')
C
      RETURN
      END




      SUBROUTINE TEMSEL
C
C     PLOT TEMP OBSERVATIONS - SELECTED BY STATION IDENTIFIERS
C
C     ARRAY 'IDEN' HOLDS THE LIST OF IDENTIFIERS TO BE PLOTTED
C
C     THE DERIVED VALUE OF POTENTIAL TEMPERATURE IS PLOTTED
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE ONLY TEMPS TO
C     BE PLOTTED
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS,IDEN
      DIMENSION ILIS(1),IDEN(11)
      DATA ILIS /'TEMP'/
C      DATA IDEN /'08160','03501','10304','04018','60155','02836',
C     1           '11035','37054','27459','17130','16716'/
      DATA IDEN /'10304','08160','10304','04018','60155','02836',
     1           '11035','37054','27459','17130','16716'/
C
C
C      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/obs991108_vsns_fb.bfr')
      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/vsns.bfr')

C
C     PASS THE ARRAYS CONTAINING THE CODE TYPES AND THE STATION
C     IDENTIFIERS
C     SET THETA TO 'ON' AND THETA_TYPE TO POTENTIAL TEMPERATURE
C
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSET1C('OBS_IDENTIFIER_LIST',IDEN,11)
      CALL PSETC ('OBS_THETA','ON')
      CALL PSETC ('OBS_THETA_TYPE','POTENTIAL_TEMPERATURE')
      CALL PSETR ('OBS_DISTANCE_APART',0.0)
      CALL PSETC ('OBS_IDENTIFICATION','ON')
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1',
     1           'TEMPS Selected by Station Identifier')
      CALL PSETC('TEXT_LINE_2',
     2           ' Potential Temperature is Plotted')
C
C     PLOT COASTLINE, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET('OBS_TYPE_LIST')
      CALL PRESET('OBS_IDENTIFIER_LIST')
      CALL PRESET('OBS_THETA')
      CALL PRESET('OBS_THETA_TYPE')
      CALL PRESET('OBS_DISTANCE_APART')
      CALL PRESET('OBS_IDENTIFICATION')
C
      RETURN
      END





      SUBROUTINE SHIP
C
C     PLOT SURFACE SHIP OBSERVATIONS ONLY.
C
C     TO PLOT SURFACE SHIP OBSERVATIONS ONLY - THE OBSERVATION TYPE
C     IS SET TO 'SYNOP' AND THE CODE TYPE TO BE PLOTTED IS SET
C     TO 11 (CODE TYPE FOR SHIPS)
C
C     ARRAY 'ICT' HOLDS THE LIST OF CODE TYPES TO BE PLOTTED. ONLY ONE
C     IN THIS CASE (11)
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE ONLY SYNOPS TO
C     BE PLOTTED
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1),ICT(1)
      DATA ILIS /'SYNOP'/
      DATA ICT /11/

      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/ss.bfr')

C
C     PASS ARRAYS CONTAINING OBSERVATION TYPE AND CODE TYPE
C
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSET1I('OBS_CODE_TYPE_LIST',ICT,1)
      CALL PSETR ('OBS_DISTANCE_APART',2.0)
C
C     CHANGE THE MAP AREA
C
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',0.0)
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1','SYNOPS - Ships Only')  
      CALL PSETC('TEXT_LINE_2','Map Area is Changed')  
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
      CALL PRESET('OBS_TYPE_LIST')
      CALL PRESET('OBS_CODE_TYPE_LIST')
      CALL PRESET('OBS_DISTANCE_APART')
C
      RETURN
      END





      SUBROUTINE SATSEL
C
C     PLOT SATEMS - SELECTED SATELLITE ONLY (NOAA9 IN THIS CASE)
C
C     ARRAY 'ICT' HOLDS LIST OF CODE TYPES (ONLY 85 IN THIS CASE)
C     ARRAY 'ISAT' HOLDS LIST OF SATELLITE NUMBERS (37,38 IN THIS CASE)
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE ONLY SATOBS TO
C     BE PLOTTED
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1),ICT(1)
      DATA ILIS /'SATOB'/
      DATA ICT /85/
C
C     PASS THE ARRAYS CONTAINING OBSERVATION TYPE, CODE TYPE
C     AND SATELLITE NUMBER
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/sls.bfr')
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSET1I('OBS_CODE_TYPE_LIST',ICT,1)
      CALL PSETC ('OBS_IDENTIFICATION_TYPE','CODE_TYPE')
      CALL PSETC ('OBS_IDENTIFICATION','ON')
      CALL PSETI ('OBS_LEVEL',850)
      CALL PSETI ('OBS_LEVEL_TOLERANCE',100)
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1',
     X  'Satellite (SATOB) Selected by Type and Code Type')
      CALL PSETC('TEXT_LINE_2',
     X  'Station Identifier is Plotted')                   
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET('OBS_TYPE_LIST')
      CALL PRESET('OBS_CODE_TYPE_LIST')
      CALL PRESET('OBS_SATELLITE_NUMBER_LIST')
      CALL PRESET('OBS_PRESSURE')
      CALL PRESET('OBS_IDENTIFICATION_TYPE')
      CALL PRESET('OBS_IDENTIFICATION')
      CALL PRESET('OBS_LEVEL')
      CALL PRESET('OBS_LEVEL_TOLERANCE')
C
      RETURN
      END





      SUBROUTINE THERML
C
C     PLOT TEMPS WITH THERMAL WIND
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE TEMPS AND PILOTS TO
C     BE PLOTTED
C
C     TEMPERATURE AND DEWPOINT ARE TURNED 'OFF'
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'TEMP'/
C
C     PASS THE ARRAY CONTAINING OBSERVATION TYPE 
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/vsns.bfr')
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSETC ('OBS_THERMAL_WIND','ON')
      CALL PSETC ('OBS_THERMAL_WIND_LINE_STYLE','DOT')
      CALL PSETI ('OBS_LEVEL',500)
      CALL PSETI ('OBS_LEVEL_2',1000)
      CALL PSETC ('OBS_TEMPERATURE','OFF')
      CALL PSETC ('OBS_DEWPOINT','OFF')
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1', 'TEMPS with Thermal Wind')
      CALL PSETC('TEXT_LINE_2', 'Temperature and Dewpoint turned OFF')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET('OBS_INPUT_FILE_NAME')
      CALL PRESET('OBS_TYPE_LIST')
      CALL PRESET('OBS_THERMAL_WIND')
      CALL PRESET('OBS_THERMAL_WIND_LINE_STYLE')
      CALL PRESET('OBS_LEVEL')
      CALL PRESET('OBS_LEVEL_2')
      CALL PRESET('OBS_TEMPERATURE')
      CALL PRESET('OBS_DEWPOINT')
C
      RETURN
      END





      SUBROUTINE SOILT
C
C     PLOT TEMPS AND PILOTS
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE
C     PLOTTED IN CHARACTER FORM. IN THIS CASE ONLY SOIL TEMPERATURES
C     TO BE PLOTTED
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'SOILT'/
C
C     MOVE TO NEW MAP AREA
C
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',10.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',10.E6)
C
C     PASS THE SOIL TEMPERATURE INPUT DATA                         
C
      CALL PSETC ('OBS_INPUT_FILE_NAME','data/oldts/soil.bfr')
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSETR ('OBS_DISTANCE_APART',1.5)
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1', 'Soil Temperatures')
      CALL PSETC('TEXT_LINE_2', 'Distance Apart set to 1.5cm')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET('OBS_INPUT_FILE_NAME')
      CALL PRESET('OBS_TYPE_LIST')
      CALL PRESET('OBS_DISTANCE_APART')
 
      RETURN
      END




      SUBROUTINE WAVES
C
C     PLOT SURFACE SHIP WAVE OBSERVATIONS ONLY.
C
C     THE INPUT DATA FILE MUST CONTAIN PART 2 OF SHIP REPORTS.
C
C     TO PLOT SHIP WAVE OBSERVATIONS ONLY - THE OBSERVATION TYPE
C     IS SET TO 'SYNOP' AND ARRAY ICT HOLDS THE LIST OF CODE TYPES
C     TO BE PLOTTED, IN THIS CASE CODE TYPES 12 AND 14.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1),ICT(2)
      DATA ILIS /'SYNOP'/
      DATA ICT /12,14/    
C
C     SET OBSERVATION INPUT FILE - PART 2 OF SHIP OBSERVATIONS
C
      CALL PSETC ('OBS_INPUT_TYPE','FILE')
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/ss2.bfr')
C
C     PASS ARRAYS CONTAINING OBSERVATION TYPE AND CODE TYPE
C
      CALL PSET1C('OBS_TYPE_LIST',ILIS,1)
      CALL PSET1I('OBS_CODE_TYPE_LIST',ICT,2)
      CALL PSETC ('OBS_WAVES','ON')                
C
C     CHANGE THE MAP AREA
C
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',-40.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE', 50.E6)
C
C     SET TEXT
C
      CALL PSETC('TEXT_LINE_1','Ship Wave Observations')
      CALL PSETI('TEXT_LINE_COUNT',1)
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
      RETURN
      END
