C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM OBS04
C
C     THIS PROGRAM GIVES EXAMPLES OF ANALYSIS FEEDBACK PLOTTING
C     OF OBSERVATIONS. THE DATA FILE 'osb04.bfr' CONTAINS 
C     OBSERVATION TYPES "SS","T","PA","AIR".
C
C     INITIALIZE MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','obs04.ps')
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Obs04') 
C
C     SET UP MAPPING PARAMETERS
C     SELECTED AREA IS POLAR STEREOGRAPHIC PROJECTION
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)
      CALL PSETR ('SUBPAGE_Y_LENGTH',17.0)   
C
C     SET OBSERVATION INPUT FILE
C
      CALL PSETC ('OBS_INPUT_FILE_NAME',
     x            'data/oldts/obs20030912_fb.bfr')
      CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
      CALL PSETC ('OBS_FB_LEGEND','ON')         
c     CALL PSETC ('OBS_FB_ERROR_FLAG0_COLOUR','BLACK')
c     CALL PSETC ('OBS_FB_ERROR_FLAG1_COLOUR','BLACK')
c     CALL PSETC ('OBS_FB_ERROR_FLAG2_COLOUR','BLACK')
c     CALL PSETC ('OBS_FB_ERROR_FLAG3_COLOUR','BLACK')
      CALL PSETC ('MAP_COASTLINE_COLOUR', 'AVOCADO')
      CALL PSETC ('MAP_COASTLINE_STYLE','DOT')  
      CALL PSETC ('MAP_GRID_COLOUR', 'AVOCADO')
C
C     PLOT BLACKLISTED SYNOP REPORTS
C
      CALL FDB01
      CALL PNEW ('PAGE')
C
C     PLOT BLACKLISTED SYNOP VARIABLES
C
      CALL FDB02
      CALL PNEW('PAGE')
C
C     PLOT SYNOP VARIABLES FLAGGED BUT USED IN THE ANALYSIS
C
      CALL FDB03
      CALL PNEW('PAGE')
C
C     PLOT AIREP VARIABLES USED IN THE ANALYSIS
C
      CALL FDB04
      CALL PNEW('PAGE')
C
C     PLOT PAOB VARIABLES USED IN THE ANALYSIS
C
      CALL FDB05
      CALL PNEW('PAGE')
C
C     PLOT AIREP VARIABLES NOT USED IN THE ANALYSIS
C
      CALL FDB06
      CALL PNEW('PAGE')
C
C     PLOT DEPARTURE VALUES OF TEMP VARIABLES USED 
C     IN THE ANALYSIS
C
      CALL FDB07
      CALL PNEW('PAGE')
C
C     PLOT ALL TEMP VARIABLES WHETHER REJECTED OR NOT -
C     USED OR NOT
C
      CALL FDB08
 
C     CLOSE MAGICS
C
998   CALL PCLOSE
C
      END




      SUBROUTINE FDB01

      CHARACTER*5 CLIST(1)
      DATA CLIST /'SYNOP'/
C
C     BLACKLISTED SYNOP REPORTS    
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','BLACKLIST_REPORT')
C
C     PLOT ONLY SYNOP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1','BLACKLISTED SYNOP Reports')
      CALL PTEXT
      CALL PCOAST
      RETURN
      END
      
      
      SUBROUTINE FDB02
      CHARACTER*5 CLIST(1)
      DATA CLIST /'SYNOP'/
C
C     BLACKLISTED VARIABLES FOR SYNOPS
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','BLACKLIST_VARIABLES')
C
C     PLOT ONLY SYNOP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1','BLACKLISTED SYNOP Variables')
      CALL PTEXT
      CALL PCOAST
      END




      SUBROUTINE FDB03

      CHARACTER*5 CLIST(1)
      DATA CLIST /'SYNOP'/
C
C     SELECT THE REQUIRED OPTIONS
C
      CALL PSETC ('OBS_FB', '4DVAR')
      CALL PSETC ('OBS_FB_TYPE', 'FLAGGED_BUT_USED')
      CALL PSETC ('OBS_FB_LEGEND','ON')
      CALL PSETI ('OBS_FB_LEVEL',500)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_BELOW',600)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',400)
C
C     PLOT ONLY SYNOP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'SYNOP Variables Flagged as Error but USED in the Analysis')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB_LEVEL')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_BELOW')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      CALL PRESET ('OBS_TYPE_LIST')
      RETURN
      END





      SUBROUTINE FDB04

      CHARACTER*5 CLIST(1)
      DATA CLIST /'AIREP'/
C
C     SELECT THE REQUIRED OPTIONS
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','USED')
      CALL PSETC ('OBS_FB_LEGEND','ON')
      CALL PSETC ('OBS_FB_PRESSURE','ON')
      CALL PSETI ('OBS_FB_LEVEL',500)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_BELOW',350)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',400)
C
C     PLOT ONLY AIREP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'AIREP Variables USED in the Analysis')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB_LEVEL')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_BELOW')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      CALL PRESET ('OBS_TYPE_LIST')
      RETURN
      END





      SUBROUTINE FDB05

      DIMENSION ILIST(1)
      DATA ILIST /164/
C
C     SELECT THE REQUIRED OPTIONS
C     NOTE THAT PAOB DATA IS ONLY PRESENT IN THE SOUTHERN HEMISPHERE.
C
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',-50.0)
      CALL PSETC ('SUBPAGE_MAP_HEMISPHERE','SOUTH')
C
C     PAOB VARIABLES USED IN THE ANALYSIS
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','USED')
      CALL PSETC ('OBS_FB_PRESSURE','ON')
C
C     PLOT ONLY PAOB REPORTS (CODE TYPE=164)
C
      CALL PSET1I ('OBS_CODE_TYPE_LIST',ILIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'PAOB Variables USED in the Analysis')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_CODE_TYPE_LIST')
      CALL PRESET ('SUBPAGE_MAP_HEMISPHERE')
      CALL PSETR  ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      RETURN
      END





      SUBROUTINE FDB06

      CHARACTER*5 CLIST(1)
      DATA CLIST /'AIREP'/
C
C     AIREPS NOT USED IN THE ANALYSIS
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','NOT_USED')
      CALL PSETC ('OBS_FB_PRESSURE','ON')
      CALL PSETI ('OBS_FB_LEVEL',500)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_BELOW',350)
      CALL PSETI ('OBS_FB_LEVEL_TOLERANCE_ABOVE',400)
C
C     PLOT ONLY AIREP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'AIREP Variables NOT USED in the Analysis')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_BELOW')
      CALL PRESET ('OBS_FB_LEVEL_TOLERANCE_ABOVE')
      RETURN
      END





      SUBROUTINE FDB07

      CHARACTER*5 CLIST
      DIMENSION CLIST(1)
      DATA CLIST /'TEMP'/
C
C     TEMP VARIABLES USED IN THE ANALYSIS
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','USED')
      CALL PSETI ('OBS_FB_LEVEL',700)
C
C     REQUEST PLOTTING OF DEPARTURE VALUES FROM 
C
      CALL PSETC ('OBS_FB_DEPARTURES', 'ON')
      CALL PSETC ('OBS_FB_DEPARTURES_TYPE', 'OBS-FG')
C
C     PLOT ONLY TEMP REPORTS

      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'TEMP Variables USED in the Analysis (Departure Values)')
      CALL PTEXT
      CALL PCOAST
      CALL PRESET ('OBS_FB_DEPARTURES')
      CALL PRESET ('OBS_FB_DEPARTURES_TYPE')
      RETURN
      END





      SUBROUTINE FDB08
      CHARACTER*5 CLIST(1)
      DATA CLIST /'TEMP'/
C
C     SELECT THE REQUIRED OPTIONS 
C
      CALL PSETC ('OBS_FB','4DVAR')
      CALL PSETC ('OBS_FB_TYPE','ALL')
      CALL PSETI ('OBS_FB_LEVEL',700)
C
C     PLOT ONLY TEMP REPORTS
C
      CALL PSET1C ('OBS_TYPE_LIST',CLIST,1)
      CALL POBS
C
C     PLOT COASTLINES AND TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     X'ALL TEMP Variables - Rejected/Not rejected - Used/Not used')
      CALL PTEXT
      CALL PCOAST
      RETURN
      END
