      PROGRAM OBS01 
C
C     THIS PROGRAM GIVES EXAMPLES OF OBSERVATION PLOTTING OF ALL
C     OBSERVATION TYPES.
C
C     INITIALIZE MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','obs01.ps')

      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Obs01')
C
C     SET UP MAPPING PARAMETERS
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)
      CALL PSETC ('MAP_COASTLINE_STYLE', 'DOT')
      CALL PSETC ('MAP_COASTLINE_COLOUR', 'RED')
      CALL PSETC ('MAP_GRID_COLOUR', 'RED')
C
C     SET OBSERVATION INPUT TYPE
C
      CALL PSETC ('OBS_INPUT_TYPE','FILE')
C
C     PLOT SYNOPS
C
      CALL SYN
      CALL PNEW ('PAGE')
C
C     PLOT AIREPS
C
      CALL AIRP
      CALL PNEW ('PAGE')
C
C     PLOT DRIBU
C
      CALL BUOY
      CALL PNEW ('PAGE')
C
C     PLOT SATOB
C
      CALL SATB
      CALL PNEW ('PAGE')
C
C     PLOT TEMPS
C
      CALL TEMP
      CALL PNEW ('PAGE')
C
C     PLOT PILOTS
C
      CALL PILT
      CALL PNEW ('PAGE')
C
C     PLOT SATEM
C
      CALL SATM
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END




      SUBROUTINE SYN
C
C     PLOT SYNOP OBSERVATIONS 
C
C     SET DISTANCE BETWEEN OBSERVATIONS TO 2CM.
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED IN
C     CHARACTER FORM.  IN THIS CASE ONLY SYNOPS TO BE PLOTTED.
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'SYNOP'/
C
C     SET OBSERVATON PARAMETERS
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/s.bfr')
      CALL PSETR ('OBS_DISTANCE_APART',2.0)
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
C
C     SET UP TEXT
C
      CALL PSETC ('TEXT_LINE_1','Observation Plotting Example')
      CALL PSETC ('TEXT_LINE_2','SYNOPS - Distance Apart set to 2.0cm')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_DISTANCE_APART')
      CALL PRESET ('OBS_TYPE_LIST')
C
      RETURN
      END




      SUBROUTINE AIRP
C
C     PLOT AIREP OBSERVATIONS ONLY.
C
C     PRESSURE LEVEL REQUIRED = 300 hPa (+/- 100 hPa)
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY AIREPS TO BE PLOTTED .
C     PRESSURE AND HEIGHT IS PLOTTED.
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'AIREP'/
*
*     CHANGE MAP CENTRE TO MID ATLANTIC
*
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',0.0)
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/slns.bfr')
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
      CALL PSETI ('OBS_LEVEL',300)
      CALL PSETI ('OBS_LEVEL_TOLERANCE',100)
c     CALL PSETC ('OBS_HEIGHT','ON')       
      CALL PSETC ('OBS_UPPER_AIR_PRESSURE','ON')       
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     1            'AIREPS at 300 hPa  (+/- 100 hPa)')
      CALL PSETC ('TEXT_LINE_2',
     1           'Pressure Level and Altitude Plotted')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_LEVEL')
      CALL PRESET ('OBS_LEVEL_TOLERANCE')
      CALL PRESET ('OBS_TYPE_LIST')
      CALL PRESET ('OBS_UPPER_AIR_PRESSURE')       
C
      RETURN
      END





      SUBROUTINE BUOY
C
C     PLOT DRIFTING BUOY OBSERVATIONS  (DRIBU) ONLY.
C
C     PLOT THE STATION IDENTIFIER
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY BUOYS TO BE PLOTTED .
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'DRIBU'/
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/buoy_satem.bfr')
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
      CALL PSETC  ('OBS_IDENTIFICATION', 'ON')
      CALL PSETC  ('OBS_IDENTIFICATION_COLOUR', 'SKY')
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','DRIFTING BUOYS')
      CALL PSETC ('TEXT_LINE_2','Station Identification Plotted')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_TYPE_LIST')
      CALL PRESET ('OBS_IDENTIFICATION')
      CALL PRESET ('OBS_IDENTIFICATION_COLOUR')       
C
      RETURN
      END




      
      SUBROUTINE SATB
C
C     PLOT SATOB OBSERVATIONS ONLY.
C
C     CHANGE SIZE OF NUMBERS AND SYMBOLS TO 0.3CM
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY SATOBS TO BE PLOTTED .
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'SATOB'/
C
C     MOVE MAP CENTRE TO EUROPE
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/sls.bfr')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',20.0)
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSETR ('OBS_SIZE',0.3)
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
      CALL PSETI ('OBS_LEVEL',850)
      CALL PSETI ('OBS_LEVEL_TOLERANCE',100)
c     CALL PSETC ('OBS_IDENTIFICATION','ON')
c     CALL PSETC ('OBS_IDENTIFICATION_TYPE','CODE_TYPE')
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','SATOBS at 850 hPa Level')
      CALL PSETC ('TEXT_LINE_2','Observation Size set to 0.3cm')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_SIZE')
      CALL PRESET ('OBS_LEVEL')
      CALL PRESET ('OBS_TYPE_LIST')
C
      RETURN
      END





      SUBROUTINE TEMP
C
C     PLOT TEMP OBSERVATIONS ONLY.
C
C     TURN ON THICKNESS (850/300 hPa)
C
C     ARRAY 'ICOD' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY TEMPS TO BE PLOTTED.
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      DIMENSION ICOD(2)
      DATA ICOD /101,102/
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/vsns.bfr')
      CALL PSETC ('OBS_THICKNESS','ON')
      CALL PSETI ('OBS_LEVEL',300)
      CALL PSETI ('OBS_LEVEL_2',850)
      CALL PSET1I ('OBS_CODE_TYPE_LIST',ICOD,2)
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     1            '300 hPa TEMP Observations')
      CALL PSETC ('TEXT_LINE_2',
     1            '850/300 hPa Thickness Plotted')
C
C     PLOT COASTINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_THICKNESS')
      CALL PRESET ('OBS_LEVEL')
      CALL PRESET ('OBS_LEVEL_2')
      CALL PRESET ('OBS_CODE_TYPE_LIST')
C
      RETURN
      END





      SUBROUTINE PILT
C
C     PLOT PILOT OBSERVATIONS ONLY.
C
C     TURN ON PRESSURE AND TIME PLOT
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY PILOTS TO BE PLOTTED.
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'PILOT'/
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
      CALL PSETC ('OBS_UPPER_AIR_PRESSURE','ON')
      CALL PSETC ('OBS_TIME_PLOT','ON')
      CALL PSETI ('OBS_LEVEL',500)
      CALL PSETC ('OBS_INPUT_FILE_NAME', 'data/oldts/vsns.bfr')
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1',
     1            'PILOTS at 500 hPa ')     
      CALL PSETC ('TEXT_LINE_2',
     1            'Pressure Level and Observation Time PLotted')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_UPPER_AIR_PRESSURE')
      CALL PRESET ('OBS_TIME_PLOT')
      CALL PRESET ('OBS_TYPE_LIST')
C
      RETURN
      END





      SUBROUTINE SATM
C
C     PLOT SATEM OBSERVATIONS ONLY.
C
C     SET DISTANCE BETWEEN OBSERVATIONS TO 2.0CM.
C     SET UPPER AND LOWER LEVELS TO 700 AND 850 hPa RESPECTIVELY.
C     TURN ON PRESSURE AND TIME PLOT.
C
C     ARRAY 'ILIS' HOLDS THE LIST OF OBSERVATION TYPES TO BE PLOTTED
C     IN CHARACTER FORM.  IN THIS CASE ONLY SATEMS TO BE PLOTTED .
C
C     ALL OBSERVATION PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CHARACTER*5 ILIS
      DIMENSION ILIS(1)
      DATA ILIS /'SATEM'/
*
*     CHANGE MAP CENTRE TO MID ATLANTIC
*
c     CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
c     CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-40.0)
c     CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',-40.0)
C
C     SET OBSERVATION PARAMETERS
C
      CALL PSETC  ('OBS_INPUT_FILE_NAME', 'data/oldts/buoy_satem.bfr')
      CALL PSETR  ('OBS_DISTANCE_APART',2.0)
      CALL PSET1C ('OBS_TYPE_LIST',ILIS,1)
      CALL PSETI ('OBS_LEVEL',850)
      CALL PSETI ('OBS_LEVEL_2',700)
      CALL PSETC ('OBS_UPPER_AIR_PRESSURE','ON')
      CALL PSETC ('OBS_TIME_PLOT','ON')
c     CALL PSETC ('OBS_IDENTIFICATION','ON')
c     CALL PSETC ('OBS_IDENTIFICATION_TYPE','CODE_TYPE')
C
C     SET TEXT
C
      CALL PSETC ('TEXT_LINE_1','SATEMS Between 850 and 700 hPa')
      CALL PSETC ('TEXT_LINE_2',
     x 'Distance Apart = 2.0cm, Pressure Levels and Time Plotted')
C
C     PLOT COASTLINES, OBSERVATIONS AND TEXT
C
      CALL PCOAST
      CALL POBS
      CALL PTEXT
C
C     RESET OBSERVATION PARAMETERS
C
      CALL PRESET ('OBS_LEVEL')
      CALL PRESET ('OBS_LEVEL_2')
      CALL PRESET ('OBS_DISTANCE_APART')
      CALL PRESET ('OBS_TYPE_LIST')
      CALL PRESET ('OBS_PRESSURE')
      CALL PRESET ('OBS_TIME_PLOT')
C
      RETURN
      END
