      PROGRAM PLOT04
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','plot04.ps')
      CALL PSETC('SUBPAGE_MAP_PROJECTION','LAMBERT')
      CALL PSETC('MAP_COASTLINE_LAND_SHADE','ON')
      CALL PSETC('MAP_COASTLINE_SEA_SHADE','ON')
      CALL PSETC('MAP_COASTLINE_LAND_SHADE_COLOUR','CREAM')
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PLOT04_ONE
      CALL PNEW('PAGE')
      CALL PLOT04_TWO
      CALL PNEW('PAGE')
      CALL PLOT04_THREE
      CALL PCLOSE
      STOP
      END


      SUBROUTINE PLOT04_ONE
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',43.5)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',53.5)
      CALL PSETC('MAP_GRID_COLOUR','GREEN')
      CALL PCOAST
      CALL PNEW('PAGE')

      CALL PSETC('MAP_COASTLINE_RESOLUTION','LOW') 
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETC('MAP_COASTLINE_RESOLUTION','HIGH') 
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PRESET('MAP_COASTLINE_RESOLUTION') 

      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-55.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.0)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.0)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETC('MAP_COASTLINE_RESOLUTION','LOW') 
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETC('MAP_COASTLINE_RESOLUTION','HIGH') 
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PRESET('MAP_COASTLINE_RESOLUTION') 

      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',20.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-20.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',54.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',165.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',35.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',45.)
      CALL PCOAST
      RETURN
      END


      SUBROUTINE PLOT04_TWO
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',140.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',190.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',230.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-60.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-120.0)
      CALL PSETR('SUBPAGE_MAP_SCALE',130.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',19.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-21.)
      CALL PCOAST
      RETURN
      END


      SUBROUTINE PLOT04_THREE
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',20.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',40.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-50.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',90.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',40.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-50.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',150.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',40.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-50.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',230.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',40.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-50.)
      CALL PCOAST
      CALL PNEW('PAGE')
      CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-1.0)
      call PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-60.)
      call PSETR('SUBPAGE_MAP_SCALE',105.E4)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_1',40.)
      CALL PSETR('SUBPAGE_MAP_STANDARD_LATITUDE_2',-50.)
      CALL PCOAST
      RETURN
      END
