C (C) Copyright 1996-2016 ECMWF.
C 
C This software is licensed under the terms of the Apache Licence Version 2.0
C which can be obtained at http://www.apache.org/licenses/LICENSE-2.0. 
C In applying this licence, ECMWF does not waive the privileges and immunities 
C granted to it by virtue of its status as an intergovernmental organisation nor
C does it submit to any jurisdiction.
C

      PROGRAM PLOT02
C
C     THIS ROUTINE DEMONSTRATES MAGICS PARAMETER SETTINGS FOR COASTLINES
C     AND PROJECTIONS.  THE ILLUSTRATIONS ARE BASED ON CYLINDRICAL AND
C     POLAR STEREOGRAPHIC PROJECTIONS.  THE MAP AREA DEFINITIONS
C     'CORNERS' AND 'CENTRE' ARE USED.
C
C
C     OPEN MAGICS
C
      CALL POPEN
      CALL PSETC ('PS_DEVICE','ps_a4')
      CALL PSETC ('PS_FILE_NAME','plot02-test.ps')
      CALL PSETR ('SUPER_PAGE_Y_LENGTH',16.0)
      CALL PSETR ('SUPER_PAGE_X_LENGTH',16.0)
      CALL PSETC ('PAGE_ID_LINE_USER_TEXT','Tests/Plot02')
C
C     DEFINE PAGE
C
      CALL PSETR ('PAGE_Y_LENGTH',16.0)
      CALL PSETR ('PAGE_X_LENGTH',16.0)
      CALL PSETR ('SUBPAGE_X_POSITION',1.5)
      CALL PSETR ('SUBPAGE_Y_POSITION',1.0)
      CALL PSETR ('SUBPAGE_Y_LENGTH',13.0)
      CALL PSETR ('SUBPAGE_X_LENGTH',13.0)
C
C     GENERATE TEXT FOR TITLE
C
      CALL PSETC ('TEXT_LINE_1','@TEXT_CHARACTER_1@')
      CALL PSETC ('TEXT_LINE_2','@TEXT_CHARACTER_2@')
      CALL PSETC ('TEXT_LINE_3','@TEXT_CHARACTER_3@')
      CALL PSETI ('TEXT_LINE_COUNT',3)
      CALL PSETR ('TEXT_REFERENCE_CHARACTER_HEIGHT',0.5)
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')
      CALL PSETC ('MAP_GRID_COLOUR','GREY')
C
C     PLOT THREE CYLINDRICAL MAPS
C
c      CALL PLOT02_ONE
c      CALL PNEW ('PAGE')
c      CALL PLOT02_TWO
c      CALL PNEW ('PAGE')
c      CALL PLOT02_THREE
c      CALL PNEW ('PAGE')
C
C     PLOT THREE POLAR STEREOGRAPHIC MAPS ON THE NORTHERN HEMISPHERE
C
C      CALL PLOT02_FOUR
C      CALL PNEW ('PAGE')
C      CALL PLOT02_FIVE
C      CALL PNEW ('PAGE')
C      CALL PLOT02_SIX
C      CALL PNEW ('PAGE')
C
C     PLOT THREE POLAR STEREOGRAPHIC MAPS ON THE SOUTHERN HEMISPHERE
C
C      CALL PLOT02_SEVEN
C      CALL PNEW ('PAGE')
C      CALL PLOT02_EIGHT
C      CALL PNEW('PAGE')
C      CALL PLOT02_NINE
C      CALL PNEW('PAGE')
C      CALL PLOT02_TEN
C      CALL PNEW('PAGE')
C      CALL PLOT02_ELEVEN
C      CALL PNEW('PAGE')
C      CALL PLOT02_TWELVE
C      CALL PNEW('PAGE')
C      CALL PLOT02_THIRTEEN
C      CALL PNEW('PAGE')
C      CALL PLOT02_FOURTEEN
C      CALL PNEW('PAGE')
      CALL PLOT02_FIFTEEN
      CALL PNEW('PAGE')
      CALL PLOT02_SIXTEEN
C
C     CLOSE MAGICS
C
      CALL PCLOSE
C
      END
      SUBROUTINE PLOT02_ONE
C
C     PLOT GLOBAL CYLINDRICAL MAP.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_1','Cylindrical Map Projection ')
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Default values for MAGICS Parameters Used')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Area is Whole Globe, Defined by Coordinates of'//
     2            ' LOWER_LEFT and UPPER_RIGHT Corners ')
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_TWO
C
C     PLOT A SELECTED AREA DEFINED BY COORDINATES OF LOWER_LEFT AND
C     UPPER_RIGHT CORNERS.  PROJECTION IS CYLINDRICAL.  A TEXT BLOCK
C     IS PLOTTED ON A BLANKED AREA.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-10.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',30.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',15.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',65.0)
C
C     PLOT TITLE (INSTRUCTION STRING IS USED TO PLOT DEGREE SIGN)
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Area definition by Corner Points')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Map Area is 10W to 15E,'//
     2            '30N to 65N')
C
      CALL PTEXT
C
C     PLOT COASTLINES
C
      CALL PSETI ('MAP_COASTLINE_THICKNESS',3)
      CALL PCOAST
C
      RETURN
      END
      SUBROUTINE PLOT02_THREE
C
C     PLOT DIFFERENT SELECTED AREA IN CYLINDRICAL PROJECTION.
C     COASTLINE RESOLUTION/COLOUR AND GRID INCREMENTS ARE ALSO CHANGED.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
C     SET UP SELECTED AREA
C
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',100.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',-10.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',140.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',20.0)
C
C     SET UP COASTLINE AND GRID INCREMENTS
C
      CALL PSETR ('MAP_GRID_LATITUDE_INCREMENT',5.0)
      CALL PSETC ('MAP_COASTLINE_RESOLUTION','HIGH')
      CALL PSETI ('MAP_COASTLINE_THICKNESS',2)
      CALL PSETR ('MAP_GRID_LONGITUDE_INCREMENT',5.0)
      CALL PSETC ('MAP_COASTLINE_COLOUR','GREEN')
      CALL PSETC ('MAP_GRID_COLOUR','GREY')
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_MODE','TITLE')
      CALL PSETC ('TEXT_BOX_BLANKING','OFF')
      CALL PSETC ('TEXT_BORDER','OFF')
      CALL PSETI ('TEXT_FIRST_LINE',1)
      CALL PSETI ('TEXT_LINE_COUNT',3)
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Coastline Resolution is HIGH and '//
     2            'Grid Intervals are 5')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Area Definition is by UPPER_RIGHT and '//
     2            'LOWER_LEFT Corners')
C
      CALL PTEXT
C
C     RESET CERTAIN MAP PARAMETERS
C
      CALL PRESET('MAP_COASTLINE_RESOLUTION')
      CALL PRESET('MAP_GRID_LATITUDE_INCREMENT')
      CALL PRESET('MAP_GRID_LONGITUDE_INCREMENT')
C
      RETURN
      END
      SUBROUTINE PLOT02_FOUR
C
C     PLOT NORTHERN HEMISPHERE ON POLAR STEREOGRAPHIC PROJECTION.
C     CORNER POINTS ARE RESET TO MAGICS DEFAULT VALUES FOR POLAR
C     STEREOGRAPHIC.  MAP LABEL LATITUDE FREQUENCY CHANGED TO 2.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',-20.1)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-44.7)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',134.5)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',-20.0)
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
      CALL PSETI ('MAP_LABEL_LATITUDE_FREQUENCY',2)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_1',
     1            'Polar Stereographic Map Projection')
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Plot Area is Whole Northen Hemisphere')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Corner Values Reset to Default for Polar'//
     2            ' Stereographic')
C
      CALL PTEXT
C
C     RESET CERTAIN PARAMETERS
C
      CALL PRESET ('MAP_LABEL_LATITUDE_FREQUENCY')
C
      RETURN
      END
      SUBROUTINE PLOT02_FIVE
C
C     PLOT SELECTED AREA IN POLAR STEREOGRAPHIC.  AREA DEFINITION IS
C     BASED ON 'CORNERS'.
C
C     THE FOLLOWING PARAMETER IS STILL ACTIVE FROM A PREVIOUS CALL.  ALL
C     OTHER PLOT LAYOUT PARAMETERS THAT ARE NOT SET IN THIS SUBROUTINE
C     TAKE THEIR DEFAULT VALUES.
C
C      'SUBPAGE_MAP_PROJECTION'        'POLAR_STEREOGRAPHIC'
C
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-10.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',30.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',80.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',50.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Area Definition is by Corners: '//
     2            '30N,10W and 50N,80E')
C
      CALL PSETC ('TEXT_CHARACTER_3','Vertical Longitude is 0.0')
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_SIX
C
C     PLOT SAME SELECTED AREA WITH DIFFERENT VERTICAL LONGITUDE.
C
C     THE FOLLOWING PLOT LAYOUT PARAMETERS ARE STILL ACTIVE FROM
C     PREVIOUS CALLS.  ALL OTHER PLOT LAYOUT PARAMETERS THAT ARE NOT
C     SET IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'SUBPAGE_MAP_PROJECTION'        'POLAR_STEREOGRAPHIC'
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'                 -10.0
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                   30.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'                 80.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'                  50.0
C
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',25.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_3','Vertical Longitude is 25.0E')
C
      CALL PTEXT
C
C     RESET SUBPAGE_MAP PARAMETERS
C
      CALL PRESET('SUBPAGE_MAP_VERTICAL_LONGITUDE')
C
      RETURN
      END
      SUBROUTINE PLOT02_SEVEN
C
C     PLOT SOUTHERN HEMISPHERE IN POLAR STEREOGRAPHIC PROJECTION.  MAP
C     AREA DEFINITION IS SET TO 'CENTRE', MAP SCALE IS ESTIMATED BY
C     THE RELATION:  PAGE_SIZE * MAP_SCALE = 24.0E8
C
C     THE FOLLOWING PLOT LAYOUT PARAMETERS ARE STILL ACTIVE FROM
C     PREVIOUS CALLS.  ALL OTHER PLOT LAYOUT PARAMETERS THAT ARE NOT
C     SET IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'SUBPAGE_MAP_PROJECTION'        'POLAR_STEREOGRAPHIC'
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'                 -10.0
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                   30.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'                 80.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'                  50.0
C
      CALL PSETR ('SUBPAGE_MAP_SCALE', 184.6E6)
      CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',-90.0)
      CALL PSETC ('SUBPAGE_MAP_HEMISPHERE','SOUTH')
      CALL PSETI ('MAP_LABEL_LATITUDE_FREQUENCY',2)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Area is Whole Southern Hemisphere, '//
     2            'Selected by Using CENTRE')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Map Scale is 184.6E6, '//
     2            'Vertical Longitude is 0.0')
C
      CALL PTEXT
C
C     RESET CERTAIN PARAMETERS
C     CENTERED AREA DEFINITION.
C
      CALL PRESET('SUBPAGE_MAP_SCALE')
      CALL PRESET('MAP_LABEL_LATITUDE_FREQUENCY')
C
      RETURN
      END
      SUBROUTINE PLOT02_EIGHT
C
C     PLOT SELECTED SOUTHERN HEMISPHERE AREA IN POLAR STEREOGRAPHIC
C     PROJECTION, DEFINED BY 'CENTRE' MAP SCALE.
C
C     THE FOLLOWING PLOT LAYOUT PARAMETERS ARE STILL ACTIVE FROM
C     PREVIOUS CALLS.  ALL OTHER PLOT LAYOUT PARAMETERS THAT ARE NOT
C     SET IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'SUBPAGE_MAP_PROJECTION'        'POLAR_STEREOGRAPHIC'
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'                 -10.0
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                   30.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'                 80.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'                  50.0
C      'SUBPAGE_MAP_AREA_DEFINITION'                'CENTRE'
C      'SUBPAGE_MAP_HEMISPHERE'                      'SOUTH'
C
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',130.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',-20.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',130.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Area Definition is by MAP_CENTRE and '//
     2            'Coordinates are')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            '20.0S, 130.0E, Map Scale is 50.0E6, '//
     2            'Vertical Longitude is 130.0E')
C
      CALL PTEXT
      CALL PRESET ('SUBPAGE_MAP_CENTRE_LATITUDE')
      CALL PRESET ('SUBPAGE_MAP_CENTRE_LONGITUDE')
C
      RETURN
      END
      SUBROUTINE PLOT02_NINE
C
C     PLOT THE SAME SELECTED AREA WITH DIFFERENT VERTICAL LONGITUDE
C     VALUE.
C
C     THE FOLLOWING PLOT LAYOUT PARAMETERS ARE STILL ACTIVE FROM
C     PREVIOUS CALL.  ALL OTHER PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
C      'SUBPAGE_MAP_PROJECTION'        'POLAR_STEREOGRAPHIC'
C      'SUBPAGE_LOWER_LEFT_LONGITUDE'                 -10.0
C      'SUBPAGE_LOWER_LEFT_LATITUDE'                   30.0
C      'SUBPAGE_UPPER_RIGHT_LONGITUDE'                 80.0
C      'SUBPAGE_UPPER_RIGHT_LATITUDE'                  50.0
C      'SUBPAGE_MAP_AREA_DEFINITION'                'CENTRE'
C      'SUBPAGE_MAP_HEMISPHERE'                      'SOUTH'
C
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',-60.0)
      CALL PSETC ('MAP_COASTLINE_STYLE','DOT')
      CALL PSETR ('MAP_GRID_LATITUDE_REFERENCE',20.0)
      CALL PSETR ('MAP_GRID_LONGITUDE_REFERENCE',100.0)
      CALL PSETR ('MAP_GRID_LATITUDE_INCREMENT',5.0)
      CALL PSETR ('MAP_GRID_LONGITUDE_INCREMENT',10.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            '20 S 130 E, Map Scale is 50.0E6, Vertical '//
     2            'Longitude is 60.0W')
C
      CALL PTEXT
C
      CALL PRESET ('SUBPAGE_LOWER_LEFT_LONGITUDE')
      CALL PRESET ('SUBPAGE_LOWER_LEFT_LATITUDE')
      CALL PRESET ('SUBPAGE_UPPER_RIGHT_LONGITUDE')
      CALL PRESET ('SUBPAGE_UPPER_RIGHT_LATITUDE')
      CALL PRESET ('MAP_GRID_LATITUDE_REFERENCE')
      CALL PRESET ('MAP_GRID_LATITUDE_INCREMENT')
      CALL PRESET ('MAP_GRID_LONGITUDE_REFERENCE')
      CALL PRESET ('MAP_GRID_LONGITUDE_INCREMENT')
      CALL PRESET ('MAP_COASTLINE_STYLE')
      RETURN
      END
      SUBROUTINE PLOT02_TEN
C
C     PLOT GLOBAL MAP IN MERCATOR PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','MERCATOR')
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_1','MERCATOR MAP PROJECTION ')
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Default Values for MAGICS Parameters Used')
C
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'Area is Whole Globe, Defined by Coordinates of'//
     2            ' LOWER_LEFT and UPPER_RIGHT Corners ')
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_ELEVEN
C
C     PLOT SUBAREA IN MERCATOR PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','MERCATOR')
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LONGITUDE',-10.0)
      CALL PSETR ('SUBPAGE_LOWER_LEFT_LATITUDE',30.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LONGITUDE',45.0)
      CALL PSETR ('SUBPAGE_UPPER_RIGHT_LATITUDE',65.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_CHARACTER_1','MERCATOR MAP PROJECTION ')
C
      CALL PSETC ('TEXT_CHARACTER_2',
     1            'Area is Defined by Coordinates of'//
     2            ' LOWER_LEFT and UPPER_RIGHT Corners ')
      CALL PSETC ('TEXT_CHARACTER_3',
     1            'MAP AREA IS 10W TO 45E,'//
     2            '30N TO 65N')
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_TWELVE
C
C     PLOT DEFAULT LAMBERT PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','LAMBERT')
c     CALL PSETR ('SUBPAGE_MAP_SCALE',8.E5)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_LINE_1','DEFAULT LAMBERT MAP PROJECTION ')
C
      CALL PSETC ('TEXT_LINE_2',
     1   'Default Values for all Map Layout Parameters')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_THIRTEEN
C
C     PLOT SELECTED LAMBERT PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','LAMBERT')
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-70.0)
      CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',50.0)
      CALL PSETR ('SUBPAGE_MAP_STANDARD_LATITUDE_1',45.0)
      CALL PSETR ('SUBPAGE_MAP_STANDARD_LATITUDE_2',75.0)
      CALL PSETR ('SUBPAGE_MAP_SCALE',10.E5)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_LINE_1','SELECTED LAMBERT MAP PROJECTION ')
C
      CALL PSETC ('TEXT_LINE_2',
     1   'Area is Defined by Centre of Map, Standard Parallels')
      CALL PSETC ('TEXT_LINE_3',
     1   ' and Map Scale')
      CALL PSETI ('TEXT_LINE_COUNT',3)
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_FOURTEEN
C
C     PLOT AITOFF PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','AITOFF')
      CALL PSETR ('SUBPAGE_MAP_VERTICAL_LONGITUDE',-65.0)
C
C     PLOT COASTLINES
C
      CALL PCOAST
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_LINE_1','AITOFF MAP PROJECTION ')
C
      CALL PSETC ('TEXT_LINE_2',
     1     'Area is Defined by Vertical Longitude')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_FIFTEEN
C
C     PLOT ZONAL OCEAN_SECTION PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETC ('PAGE_ID_LINE_ERRORS_PLOT','OFF')
      CALL PSETR ('SUBPAGE_X_POSITION',3.5)
      CALL PSETR ('SUBPAGE_Y_POSITION',2.0)
      CALL PSETR ('SUBPAGE_Y_LENGTH',12.0)
      CALL PSETR ('SUBPAGE_X_LENGTH',12.0)
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','OCEAN_SECTION')
      CALL PSETC ('GRIB_TEXT','OFF')
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     X  'data/oldts/ocean_section_1')
      CALL PGRIB
C
C     PLOT CONTOURS  
C
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL',5.0)
      CALL PSETC ('CONTOUR_HIGHLIGHT','OFF')
      CALL PSETC ('CONTOUR_LABEL','OFF')
      CALL PSETC ('CONTOUR_HILO','OFF')
      CALL PSETC ('CONTOUR_SHADE','ON')
      CALL PSETC ('CONTOUR_SHADE_COLOUR_DIRECTION','CLOCKWISE')
      CALL PSETC ('CONTOUR_SHADE_METHOD','AREA_FILL')
      CALL PSETC ('CONTOUR_SHADE_MIN_LEVEL_COLOUR','BLUE')
      CALL PSETC ('CONTOUR_SHADE_MAX_LEVEL_COLOUR','RED')
      CALL PCONT 
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_LINE_1','ZONAL OCEAN_SECTION ')
C
      CALL PSETC ('TEXT_LINE_2',
     1     'Projection is defined by GRIB Code FIeld')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
      CALL PTEXT
C
      RETURN
      END
      SUBROUTINE PLOT02_SIXTEEN
C
C     PLOT OCEAN_SECTION TIME_SERIES PROJECTION.
C
C     ALL PLOT LAYOUT PARAMETERS THAT ARE NOT SET
C     IN THIS SUBROUTINE TAKE THEIR DEFAULT VALUES.
C
      CALL PSETR ('SUBPAGE_X_POSITION',3.5)
      CALL PSETR ('SUBPAGE_Y_POSITION',2.0)
      CALL PSETR ('SUBPAGE_Y_LENGTH',12.0)
      CALL PSETR ('SUBPAGE_X_LENGTH',12.0)
      CALL PSETC ('SUBPAGE_MAP_PROJECTION','OCEAN_SECTION')
      CALL PSETC ('GRIB_TEXT','OFF')
      CALL PSETC ('GRIB_INPUT_TYPE','FILE')
      CALL PSETC ('GRIB_INPUT_FILE_NAME',
     X  'data/oldts/ocean_section_2')
      CALL PGRIB
      CALL PSETC ('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
      CALL PSETR ('CONTOUR_INTERVAL',0.2)
      CALL PSETR ('CONTOUR_REFERENCE_LEVEL',0.0)
      CALL PSETC ('CONTOUR_HIGHLIGHT','OFF')
      CALL PSETC ('CONTOUR_LABEL','OFF')
      CALL PSETC ('CONTOUR_HILO','OFF')
      CALL PSETC ('CONTOUR_SHADE','ON')
      CALL PSETC ('CONTOUR_SHADE_COLOUR_DIRECTION','CLOCKWISE')
      CALL PSETC ('CONTOUR_SHADE_METHOD','AREA_FILL')
      CALL PSETC ('CONTOUR_SHADE_MIN_LEVEL_COLOUR','BLUE')
      CALL PSETC ('CONTOUR_SHADE_MAX_LEVEL_COLOUR','RED')
C
C     PLOT COASTLINES
C
      CALL PCONT 
C
C     PLOT TITLE
C
      CALL PSETC ('TEXT_LINE_1','OCEAN_SECTION TIME_SERIES')
C
      CALL PSETC ('TEXT_LINE_2',
     1     'Projection is defined by GRIB Code FIeld')
      CALL PSETI ('TEXT_LINE_COUNT',2)
C
      CALL PTEXT
C
      RETURN
      END
