	PROGRAM PLOT03
C
C	THIS PROGRAM DEMONSTRATES LAND/SEA SHADING WITH COASTLINE PLOTTING
C
C	OPEN MAGICS
C
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','plot03.ps')
	CALL PSETC ('PAGE_ID_LINE_TYPE','LOGOONLY')
C
C	FIRST SUPER-PAGE.
C
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Cylindrical Projection')
	CALL PTEXT
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE','ON')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE','ON')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','CYAN')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','ORANGE')
	CALL PSETC ('MAP_GRID_COLOUR','BLACK')
	CALL PCOAST
	CALL PNEW('PAGE')
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','BLUE')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','AVOCADO')
	CALL PCOAST
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Polar_Stereographic Projection')
	CALL PTEXT
	CALL PNEW('PAGE')
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')         
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-20.0)
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',55.0)
	CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)             
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','RED')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','GREY')
	CALL PSETC ('MAP_GRID_COLOUR','BLACK')
	CALL PCOAST
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Polar_Stereographic Projection')
	CALL PTEXT
	CALL PNEW('PAGE')
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','SATELLITE')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','BLUE')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','GREEN')
	CALL PSETC ('GRIB_INPUT_TYPE','FILE')
	CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/im96011000.img')
	CALL PGRIB
	CALL PCOAST
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Satellite Projection')
	CALL PTEXT
	CALL PNEW('PAGE')
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','AITOFF')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','GREEN')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','CREAM')
	CALL PCOAST
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Aitoff Projection')
	CALL PTEXT
	CALL PNEW('PAGE')
	CALL PRESET ('SUBPAGE_MAP_SCALE')             
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','LAMBERT')
	CALL PSETC ('MAP_COASTLINE_SEA_SHADE_COLOUR','GREEN')
	CALL PSETC ('MAP_COASTLINE_LAND_SHADE_COLOUR','CREAM')
	CALL PCOAST
	CALL PSETC('TEXT_LINE_1',
     X'Example of LAND/SEA Shading on Lambert Projection')
	CALL PTEXT
C
C	CLOSE MAGICS
C
	CALL PCLOSE
C
	END
