	PROGRAM SPEC01
C
C	PROGRAM TO DEMONSTRATE USAGE OF SPECIFICATION GROUPS
C	
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','spec01.ps')
C
C	SET UP TWO MAP AREAS AND STORE IN SPEC GROUPS
C
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','MERCATOR')
	CALL PACT ('PUT_SPEC','SUBPAGE_MAP','MAP1')
	CALL PSETC ('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC ('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')        
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LATITUDE',40.0)          
	CALL PSETR ('SUBPAGE_MAP_CENTRE_LONGITUDE',-20.0)          
	CALL PSETR ('SUBPAGE_MAP_SCALE',35.E6)                     
	CALL PACT ('PUT_SPEC','SUBPAGE_MAP','MAP2')
C
C	PASS THE FIELD FOR CONTOURING
C
	CALL PSETC ('GRIB_INPUT_TYPE','FILE')
	CALL PSETC ('GRIB_SUBAREA_EXTRACTION','OFF')  
	CALL PSETC ('GRIB_INPUT_FILE_NAME','data/oldts/500Z.grb')
	CALL PGRIB
C
C	STORE 2 SETS OF CONTOURING SETTINGS IN SPEC GROUPS
C
	CALL PSETC ('CONTOUR_SHADE','ON')
	CALL PSETC ('CONTOUR_SHADE_METHOD','AREA_FILL')
	CALL PACT ('PUT_SPEC','CONTOUR','CONT1')
	CALL PSETC ('CONTOUR_SHADE_METHOD','HATCH')
	CALL PACT ('PUT_SPEC','CONTOUR','CONT2')
C
C	PLOT FIRST MAP
C
	CALL SPEC01_ONE
C
C	PLOT SECOND MAP
C
	CALL PNEW ('PAGE')
	CALL SPEC01_TWO
C
C	PLOT THIRD MAP - DEFAULT AREA AND CONTOURING
C
	CALL PNEW ('PAGE')
	CALL SPEC01_THREE
	CALL PCLOSE
	END
	SUBROUTINE SPEC01_ONE
C
C	PLOT MAP 2 WITH CONTOUR SETTING NUMBER 1
C
 	CALL PACT ('GET_SPEC','SUBPAGE_MAP','MAP2')
 	CALL PACT ('GET_SPEC','CONTOUR','CONT1')
 	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
 	CALL PSETI ('TEXT_LINE_COUNT',1)
 	CALL PSETC ('TEXT_LINE_1',
     x  'Specification Group Example - Map2 with Contour1')
	CALL PCONT
	CALL PCOAST
	CALL PTEXT  
	RETURN
	END
	SUBROUTINE SPEC01_TWO
C
C	PLOT MAP 1 WITH CONTOUR SETTING NUMBER 2
C
 	CALL PACT ('GET_SPEC','SUBPAGE_MAP','MAP1')
 	CALL PACT ('GET_SPEC','CONTOUR','CONT2')
 	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
 	CALL PSETI ('TEXT_LINE_COUNT',1)           
 	CALL PSETC ('TEXT_LINE_1',
     x  'Specification Group Example - Map1 with Contour2')
	CALL PCONT
	CALL PCOAST
	CALL PTEXT  
	RETURN
	END
	SUBROUTINE SPEC01_THREE
C
C	PLOT DEFAULT MAP WITH DEFAULT CONTOUR SETTINGS
C
 	CALL PACT ('GET_SPEC','ALL','DEFAULT')       
 	CALL PSETC ('TEXT_JUSTIFICATION','CENTRE')
 	CALL PSETI ('TEXT_LINE_COUNT',1)           
 	CALL PSETC ('TEXT_LINE_1',
     x  'Specification Group Example - Default map and contours')
	CALL PCONT
	CALL PCOAST
	CALL PTEXT  
	RETURN
	END
