	PROGRAM STRM02
C
C	THIS PROGRAM DEMONSTRATES MAGICS STREAMLINE PLOTTING FACILITIES.
C	THE METEOROLOGICAL DATA FIELDS ARE STANDARD GLOBAL
C	500 hPa MODEL OUTPUT FIELDS ON A REGULAR 1.5 DEGREE GRID.
C	WIND STREAMLINES AND COASTLINES ARE PROJECTED ONTO POLAR
C	STEREOGRAPHIC AREAS. THE STREAMLINES ARE PLOTTED USING
C	VARIOUS SETTINGS OF MAGICS PARAMETERS.
C	ISOTACHS ARE PLOTTED USING THE DEFAULT VALUES OF MAGICS
C	PARAMETERS FOR ISOTACH PLOTTING, SETTING THE PARAMETER
C	CONTOUR_DATA_TRANSFORMATION TO 'ISOTACHS' AND CALLING 
C	ACTION ROUTINE PCONT.
C
C	OPEN MAGICS.
C
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','strm02.ps')
c	CALL PSETR('PS_SCALE',0.78)
	CALL PSETC('PS_DEVICE','ps_vax_c')
	CALL PSETC('PAGE_ID_LINE_USER_TEXT','Tests/Strm02')
	CALL PSETC('PAGE_ID_LINE_ERRORS_PLOT','OFF')
	CALL PSETC('SUBPAGE_MAP_PROJECTION','POLAR_STEREOGRAPHIC')
	CALL PSETC('SUBPAGE_MAP_AREA_DEFINITION','CENTRE')
	CALL PSETR('SUBPAGE_MAP_SCALE',136.0E6)
C
C	PASS THE DATA TO MAGICS.
C
	CALL PSETC('GRIB_INPUT_TYPE','FILE')
	CALL PSETC('GRIB_INPUT_FILE_NAME','data/oldts/500uv.grb')
	CALL PSETI('GRIB_WIND_POSITION_1',1)
	CALL PSETI('GRIB_WIND_POSITION_2',2)
	CALL PGRIB
C
C	PLOT WIND STREAMLINES ON FULL NORTHERN HEMISPHERE
C
	CALL STRM02_ONE
	CALL PNEW('PAGE')
C
C	PLOT WIND STREAMLINES ON ATLANTIC POLAR STEREOGRAPHIC AREA
C
	CALL STRM02_TWO
	CALL PNEW('PAGE')
C
C	WIND STREAMLINES AND ISOTACHS ON EUROPEAN POLAR STEREOGRAPHIC AREA
C
	CALL STRM02_THREE
	CALL PNEW('PAGE')
C
C	WIND STREAMLINES AND ISOTACHS ON A SELECTED POLAR STEREOGRAPHIC AREA
C	WITH VARYING DENSITY AND CLOSENESS MARGIN.
C
	CALL STRM02_FOUR
	CALL PNEW('PAGE')
C
C	PLOT STREAMLINES AND ISOTACHS ON SOUTHERN HEMISPHERE
C
	CALL STRM02_FIVE
C
C	CLOSE MAGICS.
C
	CALL PCLOSE
	END

	SUBROUTINE STRM02_ONE
C
C	THIS SUBROUTINE PLOTS STREAMLINES AND COASTLINES
C	ON A POLAR STEREOGRAPHIC MAP. DEFAULT SETTING USED ARE:
C
C	'WIND_STREAMLINE_ARROWHEAD_INDEX' , 1
C	'WIND_STREAMLINE_MIN_DENSITY', 1.0
C	'WIND_STREAMLINE_CLOSENESS_CHECK', `ON'
C	'WIND_STREAMLINE_CLOSENESS_MARGIN', 0.2
C	'WIND_STREAMLINE_THICKNESS' , 2
C	'WIND_STREAMLINE_COLOUR' , `BLUE'
C	'WIND_STREAMLINE_STYLE' , `SOLID'
C	'WIND_STREAMLINE_MIN_SPEED' , 1.0
C	'WIND_STREAMLINE_CALM_MARKER' , `ON'
C	'WIND_STREAMLINE_MARKER INDEX' , 3
C	'WIND_STREAMLINE_MARKER_HEIGHT' , 0.2
C
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETC('TEXT_LINE_1',
     1  'Full Northern Hemisphere Polar Stereographic 500 hPa '//
     2  'Wind Field')
	CALL PSETC('TEXT_LINE_2',
     1  'Projected from a regular Global 1.5 Degree Field')
	CALL PSETC('TEXT_LINE_3',
     1  'Default Values for WIND_STREAMLINE Parameters')
	CALL PSETI('TEXT_LINE_COUNT',3)
	CALL PSETC('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETR('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
C
C	PLOT THE TITLE, COASTLINES AND WIND ARROWS.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET STREAMLINE SWITCH.
C
	CALL PRESET('WIND_FIELD_TYPE')
C
	RETURN
	END

	SUBROUTINE STRM02_TWO
C
C	STREAMLINES AND ISOTACHS ON A SELECTED POLAR STEREOGRAPHIC 
C	AREA WITH CENTRE POINT AT 52.0N, 0.0E.
C	THE ISOTACHS ARE PLOTTED WITH SHADING BETWEEN CONTOURS BUT
C	WITHOUT THE ACTUAL CONTOURS. LEGEND IS SET TO 'ON'.
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETR('SUBPAGE_MAP_SCALE',60.0E6)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',0.0)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',52.0)
	CALL PSETC('LEGEND','ON')
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETI('WIND_STREAMLINE_MARKER_INDEX',8)
	CALL PSETR('WIND_STREAMLINE_MARKER_HEIGHT',0.4)
	CALL PSETC('WIND_STREAMLINE_STYLE','DASH')
C
	CALL PSETC('TEXT_LINE_1',
     1  'Selected Northern Hemisphere Polar Stereographic 500 hPa '//
     2  'Wind Field')
	CALL PSETC('TEXT_LINE_3',
     1  'Calm Marker Index is  15, Marker Height is 0.4, ' //
     2  'Style is DASH ')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET PARAMETERS.
C
	CALL PRESET('WIND_FIELD_TYPE')
	CALL PRESET('WIND_STREAMLINE_MARKER_INDEX')
	CALL PRESET('WIND_STREAMLINE_MARKER_HEIGHT')
	CALL PRESET('WIND_STREAMLINE_STYLE')
C
	RETURN
	END
	SUBROUTINE STRM02_THREE
C
C	WIND STREAMLINES AND ISOTACHS IN A SELECTED
C	AREA (EUROPEAN AREA) ON A POLAR STEREOGRAPHIC PROJECTION.
C	THE STREAMLINE MIN DENSITY IS SET TO 4.0.
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
C
	CALL PSETR('WIND_STREAMLINE_MIN_DENSITY',4.0)
	CALL PSETR('WIND_STREAMLINE_CLOSENESS_MARGIN',0.2)
	CALL PSETR('SUBPAGE_MAP_SCALE',25.0E6)
C
	CALL PSETC('TEXT_LINE_3',
     1  'Streamlines and Isotachs, Streamline Min Density is 4.0, ' //
     2  'Closeness Margin is 0.2')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	PLOT ISOTACHS.
C
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PSETC('LEGEND','ON')
	CALL PSETC('CONTOUR','OFF')
	CALL PSETC('CONTOUR_HILO','OFF')
	CALL PSETC('CONTOUR_SHADE','ON')
	CALL PSETC('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
	CALL PSETR('CONTOUR_INTERVAL',10.0)
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL',10.0)
	CALL PCONT
C
C	RESET ISOTACH AND STREAMLINE PARAMETERS.
C
	CALL PRESET('CONTOUR_DATA_TRANSFORMATION')
	CALL PRESET('WIND_STREAMLINE_MIN_DENSITY')
	CALL PRESET('WIND_FIELD_TYPE')
C
	RETURN
	END
	SUBROUTINE STRM02_FOUR
C
C	STREAMLINES AND ISOTACHS IN A SELECTED POLAR STEREOGRAPHIC
C	AREA. STREAMLINE CLOSENESS MARGIN IS SET TO 0.35.
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('LEGEND_ENTRY','OFF')
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
C
	CALL PSETR('WIND_STREAMLINE_CLOSENESS_MARGIN',0.35)
	CALL PSETR('SUBPAGE_MAP_VERTICAL_LONGITUDE',180.0)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',180.0)
C
	CALL PSETC('TEXT_LINE_3',
     1  'Streamlines and Wind Flags, Streamline Closeness Margin is '//
     2  '@(F5.2)WIND_STREAMLINE_CLOSENESS_MARGIN@')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	PLOT WIND FLAGS
C
	CALL PSETC('WIND_FIELD_TYPE','FLAGS')
	CALL PSETR('WIND_THINNING_FACTOR',4.)
	CALL PSETC('WIND_FLAG_ORIGIN_MARKER','DOT')
	CALL PWIND
C
C	RESET WIND_FIELD_TYPE
C
	CALL PRESET('WIND_FIELD_TYPE')
	CALL PRESET('WIND_STREAMLINE_CLOSENESS_MARGIN')
	CALL PSETC('LEGEND_ENTRY','ON')
C
	RETURN
	END
	SUBROUTINE STRM02_FIVE
C
C	STREAMLINES AND ISOTACHS IN A SOUTHERN HEMISPHERE
C	STEREOGRAPHIC AREA.
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
C
	CALL PSETC('SUBPAGE_MAP_HEMISPHERE','SOUTH')        
	CALL PSETR('SUBPAGE_MAP_SCALE',55.0E6)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LATITUDE',-40.0)
	CALL PSETR('SUBPAGE_MAP_CENTRE_LONGITUDE',-60.0)
	CALL PSETR('SUBPAGE_MAP_VERTICAL_LONGITUDE',120.0)
	CALL PSETR('SUBPAGE_MAP_VERTICAL_LONGITUDE',120.0)
	CALL PSETR('WIND_STREAMLINE_MIN_SPEED',10.0)            
	CALL PSETC('LEGEND_ENTRY','ON')
	CALL PSETC('TEXT_LINE_1',
     1  'Selected Southern Hemisphere Polar Stereographic 500 hPa '//
     2  'Wind Field')
C
	CALL PSETC('TEXT_LINE_3',
     1  'Streamlines and Isotachs, Streamline Min Speed is 10.0 m/s')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET STREAMLINE SWITCH.
C
	CALL PRESET('WIND_FIELD_TYPE')
C
C	PLOT ISOTACHS - SET ISOTACH SWITCH.
C
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PCONT
C
C	RESET ISOTACH PLOTTING.
C
	CALL PRESET('CONTOUR_DATA_TRANSFORMATION')
C
	RETURN
	END

C
