	PROGRAM STRM01
C
C	THIS PROGRAM DEMONSTRATES MAGICS STREAMLINE PLOTTING.
C	THE METEOROLOGICAL DATA FIELDS ARE STANDARD GLOBAL
C	500 hPa MODEL OUTPUT FIELDS ON A REGULAR 1.5 DEGREE
C	GRID. WIND STREAMLINES AND COASTLINES ARE PROJECTED ONTO
C	MERCATOR MAPS. THE ISOTACHS ARE PLOTTED USING THE
C	DEFAULT VALUES OF MAGICS PARAMETERS FOR ISOTACH PLOTTING,
C	SETTING THE PARAMETER CONTOUR_DATA_TRANSFORMATION TO
C	'ISOTACHS' AND CALLING THE ACTION ROUTINE PCONT.
C
C	OPEN MAGICS.
	CALL POPEN
	CALL PSETC ('PS_DEVICE','ps_a4')
	CALL PSETC ('PS_FILE_NAME','strm01.ps')
	CALL PSETC('SUBPAGE_MAP_PROJECTION','MERCATOR')
	CALL PSETC('PAGE_ID_LINE_USER_TEXT','Tests/Strm01')
	CALL PSETC('PAGE_ID_LINE_ERRORS_PLOT','OFF')    
C
C	PASS THE DATA TO MAGICS.
C
	CALL PSETC('GRIB_INPUT_TYPE','FILE')
	CALL PSETC('GRIB_INPUT_FILE_NAME','data/oldts/500uv.grb')
	CALL PSETI('GRIB_WIND_POSITION_1',1)
	CALL PSETI('GRIB_WIND_POSITION_2',2)
	CALL PGRIB
C
C	PLOT WIND STREAMLINES ON GLOBAL MERCATOR MAP
C	WITH DEFAULT PARAMETER SETTINGS.
C
	CALL STRM01_ONE
	CALL PNEW('PAGE')
C
C	PLOT WIND STREAMLINES ON A SELECTED MERCATOR MAP
C
	CALL STRM01_TWO
	CALL PNEW('PAGE')
C
C	PLOT WIND STREAMLINES AND ISOTACHS ON SELECTED EUROPEAN AREA
C
	CALL STRM01_THREE
	CALL PNEW('PAGE')
C
C	PLOT WIND FLAGS AND ISOTACHS ON A SELECTED EUROPEAN
C	AREA. DEFAULT VALUES FOR WIND FLAG PARAMETERS.
C
	CALL STRM01_FOUR
	CALL PNEW('PAGE')
C
C	PLOT WIND STREAMLINES AND ISOTACHS ON A
C	SELECTED AREA IN THE SOUTHERN HEMISPHERE.
C
	CALL STRM01_FIVE
C
C	CLOSE MAGICS
C
	CALL PCLOSE
	END
	SUBROUTINE STRM01_ONE
C
C	WIND_STREAMLINES ON A MERCATOR PROJECTION.
C	DEFAULT SETTINGS OF STREAMLINE PARAMETERS ARE USED:
C
C	  'WIND_STREAMLINE_ARROW_HEAD_INDEX' , 1
C	  'WIND_STREAMLINE_MIN_DENSITY', 1.0
C	  'WIND_STREAMLINE_CLOSENESS_CHECK', `ON'
C	  'WIND_STREAMLINE_CLOSENESS_MARGIN', 0.2
C	  'WIND_STREAMLINE_THICKNESS' , 2
C	  'WIND_STREAMLINE_COLOUR' , `BLUE'
C	  'WIND_STREAMLINE_STYLE' , `SOLID'
C	  'WIND_STREAMLINE_MIN_SPEED' , 1.0
C	  'WIND_STREAMLINE_CALM_MARKER' , `ON'
C	  'WIND_STREAMLINE_MARKER INDEX' , 3
C	  'WIND_STREAMLINE_MARKER_HEIGHT' , 0.2
C	  'WIND_STREAMLINE_ARROW_HEAD_LENGT' , 0.3
C
C	SET UP MAP AREA
C
	CALL PSETR('SUBPAGE_LOWER_LEFT_LATITUDE',-85.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LATITUDE',85.0)
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETC('TEXT_LINE_1',
     1  'Global Mercator 500 hPa Wind Field')
	CALL PSETC('TEXT_LINE_2',
     1  'U and V Components are on a Regular '//
     2  'Global 1.5 Degree Grid')
	CALL PSETC('TEXT_LINE_3',
     1  'Default values for WIND_STREAMLINE Parameters')
	CALL PSETI('TEXT_LINE_COUNT',3)
	CALL PSETC('TEXT_JUSTIFICATION','CENTRE')
	CALL PSETR('TEXT_REFERENCE_CHARACTER_HEIGHT',0.4)
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET STREAMLINE SWITCH.
C
	CALL PRESET('WIND_FIELD_TYPE')
C
	RETURN
	END
	SUBROUTINE STRM01_TWO
C
C	THIS ROUTINE PLOTS WIND STREAMLINES IN A SELECTED AREA,
C	(30.0 SOUTH TO 30.0 NORTH AND 100.0 WEST TO 100.0 EAST).
C	ARROW_HEAD INDEX IS SET TO 3 AND LENGTH TO 0.5.
C	STREAMLINE THICKNESS IS 3.
C
	CALL PSETR('SUBPAGE_LOWER_LEFT_LATITUDE',-30.0)
	CALL PSETR('SUBPAGE_LOWER_LEFT_LONGITUDE',-100.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LONGITUDE',100.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LATITUDE',30.0)
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETI('WIND_STREAMLINE_ARROW_HEAD_INDEX',3)
	CALL PSETR('WIND_STREAMLINE_ARROW_HEAD_LENGT',0.5)
	CALL PSETI('WIND_STREAMLINE_THICKNESS',4)
C
	CALL PSETC('TEXT_LINE_1',
     1  'Tropical Belt 500 hPa Wind Field in Mercator Projection')
	CALL PSETC('TEXT_LINE_3',
     1  'Streamline Thickness is 4, '//
     2  'Arrowhead Index is 3, Arrowhead Length is 0.5')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET STREAMLINE PARAMETERS.
C
	CALL PRESET('WIND_FIELD_TYPE')
	CALL PRESET('WIND_STREAMLINE_THICKNESS')
	CALL PRESET('WIND_STREAMLINE_ARROW_HEAD_INDEX')
	CALL PRESET('WIND_STREAMLINE_ARROW_HEAD_LENGT')
C
	RETURN
	END
	SUBROUTINE STRM01_THREE
C
C	ISOTACHS AND STREAMLINES ON A SELECTED EUROPEAN AREA.
C	ISOTACHS ARE PLOTTED WITH SHADED CONTOURS (DEFAULT SETTING).
C	LEGEND SET TO 'ON'.
C
	CALL PSETR('SUBPAGE_LOWER_LEFT_LATITUDE',30.0)
	CALL PSETR('SUBPAGE_LOWER_LEFT_LONGITUDE',-20.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LATITUDE',72.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LONGITUDE',72.0)
C
C	SET CONTOUR PARAMETERS AND LEGENDS FOR ISOTACHS.
C
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PSETC('LEGEND','ON')
C
	CALL PSETC('TEXT_LINE_1',
     1  'Selected European 500 hPa Wind Field in Mercator Projection')
	CALL PSETC('TEXT_LINE_3',
     1  'Streamlines and Isotachs '//
     2  '(Default Contour Setting), Calm Marker is OFF, Legend is ON')
C
C	PLOT THE TITLE, COASTLINES AND ISOTACHS.
C
	CALL PTEXT
	CALL PCOAST
	CALL PSETC('CONTOUR_SHADE','ON')
	CALL PSETC('CONTOUR','OFF')
	CALL PSETC('CONTOUR_HILO','OFF')
	CALL PSETC('CONTOUR_LEVEL_SELECTION_TYPE','INTERVAL')
	CALL PSETR('CONTOUR_INTERVAL',10.0)
	CALL PCONT
C
C	RESET ISOTACH PLOTTING.
C
	CALL PRESET('CONTOUR_DATA_TRANSFORMATION')
C
C	PLOT WIND STREAMLINES - SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETC('WIND_STREAMLINE_CALM_MARKER','OFF')
	CALL PWIND
C
C	RESET STREAMLINE SWITCH.
C
	CALL PRESET('WIND_FIELD_TYPE')
	CALL PRESET('WIND_STREAMLINE_CALM_MARKER')
C
	RETURN
	END
	SUBROUTINE STRM01_FOUR
C
C	WIND FLAGS AND STREAMLINES.
C	WIND FLAGS ARE PLOTTED FOR EACH FOURTH
C	GRID POINT. DEFAULT VALUES FOR ALL WIND FLAG
C	PARAMETERS ARE USED. WIND_STREAMLINE_MIN_DENSITY IS 0.5.
C
	CALL PSETC('WIND_FIELD_TYPE','FLAGS')
	CALL PSETR('WIND_THINNING_FACTOR',4.0)
C
	CALL PSETC('TEXT_LINE_3',
     1  'Wind Flags Plotted for Every Fourth Grid Point, '//
     2  'Streamline Min Density is 0.5')
C
C	PLOT THE TITLE, COASTLINES AND WIND FLAGS.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	PLOT WIND STREAMLINES - SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETR('WIND_STREAMLINE_MIN_DENSITY',0.5)
	CALL PWIND
C
C	RESET STREAMLINE PARAMETERS
C
	CALL PRESET('WIND_FIELD_TYPE')
	CALL PRESET('WIND_STREAMLINE_MIN_DENSITY')
C
	RETURN
	END
	SUBROUTINE STRM01_FIVE
C
C	STREAMLINES AND ISOTACHS ON A SOUTHERN HEMISPHERE MERCATOR
C	PROJECTION. WIND_STREAMLINE_CLOSENESS_CHECK IS SET TO 'OFF'.
C
C	SET STREAMLINE SWITCH.
C
	CALL PSETC('WIND_FIELD_TYPE','STREAMLINES')
	CALL PSETR('SUBPAGE_LOWER_LEFT_LONGITUDE',-160.0)
	CALL PSETR('SUBPAGE_LOWER_LEFT_LATITUDE',-80.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LONGITUDE',0.0)
	CALL PSETR('SUBPAGE_UPPER_RIGHT_LATITUDE',-20.0)
C
C	PLOT STREAMLINES.
C
	CALL PSETC('WIND_STREAMLINE_CLOSENESS_CHECK','OFF')
	CALL PSETI('WIND_STREAMLINE_THICKNESS',1)
C
	CALL PSETC('TEXT_LINE_1',
     1  'Southern Hemisphere 500 hPa Wind Field in Mercator Projection')
	CALL PSETC('TEXT_LINE_3',
     1  'Wind Streamline Closeness Check is OFF, '//
     2  'Thickness is 1. ')
C
C	PLOT THE TITLE, COASTLINES AND WIND STREAMLINES.
C
	CALL PTEXT
	CALL PCOAST
	CALL PWIND
C
C	RESET STREAMLINE SWITCH.
C
	CALL PRESET('WIND_FIELD_TYPE')
C
C	PLOT ISOTACHS.
C
	CALL PSETC('CONTOUR_DATA_TRANSFORMATION','ISOTACHS')
	CALL PSETC('CONTOUR_SHADE','ON')
	CALL PSETC('CONTOUR','OFF')
	CALL PSETC('CONTOUR_HILO','OFF')
	CALL PSETR('CONTOUR_SHADE_MIN_LEVEL_DENSITY',50.0)
	CALL PSETR('CONTOUR_SHADE_MAX_LEVEL_DENSITY',500.0)
	CALL PSETR('CONTOUR_INTERVAL',10.0)
	CALL PCONT
C
C	RESET ISOTACH PLOTTING.
C
	CALL PRESET('CONTOUR_DATA_TRANSFORMATION')
C
	RETURN
	END
