#!/usr/bin/env python
#
# Copyright 2007 European Centre for Medium-Range Weather Forecasts (ECMWF)
# 
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
# 
# 	http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.
#
#
# This script is provided as help to clip / reduce size of mapgen data files.
#
import sys

if len(sys.argv) < 6:
    print "Not enough parameters!"
    print "mapgen_clip in.mapgen out.mapgen lon_min lon_max lat_min lat_max"
    sys.exit()

lon_min = float(sys.argv[3])
lon_max = float(sys.argv[4])
lat_min = float(sys.argv[5])
lat_max = float(sys.argv[6])

fin = open(sys.argv[1], 'r')
fou = open(sys.argv[2], 'w')

begin = ""

for line in fin:
  if line == "# -b\n":
    begin=line
  else:
    s = line.split()
    if float(s[0]) > lon_min and float(s[0]) < lon_max:
     if float(s[1]) > lat_min and float(s[1]) < lat_max:
      if begin != "":
        fou.write(begin)
        begin = ""
      fou.write(line)

fin.close()
fou.close()
